#===========================================================================
# File Name	: @Source: /net/splinter/fed/cvs/ae-ware/rc/phys_qos_edi_stats.tcl,v @
# Date Created	: 10/25/2004
# Date Modified	: @Date: 2012/03/10 10:21:39 @
# Version	: @Revision: 1.1 @
# Summary	: Generates QoS stats from Encounter and populates an array
# Keywords      : QoS Stats Array Phys
#
# Description:
#               Generates QoS stats in EDI and populates an array with a consitent
#               structure to that used in RC by the phys::qos_stats and phys::qos_summary
#               commands. This script essentially provides a mechanism to gather
#               the same metrics in EDI that are generated by the rc proc
#               phys::qos_stats.
# Assumptions:
#	None
#
#===========================================================================
if {![info exists ::ns(compat)]}     { set ::ns(compat) "::aeware::compat" }
if {![info exists ::ns(applet)]}     { set ::ns(applet) "${::ns(compat)}::applet" }

package require compatibility 1.38

namespace eval $::ns(compat) {
  # writing stats array:
  # proc qos_write_stats_array ()

  # 
  # Import required compatibility procs
  # 
  if {[llength [info commands $::ns(compat)::get_tool]]} {
    if {![llength [info commands get_tool]]} { namespace import $::ns(compat)::get_tool }
  }
  if {[llength [info commands $::ns(compat)::get_tool_version]]} {
    if {![llength [info commands get_tool_version]]} { namespace import $::ns(compat)::get_tool_version }
  }
  if {[llength [info commands $::ns(compat)::find]]} {
    if {![llength [info commands find]]} { namespace import $::ns(compat)::find }
  }

  namespace export qos_write_stats_array
  proc qos_write_stats_array {args} {
    #
    # Set the variable defaults
    #
    set aname       "::phys::stats"       ; # default name for the array
    set filename    ""                    ; # output filename
  
    #
    # Option processing
    #
    switch -- [parse_options [calling_proc] fileName $args \
      "-name sos array name to use upon reload, default is to overwrite the statistics that are currently in memory" aname \
      "-no_human_readable bos do not write the human readable section" no_human \
      "dos(design) design" des ] {
      -2 { return }
      0 { error "Failed on [calling_proc]" }
    }
  
  
    ########################################################################## 
    # Generate Output
    ########################################################################## 
    set fil [open $fileName "w"]
    # Header
    puts $fil "#####################################################################"
    puts $fil "#"
    puts $fil "# RTL Compiler Compatible QoS Statistics Array"
    puts $fil "# Created by [get_tool] [get_tool_version]"
    puts $fil "#   on [clock format [clock seconds] -format {%x %X}]"
    puts $fil "#"
    puts $fil "#####################################################################"
    # capture the filename - file must exist at this point
    set ::phys::stats([find -design /],file) [glob $filename]
  
    # Array Contents
    puts $fil "\n# Array Name"
    puts $fil "# The ::phys::set_import_array_name global can be used to overide "
    puts $fil "#   the array name when sourcing this file."
    puts $fil "if \{\[info exists ::phys::set_import_array_name] && \$::phys::set_import_array_name ne \"\"\} \{"
    puts $fil "  set array_name \$::phys::set_import_array_name"
    puts $fil "\} else \{"
    puts $fil "  set array_name $aname"
    puts $fil "\}"
    puts $fil "\n# Array Contents"
    puts $fil "# The array contents are specified in a name value pairs"
    puts $fil "#   suitable for use with the 'array set' command"
    puts $fil "set array_list \{[array get ::phys::stats]\}"
    puts $fil "array set \$array_name \$array_list"
    puts $fil "set ::phys::imported_stats_array \$array_name"
    puts $fil "puts \"Finished importing statistics array (phys::imported_stats_array == \$::phys::imported_stats_array)\""

    #
    # Array Contents in Human Readable Form (if needed)
    #
    if {!$no_human} {
      puts $fil "\n\n# Array Contents in Human Readable Format"
      set parray_out [parray ::phys::stats]
      set parray_out [regsub "^Sourcing.+\\\.\n" $parray_out ""]
      set parray_out [regsub -all "::phys::stats" $parray_out "\#  "]
      puts $fil "$parray_out"
    }

    if {[info exists ::phys::stats([find -design /],file)]} {
      unset ::phys::stats([find -design /],file)
    }

    #
    # Close Files
    #
    close $fil
  }
  add_command_help qos_write_stats_array "write the array out"
}

regexp {\d+(\.\d+)+} {@Revision: 1.1 @} pkgRev
package provide ::applet::phys_qos_edi_stats $pkgRev

#===========================================================================
#
# Copyright 1997-2012 Cadence Design Systems, Inc.  All rights reserved worldwide. 
#
# The Tcl computer program and related information (collectively "Licensed Material") 
# contained herein are protected by copyright law and international treaties. 
#
# Cadence grants Recipient of the Licensed Material a nonexclusive right
# to use, copy, and modify the Licensed Material.   Should Recipient
# desire to distribute any portion of the Licensed Material, Recipient
# must obtain Cadence's permission.  In no event shall Recipient use the 
# Licensed Material for benchmarking purposes against Cadence's products.   
#
# The Licensed Material is provided to Recipient to use at Recipient's
# own risk. The Licensed Material may not be compatible with current or 
# future versions of Cadence products, and Cadence will not provide any 
# technical support for the Licensed Material, whether modified or not 
# by the Recipient.  THE LICENSED MATERIAL IS PROVIDED "AS IS" AND WITH 
# NO WARRANTIES, INCLUDING WITHOUT LIMITATION ANY EXPRESS WARRANTIES OR 
# IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR USE.
#
# IN NO EVENT SHALL CADENCE BE LIABLE TO RECIPIENT OR ANY THIRD PARTY
# FOR ANY INCIDENTAL, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES, OR ANY 
# OTHER DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR
# LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS 
# INFORMATION, OR OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OR
# INABILITY TO USE LICENSED MATERIAL, WHETHER OR NOT THE POSSIBILITY OR 
# CAUSE OF SUCH DAMAGES WAS KNOWN TO CADENCE.
#
# Cadence Design Systems, Inc.
# 2655 Seely Avenue
# San Jose, CA 95134
#
#===========================================================================
