# This is an internal file generated by Innovus v22.10-p001_1 on Sun Jan 12 09:38:51 2025

qxDPInvokeSignOffExtractionCCEJob -jobid 6 -numjobs 16 \
		14489 14489 1 1 \
		"extLogDir/IQuantus_12-Jan-2025_09:38:36_14489_ciapsI/.extr.pp_fir_u_0.0.parallel_proc.14489_6.res" "xyz"
