
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point sclk sclk -type PI PI
add mapped point ss ss -type PI PI
add mapped point mosi mosi -type PI PI

//output ports
add mapped point vcoTrim[15] vcoTrim[15] -type PO PO
add mapped point vcoTrim[14] vcoTrim[14] -type PO PO
add mapped point vcoTrim[13] vcoTrim[13] -type PO PO
add mapped point vcoTrim[12] vcoTrim[12] -type PO PO
add mapped point vcoTrim[11] vcoTrim[11] -type PO PO
add mapped point vcoTrim[10] vcoTrim[10] -type PO PO
add mapped point vcoTrim[9] vcoTrim[9] -type PO PO
add mapped point vcoTrim[8] vcoTrim[8] -type PO PO
add mapped point vcoTrim[7] vcoTrim[7] -type PO PO
add mapped point vcoTrim[6] vcoTrim[6] -type PO PO
add mapped point vcoTrim[5] vcoTrim[5] -type PO PO
add mapped point vcoTrim[4] vcoTrim[4] -type PO PO
add mapped point vcoTrim[3] vcoTrim[3] -type PO PO
add mapped point vcoTrim[2] vcoTrim[2] -type PO PO
add mapped point vcoTrim[1] vcoTrim[1] -type PO PO
add mapped point vcoTrim[0] vcoTrim[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point fifo_inst/fifo_full/q fifo_inst/fifo_full_reg/Q  -type DFF DFF
add mapped point fifo_inst/fifo_empty/q fifo_inst/fifo_empty_reg/Q  -type DFF DFF
add mapped point fifo_inst/count[0]/q fifo_inst/count_reg[0]/Q  -type DFF DFF
add mapped point fifo_inst/count[1]/q fifo_inst/count_reg[1]/Q  -type DFF DFF
add mapped point fifo_inst/count[2]/q fifo_inst/count_reg[2]/Q  -type DFF DFF
add mapped point fifo_inst/count[3]/q fifo_inst/count_reg[3]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[0]/q fifo_inst/data_out_reg[0]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[1]/q fifo_inst/data_out_reg[1]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[2]/q fifo_inst/data_out_reg[2]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[3]/q fifo_inst/data_out_reg[3]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[4]/q fifo_inst/data_out_reg[4]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[5]/q fifo_inst/data_out_reg[5]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[6]/q fifo_inst/data_out_reg[6]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[7]/q fifo_inst/data_out_reg[7]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[8]/q fifo_inst/data_out_reg[8]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[9]/q fifo_inst/data_out_reg[9]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[10]/q fifo_inst/data_out_reg[10]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[11]/q fifo_inst/data_out_reg[11]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[12]/q fifo_inst/data_out_reg[12]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[13]/q fifo_inst/data_out_reg[13]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[14]/q fifo_inst/data_out_reg[14]/Q  -type DFF DFF
add mapped point fifo_inst/data_out[15]/q fifo_inst/data_out_reg[15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][0]/q fifo_inst/fifo_mem_reg[0][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][1]/q fifo_inst/fifo_mem_reg[0][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][2]/q fifo_inst/fifo_mem_reg[0][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][3]/q fifo_inst/fifo_mem_reg[0][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][4]/q fifo_inst/fifo_mem_reg[0][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][5]/q fifo_inst/fifo_mem_reg[0][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][6]/q fifo_inst/fifo_mem_reg[0][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][7]/q fifo_inst/fifo_mem_reg[0][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][8]/q fifo_inst/fifo_mem_reg[0][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][9]/q fifo_inst/fifo_mem_reg[0][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][10]/q fifo_inst/fifo_mem_reg[0][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][11]/q fifo_inst/fifo_mem_reg[0][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][12]/q fifo_inst/fifo_mem_reg[0][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][13]/q fifo_inst/fifo_mem_reg[0][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][14]/q fifo_inst/fifo_mem_reg[0][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[0][15]/q fifo_inst/fifo_mem_reg[0][15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][0]/q fifo_inst/fifo_mem_reg[1][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][1]/q fifo_inst/fifo_mem_reg[1][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][2]/q fifo_inst/fifo_mem_reg[1][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][3]/q fifo_inst/fifo_mem_reg[1][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][4]/q fifo_inst/fifo_mem_reg[1][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][5]/q fifo_inst/fifo_mem_reg[1][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][6]/q fifo_inst/fifo_mem_reg[1][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][7]/q fifo_inst/fifo_mem_reg[1][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][8]/q fifo_inst/fifo_mem_reg[1][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][9]/q fifo_inst/fifo_mem_reg[1][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][10]/q fifo_inst/fifo_mem_reg[1][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][11]/q fifo_inst/fifo_mem_reg[1][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][12]/q fifo_inst/fifo_mem_reg[1][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][13]/q fifo_inst/fifo_mem_reg[1][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][14]/q fifo_inst/fifo_mem_reg[1][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[1][15]/q fifo_inst/fifo_mem_reg[1][15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][0]/q fifo_inst/fifo_mem_reg[2][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][1]/q fifo_inst/fifo_mem_reg[2][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][2]/q fifo_inst/fifo_mem_reg[2][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][3]/q fifo_inst/fifo_mem_reg[2][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][4]/q fifo_inst/fifo_mem_reg[2][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][5]/q fifo_inst/fifo_mem_reg[2][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][6]/q fifo_inst/fifo_mem_reg[2][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][7]/q fifo_inst/fifo_mem_reg[2][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][8]/q fifo_inst/fifo_mem_reg[2][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][9]/q fifo_inst/fifo_mem_reg[2][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][10]/q fifo_inst/fifo_mem_reg[2][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][11]/q fifo_inst/fifo_mem_reg[2][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][12]/q fifo_inst/fifo_mem_reg[2][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][13]/q fifo_inst/fifo_mem_reg[2][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][14]/q fifo_inst/fifo_mem_reg[2][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[2][15]/q fifo_inst/fifo_mem_reg[2][15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][0]/q fifo_inst/fifo_mem_reg[3][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][1]/q fifo_inst/fifo_mem_reg[3][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][2]/q fifo_inst/fifo_mem_reg[3][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][3]/q fifo_inst/fifo_mem_reg[3][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][4]/q fifo_inst/fifo_mem_reg[3][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][5]/q fifo_inst/fifo_mem_reg[3][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][6]/q fifo_inst/fifo_mem_reg[3][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][7]/q fifo_inst/fifo_mem_reg[3][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][8]/q fifo_inst/fifo_mem_reg[3][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][9]/q fifo_inst/fifo_mem_reg[3][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][10]/q fifo_inst/fifo_mem_reg[3][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][11]/q fifo_inst/fifo_mem_reg[3][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][12]/q fifo_inst/fifo_mem_reg[3][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][13]/q fifo_inst/fifo_mem_reg[3][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][14]/q fifo_inst/fifo_mem_reg[3][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[3][15]/q fifo_inst/fifo_mem_reg[3][15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][0]/q fifo_inst/fifo_mem_reg[4][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][1]/q fifo_inst/fifo_mem_reg[4][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][2]/q fifo_inst/fifo_mem_reg[4][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][3]/q fifo_inst/fifo_mem_reg[4][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][4]/q fifo_inst/fifo_mem_reg[4][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][5]/q fifo_inst/fifo_mem_reg[4][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][6]/q fifo_inst/fifo_mem_reg[4][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][7]/q fifo_inst/fifo_mem_reg[4][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][8]/q fifo_inst/fifo_mem_reg[4][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][9]/q fifo_inst/fifo_mem_reg[4][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][10]/q fifo_inst/fifo_mem_reg[4][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][11]/q fifo_inst/fifo_mem_reg[4][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][12]/q fifo_inst/fifo_mem_reg[4][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][13]/q fifo_inst/fifo_mem_reg[4][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][14]/q fifo_inst/fifo_mem_reg[4][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[4][15]/q fifo_inst/fifo_mem_reg[4][15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][0]/q fifo_inst/fifo_mem_reg[5][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][1]/q fifo_inst/fifo_mem_reg[5][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][2]/q fifo_inst/fifo_mem_reg[5][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][3]/q fifo_inst/fifo_mem_reg[5][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][4]/q fifo_inst/fifo_mem_reg[5][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][5]/q fifo_inst/fifo_mem_reg[5][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][6]/q fifo_inst/fifo_mem_reg[5][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][7]/q fifo_inst/fifo_mem_reg[5][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][8]/q fifo_inst/fifo_mem_reg[5][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][9]/q fifo_inst/fifo_mem_reg[5][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][10]/q fifo_inst/fifo_mem_reg[5][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][11]/q fifo_inst/fifo_mem_reg[5][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][12]/q fifo_inst/fifo_mem_reg[5][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][13]/q fifo_inst/fifo_mem_reg[5][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][14]/q fifo_inst/fifo_mem_reg[5][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[5][15]/q fifo_inst/fifo_mem_reg[5][15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][0]/q fifo_inst/fifo_mem_reg[6][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][1]/q fifo_inst/fifo_mem_reg[6][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][2]/q fifo_inst/fifo_mem_reg[6][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][3]/q fifo_inst/fifo_mem_reg[6][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][4]/q fifo_inst/fifo_mem_reg[6][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][5]/q fifo_inst/fifo_mem_reg[6][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][6]/q fifo_inst/fifo_mem_reg[6][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][7]/q fifo_inst/fifo_mem_reg[6][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][8]/q fifo_inst/fifo_mem_reg[6][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][9]/q fifo_inst/fifo_mem_reg[6][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][10]/q fifo_inst/fifo_mem_reg[6][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][11]/q fifo_inst/fifo_mem_reg[6][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][12]/q fifo_inst/fifo_mem_reg[6][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][13]/q fifo_inst/fifo_mem_reg[6][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][14]/q fifo_inst/fifo_mem_reg[6][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[6][15]/q fifo_inst/fifo_mem_reg[6][15]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][0]/q fifo_inst/fifo_mem_reg[7][0]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][1]/q fifo_inst/fifo_mem_reg[7][1]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][2]/q fifo_inst/fifo_mem_reg[7][2]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][3]/q fifo_inst/fifo_mem_reg[7][3]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][4]/q fifo_inst/fifo_mem_reg[7][4]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][5]/q fifo_inst/fifo_mem_reg[7][5]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][6]/q fifo_inst/fifo_mem_reg[7][6]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][7]/q fifo_inst/fifo_mem_reg[7][7]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][8]/q fifo_inst/fifo_mem_reg[7][8]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][9]/q fifo_inst/fifo_mem_reg[7][9]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][10]/q fifo_inst/fifo_mem_reg[7][10]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][11]/q fifo_inst/fifo_mem_reg[7][11]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][12]/q fifo_inst/fifo_mem_reg[7][12]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][13]/q fifo_inst/fifo_mem_reg[7][13]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][14]/q fifo_inst/fifo_mem_reg[7][14]/Q  -type DFF DFF
add mapped point fifo_inst/fifo_mem[7][15]/q fifo_inst/fifo_mem_reg[7][15]/Q  -type DFF DFF
add mapped point fifo_inst/read_ptr[0]/q fifo_inst/read_ptr_reg[0]/Q  -type DFF DFF
add mapped point fifo_inst/read_ptr[1]/q fifo_inst/read_ptr_reg[1]/Q  -type DFF DFF
add mapped point fifo_inst/read_ptr[2]/q fifo_inst/read_ptr_reg[2]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[0]/q fifo_inst/valid_data_reg[0]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[1]/q fifo_inst/valid_data_reg[1]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[2]/q fifo_inst/valid_data_reg[2]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[3]/q fifo_inst/valid_data_reg[3]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[4]/q fifo_inst/valid_data_reg[4]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[5]/q fifo_inst/valid_data_reg[5]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[6]/q fifo_inst/valid_data_reg[6]/Q  -type DFF DFF
add mapped point fifo_inst/valid_data[7]/q fifo_inst/valid_data_reg[7]/Q  -type DFF DFF
add mapped point fifo_inst/write_ptr[0]/q fifo_inst/write_ptr_reg[0]/Q  -type DFF DFF
add mapped point fifo_inst/write_ptr[1]/q fifo_inst/write_ptr_reg[1]/Q  -type DFF DFF
add mapped point fifo_inst/write_ptr[2]/q fifo_inst/write_ptr_reg[2]/Q  -type DFF DFF
add mapped point vcoTrim[0]/q vcoTrim_reg[0]/Q  -type DFF DFF
add mapped point vcoTrim[14]/q vcoTrim_reg[14]/Q  -type DFF DFF
add mapped point vcoTrim[12]/q vcoTrim_reg[12]/Q  -type DFF DFF
add mapped point vcoTrim[8]/q vcoTrim_reg[8]/Q  -type DFF DFF
add mapped point vcoTrim[15]/q vcoTrim_reg[15]/Q  -type DFF DFF
add mapped point vcoTrim[7]/q vcoTrim_reg[7]/Q  -type DFF DFF
add mapped point vcoTrim[11]/q vcoTrim_reg[11]/Q  -type DFF DFF
add mapped point vcoTrim[6]/q vcoTrim_reg[6]/Q  -type DFF DFF
add mapped point vcoTrim[13]/q vcoTrim_reg[13]/Q  -type DFF DFF
add mapped point vcoTrim[10]/q vcoTrim_reg[10]/Q  -type DFF DFF
add mapped point vcoTrim[4]/q vcoTrim_reg[4]/Q  -type DFF DFF
add mapped point vcoTrim[3]/q vcoTrim_reg[3]/Q  -type DFF DFF
add mapped point vcoTrim[9]/q vcoTrim_reg[9]/Q  -type DFF DFF
add mapped point vcoTrim[2]/q vcoTrim_reg[2]/Q  -type DFF DFF
add mapped point vcoTrim[1]/q vcoTrim_reg[1]/Q  -type DFF DFF
add mapped point vcoTrim[5]/q vcoTrim_reg[5]/Q  -type DFF DFF
add mapped point ckDiv/clk_out/q ckDiv_clk_out_reg/Q  -type DFF DFF
add mapped point ckDiv/count[0]/q ckDiv_count_reg[0]/Q  -type DFF DFF
add mapped point ckDiv/count[1]/q ckDiv_count_reg[1]/Q  -type DFF DFF
add mapped point ckDiv/count[2]/q ckDiv_count_reg[2]/Q  -type DFF DFF
add mapped point ckDiv/count[3]/q ckDiv_count_reg[3]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[0]/q data_register_inst_data_reg_reg[0]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[1]/q data_register_inst_data_reg_reg[1]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[2]/q data_register_inst_data_reg_reg[2]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[3]/q data_register_inst_data_reg_reg[3]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[4]/q data_register_inst_data_reg_reg[4]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[5]/q data_register_inst_data_reg_reg[5]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[6]/q data_register_inst_data_reg_reg[6]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[7]/q data_register_inst_data_reg_reg[7]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[8]/q data_register_inst_data_reg_reg[8]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[9]/q data_register_inst_data_reg_reg[9]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[10]/q data_register_inst_data_reg_reg[10]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[11]/q data_register_inst_data_reg_reg[11]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[12]/q data_register_inst_data_reg_reg[12]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[13]/q data_register_inst_data_reg_reg[13]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[14]/q data_register_inst_data_reg_reg[14]/Q  -type DFF DFF
add mapped point data_register_inst/data_reg[15]/q data_register_inst_data_reg_reg[15]/Q  -type DFF DFF
add mapped point data_register_inst/data_valid/q data_register_inst_data_valid_reg/Q  -type DFF DFF
add mapped point spi_slave_inst/bit_count[0]/q spi_slave_inst_bit_count_reg[0]/Q  -type DFF DFF
add mapped point spi_slave_inst/bit_count[1]/q spi_slave_inst_bit_count_reg[1]/Q  -type DFF DFF
add mapped point spi_slave_inst/bit_count[2]/q spi_slave_inst_bit_count_reg[2]/Q  -type DFF DFF
add mapped point spi_slave_inst/bit_count[3]/q spi_slave_inst_bit_count_reg[3]/Q  -type DFF DFF
add mapped point spi_slave_inst/bit_count[4]/q spi_slave_inst_bit_count_reg[4]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[0]/q spi_slave_inst_latched_data_reg[0]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[1]/q spi_slave_inst_latched_data_reg[1]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[2]/q spi_slave_inst_latched_data_reg[2]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[3]/q spi_slave_inst_latched_data_reg[3]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[4]/q spi_slave_inst_latched_data_reg[4]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[5]/q spi_slave_inst_latched_data_reg[5]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[6]/q spi_slave_inst_latched_data_reg[6]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[7]/q spi_slave_inst_latched_data_reg[7]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[8]/q spi_slave_inst_latched_data_reg[8]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[9]/q spi_slave_inst_latched_data_reg[9]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[10]/q spi_slave_inst_latched_data_reg[10]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[11]/q spi_slave_inst_latched_data_reg[11]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[12]/q spi_slave_inst_latched_data_reg[12]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[13]/q spi_slave_inst_latched_data_reg[13]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[14]/q spi_slave_inst_latched_data_reg[14]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[15]/q spi_slave_inst_latched_data_reg[15]/Q  -type DFF DFF
add mapped point spi_slave_inst/latched_data[26]/q spi_slave_inst_latched_data_reg[26]/Q  -type DFF DFF
add mapped point spi_slave_inst/oe/q spi_slave_inst_oe_reg/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[0]/q spi_slave_inst_temp_data_reg[0]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[1]/q spi_slave_inst_temp_data_reg[1]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[2]/q spi_slave_inst_temp_data_reg[2]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[3]/q spi_slave_inst_temp_data_reg[3]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[4]/q spi_slave_inst_temp_data_reg[4]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[5]/q spi_slave_inst_temp_data_reg[5]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[6]/q spi_slave_inst_temp_data_reg[6]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[7]/q spi_slave_inst_temp_data_reg[7]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[8]/q spi_slave_inst_temp_data_reg[8]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[9]/q spi_slave_inst_temp_data_reg[9]/Q  -type DFF DFF
add mapped point spi_slave_inst/temp_data[10]/q spi_slave_inst_temp_data_reg[10]/Q  -type DFF DFF
add mapped point spi_valid_prev/q spi_valid_prev_reg/Q  -type DFF DFF
add mapped point spi_valid/q spi_valid_reg/Q  -type DFF DFF
add mapped point vcoDec_inst/data_received/q vcoDec_inst_data_received_reg/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[0]/q vcoDec_inst_dec_0_binOut_reg[0]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[1]/q vcoDec_inst_dec_0_binOut_reg[1]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[2]/q vcoDec_inst_dec_0_binOut_reg[2]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[3]/q vcoDec_inst_dec_0_binOut_reg[3]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[4]/q vcoDec_inst_dec_0_binOut_reg[4]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[5]/q vcoDec_inst_dec_0_binOut_reg[5]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[6]/q vcoDec_inst_dec_0_binOut_reg[6]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[7]/q vcoDec_inst_dec_0_binOut_reg[7]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[8]/q vcoDec_inst_dec_0_binOut_reg[8]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[9]/q vcoDec_inst_dec_0_binOut_reg[9]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[10]/q vcoDec_inst_dec_0_binOut_reg[10]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[11]/q vcoDec_inst_dec_0_binOut_reg[11]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[12]/q vcoDec_inst_dec_0_binOut_reg[12]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[13]/q vcoDec_inst_dec_0_binOut_reg[13]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[14]/q vcoDec_inst_dec_0_binOut_reg[14]/Q  -type DFF DFF
add mapped point vcoDec_inst/dec_0/binOut[15]/q vcoDec_inst_dec_0_binOut_reg[15]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
