// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_ppfir\comp_signed_mag_0.v
// Created: 2025-01-02 12:07:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: comp_signed_mag_0
// Source Path: scpa_ppfir/pp_fir/comp_signed_mag_0
// Hierarchy Level: 1
// Model version: 1.25
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module comp_signed_mag_unary
          (In1_re,
           In1_im,
           mag_re,
           sign_re,
           mag_im,
           sign_im,
           clk,
           rst);

  input wire clk;
  input wire rst;
  input   signed [8:0] In1_re;  // sfix9
  input   signed [8:0] In1_im;  // sfix9
  output  reg [255:0] mag_re;  // uint8
  output  reg sign_re;  // ufix1
  output  reg [255:0] mag_im;  // uint8
  output  reg sign_im;  // ufix1

  wire signed [9:0] twos_re;  // sfix10
  reg signed [9:0] Abs_re_stage1;  // sfix10
  reg sign_re_stage2;
  reg [7:0] Abs_re_stage2;
  wire signed [9:0] twos_im;  // sfix10
  reg signed [9:0] Abs_im_stage1;  // sfix10
  reg sign_im_stage2;
  reg [7:0] Abs_im_stage2;
  wire [255:0] re_mag;
  wire [255:0] im_mag;

  assign twos_re = {In1_re[8], In1_re};
  assign twos_im = {In1_im[8], In1_im};

  always @ (posedge clk or negedge rst) begin
     if (!rst) begin
        Abs_re_stage1 <= 10'sb0000000000;
        Abs_im_stage1 <= 10'sb0000000000;
        Abs_re_stage2 <= 8'h00;
        Abs_im_stage2 <= 8'h00;
        sign_im_stage2 <= 1'b0;
        sign_im_stage2 <= 1'b0;
        mag_re <= 256'h0000000000000000000000000000000000000000000000000000000000000000;
        sign_re <= 1'b0;
        mag_im <= 256'h0000000000000000000000000000000000000000000000000000000000000000;
        sign_im <= 1'b0;
     end else begin
        //Stage 1: Calculate Absolute Value
        Abs_re_stage1 <= (In1_re < 9'sb000000000 ?  - (twos_re) : (twos_re));
        Abs_im_stage1 <= (In1_im < 9'sb000000000 ?  - (twos_im) : (twos_im));

        //Stage 2: Extract Sign Bits and Magnitude Bits
        Abs_re_stage2 <= Abs_re_stage1[7:0];
        Abs_im_stage2 <= Abs_im_stage1[7:0];
        sign_re_stage2 <= In1_re[8];
        sign_im_stage2 <= In1_im[8];

        //Stage 3: Assign Magnitude and Sign to Output
        sign_re <= sign_re_stage2;
        mag_re <= re_mag;
        sign_im <= sign_im_stage2;
        mag_im <= im_mag;
     end
  end

  b2u_8to255_quad b2u_8to255_quad_0 (
    .clk(clk),
    .rst(rst),
    .enable(1'b1),
    .iIn(Abs_re_stage2),
    .iMsb(1'b0),
    .qIn(Abs_im_stage2),
    .qMsb(1'b0),
    .iOut(re_mag),
    .qOut(im_mag)
  );

endmodule  // comp_signed_mag_unary