// -------------------------------------------------------------
// 
// File Name: C:\Users\Meysam\OneDrive - Virginia Tech\Projects\MATLAB\WLAN\EHTTransmitterMeasurementsExample\HDL_Codes\Code\FIR_Model\FIR_Filter_M.v
// Created: 2024-11-26 17:13:41
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 6.25e-10
// Target subsystem base rate: 6.25e-10
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        6.25e-10
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Out1_re                       ce_out        6.25e-10
// Out1_im                       ce_out        6.25e-10
// Out2_re                       ce_out        6.25e-10
// Out2_im                       ce_out        6.25e-10
// Out3_re                       ce_out        6.25e-10
// Out3_im                       ce_out        6.25e-10
// Out4_re                       ce_out        6.25e-10
// Out4_im                       ce_out        6.25e-10
// Out5_re                       ce_out        6.25e-10
// Out5_im                       ce_out        6.25e-10
// Out6_re                       ce_out        6.25e-10
// Out6_im                       ce_out        6.25e-10
// Out7_re                       ce_out        6.25e-10
// Out7_im                       ce_out        6.25e-10
// Out8_re                       ce_out        6.25e-10
// Out8_im                       ce_out        6.25e-10
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIR_Filter_M
// Source Path: FIR_Model/FIR_Filter_M
// Hierarchy Level: 0
// Model version: 2.12
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIR_Filter_M
          (clk,
           reset,
           clk_enable,
           In1_re,
           In1_im,
           ce_out,
           Out1_re,
           Out1_im,
           Out2_re,
           Out2_im,
           Out3_re,
           Out3_im,
           Out4_re,
           Out4_im,
           Out5_re,
           Out5_im,
           Out6_re,
           Out6_im,
           Out7_re,
           Out7_im,
           Out8_re,
           Out8_im);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] In1_re;  // sfix16_En15
  input   signed [15:0] In1_im;  // sfix16_En15
  output  ce_out;
  output  signed [8:0] Out1_re;  // sfix9_E2
  output  signed [8:0] Out1_im;  // sfix9_E2
  output  signed [8:0] Out2_re;  // sfix9_E2
  output  signed [8:0] Out2_im;  // sfix9_E2
  output  signed [8:0] Out3_re;  // sfix9_E2
  output  signed [8:0] Out3_im;  // sfix9_E2
  output  signed [8:0] Out4_re;  // sfix9_E2
  output  signed [8:0] Out4_im;  // sfix9_E2
  output  signed [8:0] Out5_re;  // sfix9_E2
  output  signed [8:0] Out5_im;  // sfix9_E2
  output  signed [8:0] Out6_re;  // sfix9_E2
  output  signed [8:0] Out6_im;  // sfix9_E2
  output  signed [8:0] Out7_re;  // sfix9_E2
  output  signed [8:0] Out7_im;  // sfix9_E2
  output  signed [8:0] Out8_re;  // sfix9_E2
  output  signed [8:0] Out8_im;  // sfix9_E2


  wire signed [15:0] Discrete_FIR_Filter_1_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_1_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion2_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion2_out1_im;  // sfix9_E2
  wire signed [15:0] Discrete_FIR_Filter_2_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_2_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion1_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion1_out1_im;  // sfix9_E2
  wire signed [15:0] Discrete_FIR_Filter_3_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_3_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion3_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion3_out1_im;  // sfix9_E2
  wire signed [15:0] Discrete_FIR_Filter_4_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_4_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion4_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion4_out1_im;  // sfix9_E2
  wire signed [15:0] Discrete_FIR_Filter_5_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_5_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion5_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion5_out1_im;  // sfix9_E2
  wire signed [15:0] Discrete_FIR_Filter_6_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_6_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion6_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion6_out1_im;  // sfix9_E2
  wire signed [15:0] Discrete_FIR_Filter_7_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_7_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion7_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion7_out1_im;  // sfix9_E2
  wire signed [15:0] Discrete_FIR_Filter_8_out1_re;  // sfix16_En5
  wire signed [15:0] Discrete_FIR_Filter_8_out1_im;  // sfix16_En5
  wire signed [8:0] Data_Type_Conversion8_out1_re;  // sfix9_E2
  wire signed [8:0] Data_Type_Conversion8_out1_im;  // sfix9_E2


  Discrete_FIR_Filter_1 u_Discrete_FIR_Filter_1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_1_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_1_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_1_out_re(Discrete_FIR_Filter_1_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_1_out_im(Discrete_FIR_Filter_1_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion2_out1_re = Discrete_FIR_Filter_1_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_1_out1_re[6]});
  assign Data_Type_Conversion2_out1_im = Discrete_FIR_Filter_1_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_1_out1_im[6]});
  assign Out1_re = Data_Type_Conversion2_out1_re;

  assign Out1_im = Data_Type_Conversion2_out1_im;

  Discrete_FIR_Filter_2 u_Discrete_FIR_Filter_2 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_2_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_2_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_2_out_re(Discrete_FIR_Filter_2_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_2_out_im(Discrete_FIR_Filter_2_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion1_out1_re = Discrete_FIR_Filter_2_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_2_out1_re[6]});
  assign Data_Type_Conversion1_out1_im = Discrete_FIR_Filter_2_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_2_out1_im[6]});
  assign Out2_re = Data_Type_Conversion1_out1_re;

  assign Out2_im = Data_Type_Conversion1_out1_im;

  Discrete_FIR_Filter_3 u_Discrete_FIR_Filter_3 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_3_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_3_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_3_out_re(Discrete_FIR_Filter_3_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_3_out_im(Discrete_FIR_Filter_3_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion3_out1_re = Discrete_FIR_Filter_3_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_3_out1_re[6]});
  assign Data_Type_Conversion3_out1_im = Discrete_FIR_Filter_3_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_3_out1_im[6]});
  assign Out3_re = Data_Type_Conversion3_out1_re;

  assign Out3_im = Data_Type_Conversion3_out1_im;

  Discrete_FIR_Filter_4 u_Discrete_FIR_Filter_4 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_4_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_4_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_4_out_re(Discrete_FIR_Filter_4_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_4_out_im(Discrete_FIR_Filter_4_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion4_out1_re = Discrete_FIR_Filter_4_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_4_out1_re[6]});
  assign Data_Type_Conversion4_out1_im = Discrete_FIR_Filter_4_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_4_out1_im[6]});
  assign Out4_re = Data_Type_Conversion4_out1_re;

  assign Out4_im = Data_Type_Conversion4_out1_im;

  Discrete_FIR_Filter_5 u_Discrete_FIR_Filter_5 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_5_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_5_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_5_out_re(Discrete_FIR_Filter_5_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_5_out_im(Discrete_FIR_Filter_5_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion5_out1_re = Discrete_FIR_Filter_5_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_5_out1_re[6]});
  assign Data_Type_Conversion5_out1_im = Discrete_FIR_Filter_5_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_5_out1_im[6]});
  assign Out5_re = Data_Type_Conversion5_out1_re;

  assign Out5_im = Data_Type_Conversion5_out1_im;

  Discrete_FIR_Filter_6 u_Discrete_FIR_Filter_6 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_6_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_6_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_6_out_re(Discrete_FIR_Filter_6_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_6_out_im(Discrete_FIR_Filter_6_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion6_out1_re = Discrete_FIR_Filter_6_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_6_out1_re[6]});
  assign Data_Type_Conversion6_out1_im = Discrete_FIR_Filter_6_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_6_out1_im[6]});
  assign Out6_re = Data_Type_Conversion6_out1_re;

  assign Out6_im = Data_Type_Conversion6_out1_im;

  Discrete_FIR_Filter_7 u_Discrete_FIR_Filter_7 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_7_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_7_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_7_out_re(Discrete_FIR_Filter_7_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_7_out_im(Discrete_FIR_Filter_7_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion7_out1_re = Discrete_FIR_Filter_7_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_7_out1_re[6]});
  assign Data_Type_Conversion7_out1_im = Discrete_FIR_Filter_7_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_7_out1_im[6]});
  assign Out7_re = Data_Type_Conversion7_out1_re;

  assign Out7_im = Data_Type_Conversion7_out1_im;

  Discrete_FIR_Filter_8 u_Discrete_FIR_Filter_8 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(clk_enable),
                                                 .Discrete_FIR_Filter_8_in_re(In1_re),  // sfix16_En15
                                                 .Discrete_FIR_Filter_8_in_im(In1_im),  // sfix16_En15
                                                 .Discrete_FIR_Filter_8_out_re(Discrete_FIR_Filter_8_out1_re),  // sfix16_En5
                                                 .Discrete_FIR_Filter_8_out_im(Discrete_FIR_Filter_8_out1_im)  // sfix16_En5
                                                 );
  assign Data_Type_Conversion8_out1_re = Discrete_FIR_Filter_8_out1_re[15:7] + $signed({1'b0, Discrete_FIR_Filter_8_out1_re[6]});
  assign Data_Type_Conversion8_out1_im = Discrete_FIR_Filter_8_out1_im[15:7] + $signed({1'b0, Discrete_FIR_Filter_8_out1_im[6]});
  assign Out8_re = Data_Type_Conversion8_out1_re;

  assign Out8_im = Data_Type_Conversion8_out1_im;

  assign ce_out = clk_enable;

endmodule  // FIR_Filter_M

