// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_ppfir\pp_fir_tc.v
// Created: 2024-12-31 13:34:34
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_fir_tc
// Source Path: pp_fir_tc
// Hierarchy Level: 1
// 
// Master clock enable input: en
// 
// enb         : identical to en
// enb_1_1_1   : identical to en
// enb_1_8_0   : 8x slower than clk with last phase
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_fir_tc
          (clk,
           rst_n,
           en,
           enb,
           enb_1_1_1,
           enb_1_8_0);


  input   clk;
  input   rst_n;
  input   en;
  output  enb;
  output  enb_1_1_1;
  output  enb_1_8_0;


  reg [2:0] count8;  // ufix3
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_8_0_1;


  assign enb = en;

  assign enb_1_1_1 = en;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 7
  always @(posedge clk or negedge rst_n)
    begin : counter_8_process
      if (rst_n == 1'b0) begin
        count8 <= 3'b001;
      end
      else begin
        if (en) begin
          count8 <= count8 + 3'b001;
        end
      end
    end



  assign comp_0_tmp = count8 == 3'b111;



  assign phase_0_tmp = comp_0_tmp & en;



  always @(posedge clk or negedge rst_n)
    begin : phase_delay_process
      if (rst_n == 1'b0) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (en) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end



  assign enb_1_8_0_1 = phase_0 & en;



  assign enb_1_8_0 = enb_1_8_0_1;

endmodule  // pp_fir_tc

