// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_ppfir_blocked\pp_fir_2.v
// Created: 2025-01-05 11:40:29
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_fir_2
// Source Path: scpa_ppfir_blocked/pp_fir_blocked/pp_fir_u_2/pp_fir_2
// Hierarchy Level: 2
// Model version: 1.32
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_fir_2
          (clk,
           rst_n,
           enb_1_8_0,
           pp_fir_2_in_re,
           pp_fir_2_in_im,
           pp_fir_2_out_re,
           pp_fir_2_out_im);


  input   clk;
  input   rst_n;
  input   enb_1_8_0;
  input   signed [15:0] pp_fir_2_in_re;  // sfix16_En15
  input   signed [15:0] pp_fir_2_in_im;  // sfix16_En15
  output  signed [15:0] pp_fir_2_out_re;  // sfix16_En4
  output  signed [15:0] pp_fir_2_out_im;  // sfix16_En4


  reg signed [15:0] Delay_Pipeline_reg_re [0:31];  // sfix16_En15 [32]
  reg signed [15:0] Delay_Pipeline_reg_im [0:31];  // sfix16_En15 [32]
  reg signed [15:0] Delay_Pipeline_reg_next_re [0:31];  // sfix16_En15 [32]
  reg signed [15:0] Delay_Pipeline_reg_next_im [0:31];  // sfix16_En15 [32]
  reg signed [15:0] delay_pipeline_re [0:31];  // sfix16_En15 [32]
  reg signed [15:0] delay_pipeline_im [0:31];  // sfix16_En15 [32]
  wire signed [15:0] delay_pipeline_31_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_31_im;  // sfix16_En15
  wire signed [31:0] product33_re;  // sfix32_En20
  wire signed [31:0] product33_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_30_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_30_im;  // sfix16_En15
  wire signed [31:0] product32_re;  // sfix32_En20
  wire signed [31:0] product32_im;  // sfix32_En20
  wire signed [31:0] sum1_1_re;  // sfix32_En20
  wire signed [31:0] sum1_1_im;  // sfix32_En20
  reg signed [31:0] sum1_1_re_1;  // sfix32_En20
  reg signed [31:0] sum1_1_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_29_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_29_im;  // sfix16_En15
  wire signed [15:0] coeff31;  // sfix16_En5
  wire signed [31:0] product31_re;  // sfix32_En20
  wire signed [31:0] product31_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_28_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_28_im;  // sfix16_En15
  wire signed [15:0] coeff30;  // sfix16_En5
  wire signed [31:0] product30_re;  // sfix32_En20
  wire signed [31:0] product30_im;  // sfix32_En20
  wire signed [31:0] sum1_2_re;  // sfix32_En20
  wire signed [31:0] sum1_2_im;  // sfix32_En20
  reg signed [31:0] sum1_2_re_1;  // sfix32_En20
  reg signed [31:0] sum1_2_im_1;  // sfix32_En20
  wire signed [31:0] sum2_1_re;  // sfix32_En20
  wire signed [31:0] sum2_1_im;  // sfix32_En20
  reg signed [31:0] sum2_1_re_1;  // sfix32_En20
  reg signed [31:0] sum2_1_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_27_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_27_im;  // sfix16_En15
  wire signed [15:0] coeff29;  // sfix16_En5
  wire signed [31:0] product29_re;  // sfix32_En20
  wire signed [31:0] product29_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_26_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_26_im;  // sfix16_En15
  wire signed [15:0] coeff28;  // sfix16_En5
  wire signed [31:0] product28_re;  // sfix32_En20
  wire signed [31:0] product28_im;  // sfix32_En20
  wire signed [31:0] sum1_3_re;  // sfix32_En20
  wire signed [31:0] sum1_3_im;  // sfix32_En20
  reg signed [31:0] sum1_3_re_1;  // sfix32_En20
  reg signed [31:0] sum1_3_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_25_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_25_im;  // sfix16_En15
  wire signed [15:0] coeff27;  // sfix16_En5
  wire signed [31:0] product27_re;  // sfix32_En20
  wire signed [31:0] product27_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_24_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_24_im;  // sfix16_En15
  wire signed [15:0] coeff26;  // sfix16_En5
  wire signed [31:0] product26_re;  // sfix32_En20
  wire signed [31:0] product26_im;  // sfix32_En20
  wire signed [31:0] sum1_4_re;  // sfix32_En20
  wire signed [31:0] sum1_4_im;  // sfix32_En20
  reg signed [31:0] sum1_4_re_1;  // sfix32_En20
  reg signed [31:0] sum1_4_im_1;  // sfix32_En20
  wire signed [31:0] sum2_2_re;  // sfix32_En20
  wire signed [31:0] sum2_2_im;  // sfix32_En20
  reg signed [31:0] sum2_2_re_1;  // sfix32_En20
  reg signed [31:0] sum2_2_im_1;  // sfix32_En20
  wire signed [31:0] sum3_1_re;  // sfix32_En20
  wire signed [31:0] sum3_1_im;  // sfix32_En20
  reg signed [31:0] sum3_1_re_1;  // sfix32_En20
  reg signed [31:0] sum3_1_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_23_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_23_im;  // sfix16_En15
  wire signed [15:0] coeff25;  // sfix16_En5
  wire signed [31:0] product25_re;  // sfix32_En20
  wire signed [31:0] product25_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_22_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_22_im;  // sfix16_En15
  wire signed [15:0] coeff24;  // sfix16_En5
  wire signed [31:0] product24_re;  // sfix32_En20
  wire signed [31:0] product24_im;  // sfix32_En20
  wire signed [31:0] sum1_5_re;  // sfix32_En20
  wire signed [31:0] sum1_5_im;  // sfix32_En20
  reg signed [31:0] sum1_5_re_1;  // sfix32_En20
  reg signed [31:0] sum1_5_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_21_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_21_im;  // sfix16_En15
  wire signed [15:0] coeff23;  // sfix16_En5
  wire signed [31:0] product23_re;  // sfix32_En20
  wire signed [31:0] product23_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_20_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_20_im;  // sfix16_En15
  wire signed [15:0] coeff22;  // sfix16_En5
  wire signed [31:0] product22_re;  // sfix32_En20
  wire signed [31:0] product22_im;  // sfix32_En20
  wire signed [31:0] sum1_6_re;  // sfix32_En20
  wire signed [31:0] sum1_6_im;  // sfix32_En20
  reg signed [31:0] sum1_6_re_1;  // sfix32_En20
  reg signed [31:0] sum1_6_im_1;  // sfix32_En20
  wire signed [31:0] sum2_3_re;  // sfix32_En20
  wire signed [31:0] sum2_3_im;  // sfix32_En20
  reg signed [31:0] sum2_3_re_1;  // sfix32_En20
  reg signed [31:0] sum2_3_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_19_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_19_im;  // sfix16_En15
  wire signed [15:0] coeff21;  // sfix16_En5
  wire signed [31:0] product21_re;  // sfix32_En20
  wire signed [31:0] product21_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_18_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_18_im;  // sfix16_En15
  wire signed [15:0] coeff20;  // sfix16_En5
  wire signed [31:0] product20_re;  // sfix32_En20
  wire signed [31:0] product20_im;  // sfix32_En20
  wire signed [31:0] sum1_7_re;  // sfix32_En20
  wire signed [31:0] sum1_7_im;  // sfix32_En20
  reg signed [31:0] sum1_7_re_1;  // sfix32_En20
  reg signed [31:0] sum1_7_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_17_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_17_im;  // sfix16_En15
  wire signed [15:0] coeff19;  // sfix16_En5
  wire signed [31:0] product19_re;  // sfix32_En20
  wire signed [31:0] product19_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_16_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_16_im;  // sfix16_En15
  wire signed [15:0] coeff18;  // sfix16_En5
  wire signed [31:0] product18_re;  // sfix32_En20
  wire signed [31:0] product18_im;  // sfix32_En20
  wire signed [31:0] sum1_8_re;  // sfix32_En20
  wire signed [31:0] sum1_8_im;  // sfix32_En20
  reg signed [31:0] sum1_8_re_1;  // sfix32_En20
  reg signed [31:0] sum1_8_im_1;  // sfix32_En20
  wire signed [31:0] sum2_4_re;  // sfix32_En20
  wire signed [31:0] sum2_4_im;  // sfix32_En20
  reg signed [31:0] sum2_4_re_1;  // sfix32_En20
  reg signed [31:0] sum2_4_im_1;  // sfix32_En20
  wire signed [31:0] sum3_2_re;  // sfix32_En20
  wire signed [31:0] sum3_2_im;  // sfix32_En20
  reg signed [31:0] sum3_2_re_1;  // sfix32_En20
  reg signed [31:0] sum3_2_im_1;  // sfix32_En20
  wire signed [31:0] sum4_1_re;  // sfix32_En20
  wire signed [31:0] sum4_1_im;  // sfix32_En20
  reg signed [31:0] sum4_1_re_1;  // sfix32_En20
  reg signed [31:0] sum4_1_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_15_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_15_im;  // sfix16_En15
  wire signed [15:0] coeff17;  // sfix16_En5
  wire signed [31:0] product17_re;  // sfix32_En20
  wire signed [31:0] product17_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_14_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_14_im;  // sfix16_En15
  wire signed [15:0] coeff16;  // sfix16_En5
  wire signed [31:0] product16_re;  // sfix32_En20
  wire signed [31:0] product16_im;  // sfix32_En20
  wire signed [31:0] sum1_9_re;  // sfix32_En20
  wire signed [31:0] sum1_9_im;  // sfix32_En20
  reg signed [31:0] sum1_9_re_1;  // sfix32_En20
  reg signed [31:0] sum1_9_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_13_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_13_im;  // sfix16_En15
  wire signed [15:0] coeff15;  // sfix16_En5
  wire signed [31:0] product15_re;  // sfix32_En20
  wire signed [31:0] product15_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_12_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_12_im;  // sfix16_En15
  wire signed [15:0] coeff14;  // sfix16_En5
  wire signed [31:0] product14_re;  // sfix32_En20
  wire signed [31:0] product14_im;  // sfix32_En20
  wire signed [31:0] sum1_10_re;  // sfix32_En20
  wire signed [31:0] sum1_10_im;  // sfix32_En20
  reg signed [31:0] sum1_10_re_1;  // sfix32_En20
  reg signed [31:0] sum1_10_im_1;  // sfix32_En20
  wire signed [31:0] sum2_5_re;  // sfix32_En20
  wire signed [31:0] sum2_5_im;  // sfix32_En20
  reg signed [31:0] sum2_5_re_1;  // sfix32_En20
  reg signed [31:0] sum2_5_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_11_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_11_im;  // sfix16_En15
  wire signed [15:0] coeff13;  // sfix16_En5
  wire signed [31:0] product13_re;  // sfix32_En20
  wire signed [31:0] product13_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_10_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_10_im;  // sfix16_En15
  wire signed [15:0] coeff12;  // sfix16_En5
  wire signed [31:0] product12_re;  // sfix32_En20
  wire signed [31:0] product12_im;  // sfix32_En20
  wire signed [31:0] sum1_11_re;  // sfix32_En20
  wire signed [31:0] sum1_11_im;  // sfix32_En20
  reg signed [31:0] sum1_11_re_1;  // sfix32_En20
  reg signed [31:0] sum1_11_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_9_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_9_im;  // sfix16_En15
  wire signed [15:0] coeff11;  // sfix16_En5
  wire signed [31:0] product11_re;  // sfix32_En20
  wire signed [31:0] product11_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_8_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_8_im;  // sfix16_En15
  wire signed [15:0] coeff10;  // sfix16_En5
  wire signed [31:0] product10_re;  // sfix32_En20
  wire signed [31:0] product10_im;  // sfix32_En20
  wire signed [31:0] sum1_12_re;  // sfix32_En20
  wire signed [31:0] sum1_12_im;  // sfix32_En20
  reg signed [31:0] sum1_12_re_1;  // sfix32_En20
  reg signed [31:0] sum1_12_im_1;  // sfix32_En20
  wire signed [31:0] sum2_6_re;  // sfix32_En20
  wire signed [31:0] sum2_6_im;  // sfix32_En20
  reg signed [31:0] sum2_6_re_1;  // sfix32_En20
  reg signed [31:0] sum2_6_im_1;  // sfix32_En20
  wire signed [31:0] sum3_3_re;  // sfix32_En20
  wire signed [31:0] sum3_3_im;  // sfix32_En20
  reg signed [31:0] sum3_3_re_1;  // sfix32_En20
  reg signed [31:0] sum3_3_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_7_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_7_im;  // sfix16_En15
  wire signed [15:0] coeff9;  // sfix16_En5
  wire signed [31:0] product9_re;  // sfix32_En20
  wire signed [31:0] product9_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_6_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_6_im;  // sfix16_En15
  wire signed [15:0] coeff8;  // sfix16_En5
  wire signed [31:0] product8_re;  // sfix32_En20
  wire signed [31:0] product8_im;  // sfix32_En20
  wire signed [31:0] sum1_13_re;  // sfix32_En20
  wire signed [31:0] sum1_13_im;  // sfix32_En20
  reg signed [31:0] sum1_13_re_1;  // sfix32_En20
  reg signed [31:0] sum1_13_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_5_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_5_im;  // sfix16_En15
  wire signed [15:0] coeff7;  // sfix16_En5
  wire signed [31:0] product7_re;  // sfix32_En20
  wire signed [31:0] product7_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_4_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_4_im;  // sfix16_En15
  wire signed [15:0] coeff6;  // sfix16_En5
  wire signed [31:0] product6_re;  // sfix32_En20
  wire signed [31:0] product6_im;  // sfix32_En20
  wire signed [31:0] sum1_14_re;  // sfix32_En20
  wire signed [31:0] sum1_14_im;  // sfix32_En20
  reg signed [31:0] sum1_14_re_1;  // sfix32_En20
  reg signed [31:0] sum1_14_im_1;  // sfix32_En20
  wire signed [31:0] sum2_7_re;  // sfix32_En20
  wire signed [31:0] sum2_7_im;  // sfix32_En20
  reg signed [31:0] sum2_7_re_1;  // sfix32_En20
  reg signed [31:0] sum2_7_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_3_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_3_im;  // sfix16_En15
  wire signed [15:0] coeff5;  // sfix16_En5
  wire signed [31:0] product5_re;  // sfix32_En20
  wire signed [31:0] product5_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_2_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_2_im;  // sfix16_En15
  wire signed [15:0] coeff4;  // sfix16_En5
  wire signed [31:0] product4_re;  // sfix32_En20
  wire signed [31:0] product4_im;  // sfix32_En20
  wire signed [31:0] sum1_15_re;  // sfix32_En20
  wire signed [31:0] sum1_15_im;  // sfix32_En20
  reg signed [31:0] sum1_15_re_1;  // sfix32_En20
  reg signed [31:0] sum1_15_im_1;  // sfix32_En20
  wire signed [15:0] delay_pipeline_1_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_1_im;  // sfix16_En15
  wire signed [15:0] coeff3;  // sfix16_En5
  wire signed [31:0] product3_re;  // sfix32_En20
  wire signed [31:0] product3_im;  // sfix32_En20
  wire signed [15:0] delay_pipeline_0_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_0_im;  // sfix16_En15
  wire signed [31:0] product2_re;  // sfix32_En20
  wire signed [31:0] product2_im;  // sfix32_En20
  wire signed [31:0] sum1_16_re;  // sfix32_En20
  wire signed [31:0] sum1_16_im;  // sfix32_En20
  reg signed [31:0] sum1_16_re_1;  // sfix32_En20
  reg signed [31:0] sum1_16_im_1;  // sfix32_En20
  wire signed [31:0] sum2_8_re;  // sfix32_En20
  wire signed [31:0] sum2_8_im;  // sfix32_En20
  reg signed [31:0] sum2_8_re_1;  // sfix32_En20
  reg signed [31:0] sum2_8_im_1;  // sfix32_En20
  wire signed [31:0] sum3_4_re;  // sfix32_En20
  wire signed [31:0] sum3_4_im;  // sfix32_En20
  reg signed [31:0] sum3_4_re_1;  // sfix32_En20
  reg signed [31:0] sum3_4_im_1;  // sfix32_En20
  wire signed [31:0] sum4_2_re;  // sfix32_En20
  wire signed [31:0] sum4_2_im;  // sfix32_En20
  reg signed [31:0] sum4_2_re_1;  // sfix32_En20
  reg signed [31:0] sum4_2_im_1;  // sfix32_En20
  wire signed [31:0] sum5_1_re;  // sfix32_En20
  wire signed [31:0] sum5_1_im;  // sfix32_En20
  reg signed [31:0] sum5_1_re_1;  // sfix32_En20
  reg signed [31:0] sum5_1_im_1;  // sfix32_En20
  wire signed [31:0] product1_re;  // sfix32_En20
  wire signed [31:0] product1_im;  // sfix32_En20
  reg signed [31:0] product1_re_1;  // sfix32_En20
  reg signed [31:0] product1_im_1;  // sfix32_En20
  reg signed [31:0] product1_re_2;  // sfix32_En20
  reg signed [31:0] product1_im_2;  // sfix32_En20
  reg signed [31:0] product1_re_3;  // sfix32_En20
  reg signed [31:0] product1_im_3;  // sfix32_En20
  reg signed [31:0] product1_re_4;  // sfix32_En20
  reg signed [31:0] product1_im_4;  // sfix32_En20
  reg signed [31:0] product1_re_5;  // sfix32_En20
  reg signed [31:0] product1_im_5;  // sfix32_En20
  wire signed [31:0] sum6_1_re;  // sfix32_En20
  wire signed [31:0] sum6_1_im;  // sfix32_En20
  reg signed [31:0] sum6_1_re_1;  // sfix32_En20
  reg signed [31:0] sum6_1_im_1;  // sfix32_En20
  wire signed [15:0] output_typeconvert_re;  // sfix16_En4
  wire signed [15:0] output_typeconvert_im;  // sfix16_En4
  reg signed [31:0] Delay_Pipeline_t_0_0;  // int32
  reg signed [31:0] Delay_Pipeline_t_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_0_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_1_0;  // int32


  always @(posedge clk or negedge rst_n)
    begin : Delay_Pipeline_process
      if (rst_n == 1'b0) begin
        for(Delay_Pipeline_t_1_0 = 32'sd0; Delay_Pipeline_t_1_0 <= 32'sd31; Delay_Pipeline_t_1_0 = 
          Delay_Pipeline_t_1_0 + 32'sd1) begin
          Delay_Pipeline_reg_re[Delay_Pipeline_t_1_0] <= 16'sb0000000000000000;
          Delay_Pipeline_reg_im[Delay_Pipeline_t_1_0] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_8_0) begin
          for(Delay_Pipeline_t_0_1 = 32'sd0; Delay_Pipeline_t_0_1 <= 32'sd31; Delay_Pipeline_t_0_1 = 
            Delay_Pipeline_t_0_1 + 32'sd1) begin
            Delay_Pipeline_reg_re[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_re[Delay_Pipeline_t_0_1];
            Delay_Pipeline_reg_im[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_im[Delay_Pipeline_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(Delay_Pipeline_t_0_0 = 32'sd0; Delay_Pipeline_t_0_0 <= 32'sd31; Delay_Pipeline_t_0_0 = 
      Delay_Pipeline_t_0_0 + 32'sd1) begin
      delay_pipeline_re[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_re[Delay_Pipeline_t_0_0];
      delay_pipeline_im[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_im[Delay_Pipeline_t_0_0];
    end

    Delay_Pipeline_reg_next_re[0] = pp_fir_2_in_re;
    Delay_Pipeline_reg_next_im[0] = pp_fir_2_in_im;

    for(Delay_Pipeline_t_1 = 32'sd0; Delay_Pipeline_t_1 <= 32'sd30; Delay_Pipeline_t_1 = Delay_Pipeline_t_1 + 
      32'sd1) begin
      Delay_Pipeline_reg_next_re[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_re[Delay_Pipeline_t_1];
      Delay_Pipeline_reg_next_im[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_im[Delay_Pipeline_t_1];
    end

  end



  assign delay_pipeline_31_re = delay_pipeline_re[31];

  assign delay_pipeline_31_im = delay_pipeline_im[31];

  // coeff33
  assign product33_re = 32'sb00000000000000000000000000000000;
  assign product33_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_30_re = delay_pipeline_re[30];

  assign delay_pipeline_30_im = delay_pipeline_im[30];

  // coeff32
  assign product32_re = {{16{delay_pipeline_30_re[15]}}, delay_pipeline_30_re};
  assign product32_im = {{16{delay_pipeline_30_im[15]}}, delay_pipeline_30_im};



  assign sum1_1_re = product33_re + product32_re;
  assign sum1_1_im = product33_im + product32_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        sum1_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_1_re_1 <= sum1_1_re;
          sum1_1_im_1 <= sum1_1_im;
        end
      end
    end



  assign delay_pipeline_29_re = delay_pipeline_re[29];

  assign delay_pipeline_29_im = delay_pipeline_im[29];

  assign coeff31 = 16'sb1111111111100011;



  assign product31_re = delay_pipeline_29_re * coeff31;
  assign product31_im = delay_pipeline_29_im * coeff31;



  assign delay_pipeline_28_re = delay_pipeline_re[28];

  assign delay_pipeline_28_im = delay_pipeline_im[28];

  assign coeff30 = 16'sb1111111110001110;



  assign product30_re = delay_pipeline_28_re * coeff30;
  assign product30_im = delay_pipeline_28_im * coeff30;



  assign sum1_2_re = product31_re + product30_re;
  assign sum1_2_im = product31_im + product30_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_1_process
      if (rst_n == 1'b0) begin
        sum1_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_2_re_1 <= sum1_2_re;
          sum1_2_im_1 <= sum1_2_im;
        end
      end
    end



  assign sum2_1_re = sum1_1_re_1 + sum1_2_re_1;
  assign sum2_1_im = sum1_1_im_1 + sum1_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_2_process
      if (rst_n == 1'b0) begin
        sum2_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_1_re_1 <= sum2_1_re;
          sum2_1_im_1 <= sum2_1_im;
        end
      end
    end



  assign delay_pipeline_27_re = delay_pipeline_re[27];

  assign delay_pipeline_27_im = delay_pipeline_im[27];

  assign coeff29 = 16'sb1111111111110111;



  assign product29_re = delay_pipeline_27_re * coeff29;
  assign product29_im = delay_pipeline_27_im * coeff29;



  assign delay_pipeline_26_re = delay_pipeline_re[26];

  assign delay_pipeline_26_im = delay_pipeline_im[26];

  assign coeff28 = 16'sb0000000011010010;



  assign product28_re = delay_pipeline_26_re * coeff28;
  assign product28_im = delay_pipeline_26_im * coeff28;



  assign sum1_3_re = product29_re + product28_re;
  assign sum1_3_im = product29_im + product28_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_3_process
      if (rst_n == 1'b0) begin
        sum1_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_3_re_1 <= sum1_3_re;
          sum1_3_im_1 <= sum1_3_im;
        end
      end
    end



  assign delay_pipeline_25_re = delay_pipeline_re[25];

  assign delay_pipeline_25_im = delay_pipeline_im[25];

  assign coeff27 = 16'sb1111111101111100;



  assign product27_re = delay_pipeline_25_re * coeff27;
  assign product27_im = delay_pipeline_25_im * coeff27;



  assign delay_pipeline_24_re = delay_pipeline_re[24];

  assign delay_pipeline_24_im = delay_pipeline_im[24];

  assign coeff26 = 16'sb1111111010100101;



  assign product26_re = delay_pipeline_24_re * coeff26;
  assign product26_im = delay_pipeline_24_im * coeff26;



  assign sum1_4_re = product27_re + product26_re;
  assign sum1_4_im = product27_im + product26_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_4_process
      if (rst_n == 1'b0) begin
        sum1_4_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_4_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_4_re_1 <= sum1_4_re;
          sum1_4_im_1 <= sum1_4_im;
        end
      end
    end



  assign sum2_2_re = sum1_3_re_1 + sum1_4_re_1;
  assign sum2_2_im = sum1_3_im_1 + sum1_4_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_5_process
      if (rst_n == 1'b0) begin
        sum2_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_2_re_1 <= sum2_2_re;
          sum2_2_im_1 <= sum2_2_im;
        end
      end
    end



  assign sum3_1_re = sum2_1_re_1 + sum2_2_re_1;
  assign sum3_1_im = sum2_1_im_1 + sum2_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_6_process
      if (rst_n == 1'b0) begin
        sum3_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_1_re_1 <= sum3_1_re;
          sum3_1_im_1 <= sum3_1_im;
        end
      end
    end



  assign delay_pipeline_23_re = delay_pipeline_re[23];

  assign delay_pipeline_23_im = delay_pipeline_im[23];

  assign coeff25 = 16'sb0000001000000111;



  assign product25_re = delay_pipeline_23_re * coeff25;
  assign product25_im = delay_pipeline_23_im * coeff25;



  assign delay_pipeline_22_re = delay_pipeline_re[22];

  assign delay_pipeline_22_im = delay_pipeline_im[22];

  assign coeff24 = 16'sb0000000100010001;



  assign product24_re = delay_pipeline_22_re * coeff24;
  assign product24_im = delay_pipeline_22_im * coeff24;



  assign sum1_5_re = product25_re + product24_re;
  assign sum1_5_im = product25_im + product24_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_7_process
      if (rst_n == 1'b0) begin
        sum1_5_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_5_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_5_re_1 <= sum1_5_re;
          sum1_5_im_1 <= sum1_5_im;
        end
      end
    end



  assign delay_pipeline_21_re = delay_pipeline_re[21];

  assign delay_pipeline_21_im = delay_pipeline_im[21];

  assign coeff23 = 16'sb1111101101011101;



  assign product23_re = delay_pipeline_21_re * coeff23;
  assign product23_im = delay_pipeline_21_im * coeff23;



  assign delay_pipeline_20_re = delay_pipeline_re[20];

  assign delay_pipeline_20_im = delay_pipeline_im[20];

  assign coeff22 = 16'sb0000000110110010;



  assign product22_re = delay_pipeline_20_re * coeff22;
  assign product22_im = delay_pipeline_20_im * coeff22;



  assign sum1_6_re = product23_re + product22_re;
  assign sum1_6_im = product23_im + product22_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_8_process
      if (rst_n == 1'b0) begin
        sum1_6_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_6_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_6_re_1 <= sum1_6_re;
          sum1_6_im_1 <= sum1_6_im;
        end
      end
    end



  assign sum2_3_re = sum1_5_re_1 + sum1_6_re_1;
  assign sum2_3_im = sum1_5_im_1 + sum1_6_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_9_process
      if (rst_n == 1'b0) begin
        sum2_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_3_re_1 <= sum2_3_re;
          sum2_3_im_1 <= sum2_3_im;
        end
      end
    end



  assign delay_pipeline_19_re = delay_pipeline_re[19];

  assign delay_pipeline_19_im = delay_pipeline_im[19];

  assign coeff21 = 16'sb0000011101110001;



  assign product21_re = delay_pipeline_19_re * coeff21;
  assign product21_im = delay_pipeline_19_im * coeff21;



  assign delay_pipeline_18_re = delay_pipeline_re[18];

  assign delay_pipeline_18_im = delay_pipeline_im[18];

  assign coeff20 = 16'sb1111011000010010;



  assign product20_re = delay_pipeline_18_re * coeff20;
  assign product20_im = delay_pipeline_18_im * coeff20;



  assign sum1_7_re = product21_re + product20_re;
  assign sum1_7_im = product21_im + product20_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_10_process
      if (rst_n == 1'b0) begin
        sum1_7_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_7_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_7_re_1 <= sum1_7_re;
          sum1_7_im_1 <= sum1_7_im;
        end
      end
    end



  assign delay_pipeline_17_re = delay_pipeline_re[17];

  assign delay_pipeline_17_im = delay_pipeline_im[17];

  assign coeff19 = 16'sb1111100000101011;



  assign product19_re = delay_pipeline_17_re * coeff19;
  assign product19_im = delay_pipeline_17_im * coeff19;



  assign delay_pipeline_16_re = delay_pipeline_re[16];

  assign delay_pipeline_16_im = delay_pipeline_im[16];

  assign coeff18 = 16'sb0010111000001000;



  assign product18_re = delay_pipeline_16_re * coeff18;
  assign product18_im = delay_pipeline_16_im * coeff18;



  assign sum1_8_re = product19_re + product18_re;
  assign sum1_8_im = product19_im + product18_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_11_process
      if (rst_n == 1'b0) begin
        sum1_8_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_8_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_8_re_1 <= sum1_8_re;
          sum1_8_im_1 <= sum1_8_im;
        end
      end
    end



  assign sum2_4_re = sum1_7_re_1 + sum1_8_re_1;
  assign sum2_4_im = sum1_7_im_1 + sum1_8_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_12_process
      if (rst_n == 1'b0) begin
        sum2_4_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_4_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_4_re_1 <= sum2_4_re;
          sum2_4_im_1 <= sum2_4_im;
        end
      end
    end



  assign sum3_2_re = sum2_3_re_1 + sum2_4_re_1;
  assign sum3_2_im = sum2_3_im_1 + sum2_4_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_13_process
      if (rst_n == 1'b0) begin
        sum3_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_2_re_1 <= sum3_2_re;
          sum3_2_im_1 <= sum3_2_im;
        end
      end
    end



  assign sum4_1_re = sum3_1_re_1 + sum3_2_re_1;
  assign sum4_1_im = sum3_1_im_1 + sum3_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_14_process
      if (rst_n == 1'b0) begin
        sum4_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum4_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum4_1_re_1 <= sum4_1_re;
          sum4_1_im_1 <= sum4_1_im;
        end
      end
    end



  assign delay_pipeline_15_re = delay_pipeline_re[15];

  assign delay_pipeline_15_im = delay_pipeline_im[15];

  assign coeff17 = 16'sb0100101111101100;



  assign product17_re = delay_pipeline_15_re * coeff17;
  assign product17_im = delay_pipeline_15_im * coeff17;



  assign delay_pipeline_14_re = delay_pipeline_re[14];

  assign delay_pipeline_14_im = delay_pipeline_im[14];

  assign coeff16 = 16'sb0001111010000111;



  assign product16_re = delay_pipeline_14_re * coeff16;
  assign product16_im = delay_pipeline_14_im * coeff16;



  assign sum1_9_re = product17_re + product16_re;
  assign sum1_9_im = product17_im + product16_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_15_process
      if (rst_n == 1'b0) begin
        sum1_9_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_9_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_9_re_1 <= sum1_9_re;
          sum1_9_im_1 <= sum1_9_im;
        end
      end
    end



  assign delay_pipeline_13_re = delay_pipeline_re[13];

  assign delay_pipeline_13_im = delay_pipeline_im[13];

  assign coeff15 = 16'sb1111001001000011;



  assign product15_re = delay_pipeline_13_re * coeff15;
  assign product15_im = delay_pipeline_13_im * coeff15;



  assign delay_pipeline_12_re = delay_pipeline_re[12];

  assign delay_pipeline_12_im = delay_pipeline_im[12];

  assign coeff14 = 16'sb1111101101011100;



  assign product14_re = delay_pipeline_12_re * coeff14;
  assign product14_im = delay_pipeline_12_im * coeff14;



  assign sum1_10_re = product15_re + product14_re;
  assign sum1_10_im = product15_im + product14_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_16_process
      if (rst_n == 1'b0) begin
        sum1_10_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_10_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_10_re_1 <= sum1_10_re;
          sum1_10_im_1 <= sum1_10_im;
        end
      end
    end



  assign sum2_5_re = sum1_9_re_1 + sum1_10_re_1;
  assign sum2_5_im = sum1_9_im_1 + sum1_10_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_17_process
      if (rst_n == 1'b0) begin
        sum2_5_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_5_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_5_re_1 <= sum2_5_re;
          sum2_5_im_1 <= sum2_5_im;
        end
      end
    end



  assign delay_pipeline_11_re = delay_pipeline_re[11];

  assign delay_pipeline_11_im = delay_pipeline_im[11];

  assign coeff13 = 16'sb0000100000010101;



  assign product13_re = delay_pipeline_11_re * coeff13;
  assign product13_im = delay_pipeline_11_im * coeff13;



  assign delay_pipeline_10_re = delay_pipeline_re[10];

  assign delay_pipeline_10_im = delay_pipeline_im[10];

  assign coeff12 = 16'sb1111111011011001;



  assign product12_re = delay_pipeline_10_re * coeff12;
  assign product12_im = delay_pipeline_10_im * coeff12;



  assign sum1_11_re = product13_re + product12_re;
  assign sum1_11_im = product13_im + product12_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_18_process
      if (rst_n == 1'b0) begin
        sum1_11_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_11_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_11_re_1 <= sum1_11_re;
          sum1_11_im_1 <= sum1_11_im;
        end
      end
    end



  assign delay_pipeline_9_re = delay_pipeline_re[9];

  assign delay_pipeline_9_im = delay_pipeline_im[9];

  assign coeff11 = 16'sb1111110000111001;



  assign product11_re = delay_pipeline_9_re * coeff11;
  assign product11_im = delay_pipeline_9_im * coeff11;



  assign delay_pipeline_8_re = delay_pipeline_re[8];

  assign delay_pipeline_8_im = delay_pipeline_im[8];

  assign coeff10 = 16'sb0000001000110111;



  assign product10_re = delay_pipeline_8_re * coeff10;
  assign product10_im = delay_pipeline_8_im * coeff10;



  assign sum1_12_re = product11_re + product10_re;
  assign sum1_12_im = product11_im + product10_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_19_process
      if (rst_n == 1'b0) begin
        sum1_12_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_12_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_12_re_1 <= sum1_12_re;
          sum1_12_im_1 <= sum1_12_im;
        end
      end
    end



  assign sum2_6_re = sum1_11_re_1 + sum1_12_re_1;
  assign sum2_6_im = sum1_11_im_1 + sum1_12_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_20_process
      if (rst_n == 1'b0) begin
        sum2_6_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_6_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_6_re_1 <= sum2_6_re;
          sum2_6_im_1 <= sum2_6_im;
        end
      end
    end



  assign sum3_3_re = sum2_5_re_1 + sum2_6_re_1;
  assign sum3_3_im = sum2_5_im_1 + sum2_6_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_21_process
      if (rst_n == 1'b0) begin
        sum3_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_3_re_1 <= sum3_3_re;
          sum3_3_im_1 <= sum3_3_im;
        end
      end
    end



  assign delay_pipeline_7_re = delay_pipeline_re[7];

  assign delay_pipeline_7_im = delay_pipeline_im[7];

  assign coeff9 = 16'sb0000000100011001;



  assign product9_re = delay_pipeline_7_re * coeff9;
  assign product9_im = delay_pipeline_7_im * coeff9;



  assign delay_pipeline_6_re = delay_pipeline_re[6];

  assign delay_pipeline_6_im = delay_pipeline_im[6];

  assign coeff8 = 16'sb1111111001101110;



  assign product8_re = delay_pipeline_6_re * coeff8;
  assign product8_im = delay_pipeline_6_im * coeff8;



  assign sum1_13_re = product9_re + product8_re;
  assign sum1_13_im = product9_im + product8_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_22_process
      if (rst_n == 1'b0) begin
        sum1_13_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_13_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_13_re_1 <= sum1_13_re;
          sum1_13_im_1 <= sum1_13_im;
        end
      end
    end



  assign delay_pipeline_5_re = delay_pipeline_re[5];

  assign delay_pipeline_5_im = delay_pipeline_im[5];

  assign coeff7 = 16'sb0000000000000110;



  assign product7_re = delay_pipeline_5_re * coeff7;
  assign product7_im = delay_pipeline_5_im * coeff7;



  assign delay_pipeline_4_re = delay_pipeline_re[4];

  assign delay_pipeline_4_im = delay_pipeline_im[4];

  assign coeff6 = 16'sb0000000010111011;



  assign product6_re = delay_pipeline_4_re * coeff6;
  assign product6_im = delay_pipeline_4_im * coeff6;



  assign sum1_14_re = product7_re + product6_re;
  assign sum1_14_im = product7_im + product6_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_23_process
      if (rst_n == 1'b0) begin
        sum1_14_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_14_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_14_re_1 <= sum1_14_re;
          sum1_14_im_1 <= sum1_14_im;
        end
      end
    end



  assign sum2_7_re = sum1_13_re_1 + sum1_14_re_1;
  assign sum2_7_im = sum1_13_im_1 + sum1_14_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_24_process
      if (rst_n == 1'b0) begin
        sum2_7_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_7_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_7_re_1 <= sum2_7_re;
          sum2_7_im_1 <= sum2_7_im;
        end
      end
    end



  assign delay_pipeline_3_re = delay_pipeline_re[3];

  assign delay_pipeline_3_im = delay_pipeline_im[3];

  assign coeff5 = 16'sb1111111110111110;



  assign product5_re = delay_pipeline_3_re * coeff5;
  assign product5_im = delay_pipeline_3_im * coeff5;



  assign delay_pipeline_2_re = delay_pipeline_re[2];

  assign delay_pipeline_2_im = delay_pipeline_im[2];

  assign coeff4 = 16'sb1111111110011111;



  assign product4_re = delay_pipeline_2_re * coeff4;
  assign product4_im = delay_pipeline_2_im * coeff4;



  assign sum1_15_re = product5_re + product4_re;
  assign sum1_15_im = product5_im + product4_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_25_process
      if (rst_n == 1'b0) begin
        sum1_15_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_15_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_15_re_1 <= sum1_15_re;
          sum1_15_im_1 <= sum1_15_im;
        end
      end
    end



  assign delay_pipeline_1_re = delay_pipeline_re[1];

  assign delay_pipeline_1_im = delay_pipeline_im[1];

  assign coeff3 = 16'sb1111111111110011;



  assign product3_re = delay_pipeline_1_re * coeff3;
  assign product3_im = delay_pipeline_1_im * coeff3;



  assign delay_pipeline_0_re = delay_pipeline_re[0];

  assign delay_pipeline_0_im = delay_pipeline_im[0];

  // coeff2
  assign product2_re = 32'sb00000000000000000000000000000000;
  assign product2_im = 32'sb00000000000000000000000000000000;



  assign sum1_16_re = product3_re + product2_re;
  assign sum1_16_im = product3_im + product2_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_26_process
      if (rst_n == 1'b0) begin
        sum1_16_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_16_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_16_re_1 <= sum1_16_re;
          sum1_16_im_1 <= sum1_16_im;
        end
      end
    end



  assign sum2_8_re = sum1_15_re_1 + sum1_16_re_1;
  assign sum2_8_im = sum1_15_im_1 + sum1_16_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_27_process
      if (rst_n == 1'b0) begin
        sum2_8_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_8_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_8_re_1 <= sum2_8_re;
          sum2_8_im_1 <= sum2_8_im;
        end
      end
    end



  assign sum3_4_re = sum2_7_re_1 + sum2_8_re_1;
  assign sum3_4_im = sum2_7_im_1 + sum2_8_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_28_process
      if (rst_n == 1'b0) begin
        sum3_4_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_4_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_4_re_1 <= sum3_4_re;
          sum3_4_im_1 <= sum3_4_im;
        end
      end
    end



  assign sum4_2_re = sum3_3_re_1 + sum3_4_re_1;
  assign sum4_2_im = sum3_3_im_1 + sum3_4_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_29_process
      if (rst_n == 1'b0) begin
        sum4_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum4_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum4_2_re_1 <= sum4_2_re;
          sum4_2_im_1 <= sum4_2_im;
        end
      end
    end



  assign sum5_1_re = sum4_1_re_1 + sum4_2_re_1;
  assign sum5_1_im = sum4_1_im_1 + sum4_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_30_process
      if (rst_n == 1'b0) begin
        sum5_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum5_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum5_1_re_1 <= sum5_1_re;
          sum5_1_im_1 <= sum5_1_im;
        end
      end
    end



  // coeff1
  assign product1_re = 32'sb00000000000000000000000000000000;
  assign product1_im = 32'sb00000000000000000000000000000000;



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        product1_re_1 <= 32'sb00000000000000000000000000000000;
        product1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          product1_re_1 <= product1_re;
          product1_im_1 <= product1_im;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_buff_out_pipe_proc
      if (rst_n == 1'b0) begin
        product1_re_2 <= 32'sb00000000000000000000000000000000;
        product1_im_2 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          product1_re_2 <= product1_re_1;
          product1_im_2 <= product1_im_1;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_buff_out_buff_out1
      if (rst_n == 1'b0) begin
        product1_re_3 <= 32'sb00000000000000000000000000000000;
        product1_im_3 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          product1_re_3 <= product1_re_2;
          product1_im_3 <= product1_im_2;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_buff_out_buff_out3
      if (rst_n == 1'b0) begin
        product1_re_4 <= 32'sb00000000000000000000000000000000;
        product1_im_4 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          product1_re_4 <= product1_re_3;
          product1_im_4 <= product1_im_3;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_buff_out_buff_out5
      if (rst_n == 1'b0) begin
        product1_re_5 <= 32'sb00000000000000000000000000000000;
        product1_im_5 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          product1_re_5 <= product1_re_4;
          product1_im_5 <= product1_im_4;
        end
      end
    end



  assign sum6_1_re = sum5_1_re_1 + product1_re_5;
  assign sum6_1_im = sum5_1_im_1 + product1_im_5;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_31_process
      if (rst_n == 1'b0) begin
        sum6_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum6_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum6_1_re_1 <= sum6_1_re;
          sum6_1_im_1 <= sum6_1_im;
        end
      end
    end



  assign output_typeconvert_re = sum6_1_re_1[31:16];
  assign output_typeconvert_im = sum6_1_im_1[31:16];



  assign pp_fir_2_out_re = output_typeconvert_re;

  assign pp_fir_2_out_im = output_typeconvert_im;

endmodule  // pp_fir_2

