// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_ppfir_blocked\pp_fir_blocked.v
// Created: 2025-01-05 11:40:29
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 7.8125e-11
// Target subsystem base rate: 6.25e-10
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        6.25e-10
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Re_0                          ce_out        6.25e-10
// Re_s_0                        ce_out        6.25e-10
// Im_0                          ce_out        6.25e-10
// Im_s_0                        ce_out        6.25e-10
// Re_1                          ce_out        6.25e-10
// Re_s_1                        ce_out        6.25e-10
// Im_1                          ce_out        6.25e-10
// Im_s_1                        ce_out        6.25e-10
// Re_2                          ce_out        6.25e-10
// Re_s_2                        ce_out        6.25e-10
// Im_2                          ce_out        6.25e-10
// Im_s_2                        ce_out        6.25e-10
// Re_3                          ce_out        6.25e-10
// Re_s_3                        ce_out        6.25e-10
// Im_3                          ce_out        6.25e-10
// Im_s_3                        ce_out        6.25e-10
// Re_4                          ce_out        6.25e-10
// Re_s_4                        ce_out        6.25e-10
// Im_4                          ce_out        6.25e-10
// Im_s_4                        ce_out        6.25e-10
// Re_5                          ce_out        6.25e-10
// Re_s_5                        ce_out        6.25e-10
// Im_5                          ce_out        6.25e-10
// Im_s_5                        ce_out        6.25e-10
// Re_6                          ce_out        6.25e-10
// Re_s_6                        ce_out        6.25e-10
// Im_6                          ce_out        6.25e-10
// Im_s_6                        ce_out        6.25e-10
// Re_7                          ce_out        6.25e-10
// Re_s_7                        ce_out        6.25e-10
// Im_7                          ce_out        6.25e-10
// Im_s_7                        ce_out        6.25e-10
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_fir_blocked
// Source Path: scpa_ppfir_blocked/pp_fir_blocked
// Hierarchy Level: 0
// Model version: 1.32
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_fir_blocked
          (clk,
           rst_n,
           en,
           In1_re,
           In1_im,
           ce_out,
           Re_0,
           Re_s_0,
           Im_0,
           Im_s_0,
           Re_1,
           Re_s_1,
           Im_1,
           Im_s_1,
           Re_2,
           Re_s_2,
           Im_2,
           Im_s_2,
           Re_3,
           Re_s_3,
           Im_3,
           Im_s_3,
           Re_4,
           Re_s_4,
           Im_4,
           Im_s_4,
           Re_5,
           Re_s_5,
           Im_5,
           Im_s_5,
           Re_6,
           Re_s_6,
           Im_6,
           Im_s_6,
           Re_7,
           Re_s_7,
           Im_7,
           Im_s_7);


  input   clk;
  input   rst_n;
  input   en;
  input   signed [15:0] In1_re;  // sfix16_En15
  input   signed [15:0] In1_im;  // sfix16_En15
  output  ce_out;
  output  [255:0] Re_0;  // uint8
  output  Re_s_0;  // ufix1
  output  [255:0] Im_0;  // uint8
  output  Im_s_0;  // ufix1
  output  [255:0] Re_1;  // uint8
  output  Re_s_1;  // ufix1
  output  [255:0] Im_1;  // uint8
  output  Im_s_1;  // ufix1
  output  [255:0] Re_2;  // uint8
  output  Re_s_2;  // ufix1
  output  [255:0] Im_2;  // uint8
  output  Im_s_2;  // ufix1
  output  [255:0] Re_3;  // uint8
  output  Re_s_3;  // ufix1
  output  [255:0] Im_3;  // uint8
  output  Im_s_3;  // ufix1
  output  [255:0] Re_4;  // uint8
  output  Re_s_4;  // ufix1
  output  [255:0] Im_4;  // uint8
  output  Im_s_4;  // ufix1
  output  [255:0] Re_5;  // uint8
  output  Re_s_5;  // ufix1
  output  [255:0] Im_5;  // uint8
  output  Im_s_5;  // ufix1
  output  [255:0] Re_6;  // uint8
  output  Re_s_6;  // ufix1
  output  [255:0] Im_6;  // uint8
  output  Im_s_6;  // ufix1
  output  [255:0] Re_7;  // uint8
  output  Re_s_7;  // ufix1
  output  [255:0] Im_7;  // uint8
  output  Im_s_7;  // ufix1


  wire [255:0] pp_fir_u_0_re;  // uint8
  wire pp_fir_u_0_s_re;  // ufix1
  wire [255:0] pp_fir_u_0_im;  // uint8
  wire pp_fir_u_0_s_im;  // ufix1
  wire [255:0] pp_fir_u_1_re;  // uint8
  wire pp_fir_u_1_s_re;  // ufix1
  wire [255:0] pp_fir_u_1_im;  // uint8
  wire pp_fir_u_1_s_im;  // ufix1
  wire [255:0] pp_fir_u_2_re;  // uint8
  wire pp_fir_u_2_s_re;  // ufix1
  wire [255:0] pp_fir_u_2_im;  // uint8
  wire pp_fir_u_2_s_im;  // ufix1
  wire [255:0] pp_fir_u_3_re;  // uint8
  wire pp_fir_u_3_s_re;  // ufix1
  wire [255:0] pp_fir_u_3_im;  // uint8
  wire pp_fir_u_3_s_im;  // ufix1
  wire [255:0] pp_fir_u_4_re;  // uint8
  wire pp_fir_u_4_s_re;  // ufix1
  wire [255:0] pp_fir_u_4_im;  // uint8
  wire pp_fir_u_4_s_im;  // ufix1
  wire [255:0] pp_fir_u_5_re;  // uint8
  wire pp_fir_u_5_s_re;  // ufix1
  wire [255:0] pp_fir_u_5_im;  // uint8
  wire pp_fir_u_5_s_im;  // ufix1
  wire [255:0] pp_fir_u_6_re;  // uint8
  wire pp_fir_u_6_s_re;  // ufix1
  wire [255:0] pp_fir_u_6_im;  // uint8
  wire pp_fir_u_6_s_im;  // ufix1
  wire [255:0] pp_fir_u_7_re;  // uint8
  wire pp_fir_u_7_s_re;  // ufix1
  wire [255:0] pp_fir_u_7_im;  // uint8
  wire pp_fir_u_7_s_im;  // ufix1


  pp_fir_u_0 pp_fir_u_0_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_0_re),  // uint8
                             .sign_re(pp_fir_u_0_s_re),  // ufix1
                             .mag_im(pp_fir_u_0_im),  // uint8
                             .sign_im(pp_fir_u_0_s_im)  // ufix1
                             );

  assign Re_0 = pp_fir_u_0_re;

  assign Re_s_0 = pp_fir_u_0_s_re;

  assign Im_0 = pp_fir_u_0_im;

  assign Im_s_0 = pp_fir_u_0_s_im;

  pp_fir_u_1 pp_fir_u_1_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_1_re),  // uint8
                             .sign_re(pp_fir_u_1_s_re),  // ufix1
                             .mag_im(pp_fir_u_1_im),  // uint8
                             .sign_im(pp_fir_u_1_s_im)  // ufix1
                             );

  assign Re_1 = pp_fir_u_1_re;

  assign Re_s_1 = pp_fir_u_1_s_re;

  assign Im_1 = pp_fir_u_1_im;

  assign Im_s_1 = pp_fir_u_1_s_im;

  pp_fir_u_2 pp_fir_u_2_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_2_re),  // uint8
                             .sign_re(pp_fir_u_2_s_re),  // ufix1
                             .mag_im(pp_fir_u_2_im),  // uint8
                             .sign_im(pp_fir_u_2_s_im)  // ufix1
                             );

  assign Re_2 = pp_fir_u_2_re;

  assign Re_s_2 = pp_fir_u_2_s_re;

  assign Im_2 = pp_fir_u_2_im;

  assign Im_s_2 = pp_fir_u_2_s_im;

  pp_fir_u_3 pp_fir_u_3_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_3_re),  // uint8
                             .sign_re(pp_fir_u_3_s_re),  // ufix1
                             .mag_im(pp_fir_u_3_im),  // uint8
                             .sign_im(pp_fir_u_3_s_im)  // ufix1
                             );

  assign Re_3 = pp_fir_u_3_re;

  assign Re_s_3 = pp_fir_u_3_s_re;

  assign Im_3 = pp_fir_u_3_im;

  assign Im_s_3 = pp_fir_u_3_s_im;

  pp_fir_u_4 pp_fir_u_4_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_4_re),  // uint8
                             .sign_re(pp_fir_u_4_s_re),  // ufix1
                             .mag_im(pp_fir_u_4_im),  // uint8
                             .sign_im(pp_fir_u_4_s_im)  // ufix1
                             );

  assign Re_4 = pp_fir_u_4_re;

  assign Re_s_4 = pp_fir_u_4_s_re;

  assign Im_4 = pp_fir_u_4_im;

  assign Im_s_4 = pp_fir_u_4_s_im;

  pp_fir_u_5 pp_fir_u_5_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_5_re),  // uint8
                             .sign_re(pp_fir_u_5_s_re),  // ufix1
                             .mag_im(pp_fir_u_5_im),  // uint8
                             .sign_im(pp_fir_u_5_s_im)  // ufix1
                             );

  assign Re_5 = pp_fir_u_5_re;

  assign Re_s_5 = pp_fir_u_5_s_re;

  assign Im_5 = pp_fir_u_5_im;

  assign Im_s_5 = pp_fir_u_5_s_im;

  pp_fir_u_6 pp_fir_u_6_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_6_re),  // uint8
                             .sign_re(pp_fir_u_6_s_re),  // ufix1
                             .mag_im(pp_fir_u_6_im),  // uint8
                             .sign_im(pp_fir_u_6_s_im)  // ufix1
                             );

  assign Re_6 = pp_fir_u_6_re;

  assign Re_s_6 = pp_fir_u_6_s_re;

  assign Im_6 = pp_fir_u_6_im;

  assign Im_s_6 = pp_fir_u_6_s_im;

  pp_fir_u_7 pp_fir_u_7_1_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_8_0(en),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_7_re),  // uint8
                             .sign_re(pp_fir_u_7_s_re),  // ufix1
                             .mag_im(pp_fir_u_7_im),  // uint8
                             .sign_im(pp_fir_u_7_s_im)  // ufix1
                             );

  assign Re_7 = pp_fir_u_7_re;

  assign Re_s_7 = pp_fir_u_7_s_re;

  assign Im_7 = pp_fir_u_7_im;

  assign Im_s_7 = pp_fir_u_7_s_im;

  assign ce_out = en;

endmodule  // pp_fir_blocked

