// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_ppfir\comp_signed_mag_0.v
// Created: 2025-01-02 12:07:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: comp_signed_mag_0
// Source Path: scpa_ppfir/pp_fir/comp_signed_mag_0
// Hierarchy Level: 1
// Model version: 1.25
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module signed_mag_unary
          (In1_re,
           In1_im,
           mag_re,
           sign_re,
           mag_im,
           sign_im,
           clk,
           rst);

  input wire clk;
  input wire rst;
  input   signed [8:0] In1_re;  // sfix9
  input   signed [8:0] In1_im;  // sfix9
  output  reg [255:0] mag_re;  // uint8
  output  reg sign_re;  // ufix1
  output  reg [255:0] mag_im;  // uint8
  output  reg sign_im;  // ufix1

  reg signed [8:0] abs_re_stage1;  // sfix10
  reg sign_re_stage1;
  reg signed [8:0] abs_im_stage1;  // sfix10
  reg sign_im_stage1;
  wire [255:0] re_mag;
  wire [255:0] im_mag;

  //assign twos_re = {In1_re[8], In1_re};
  //assign twos_im = {In1_im[8], In1_im};

  always @ (posedge clk or negedge rst) begin
     if (!rst) begin
        abs_re_stage1 <= 9'sb0;
        abs_im_stage1 <= 9'sb0;
        sign_im_stage1 <= 1'b0;
        sign_im_stage1 <= 1'b0;
        mag_re <= 256'h0;
        sign_re <= 1'b0;
        mag_im <= 256'h0;
        sign_im <= 1'b0;
     end else begin
        //Stage 1: Calculate Absolute Value and Sign Bits
        abs_re_stage1 <= (In1_re[8] ?  -In1_re : In1_re);
        abs_im_stage1 <= (In1_im[8] ?  -In1_im : In1_im);
        sign_re_stage1 <= In1_re[8];
        sign_im_stage1 <= In1_im[8];

        //Stage 2: Assign Magnitude and Sign to Output
        sign_re <= sign_re_stage1;
        mag_re <= re_mag;
        sign_im <= sign_im_stage1;
        mag_im <= im_mag;
     end
  end

  b2u_8to255_quad b2u_8to255_quad_0 (
    .clk(clk),
    .rst(rst),
    .enable(1'b1),
    .iIn(abs_re_stage1[7:0]),
    .iMsb(1'b0),
    .qIn(abs_im_stage1[7:0]),
    .qMsb(1'b0),
    .iOut(re_mag),
    .qOut(im_mag)
  );

endmodule  // comp_signed_mag_unary