// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_int_fir_multiclk\fir_int_p0.v
// Created: 2025-01-20 09:03:33
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fir_int_p0
// Source Path: scpa_int_fir_multiclk/pp_int_x4/fir _int_p0
// Hierarchy Level: 1
// Model version: 1.13
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fir_int_p0
          (clk,
           rst_n,
           en,
           in_re,
           in_im,
           out_re,
           out_im);


  input   clk;
  input   rst_n;
  input   en;
  input   signed [12:0] in_re;  // sfix13_En12
  input   signed [12:0] in_im;  // sfix13_En12
  output  signed [15:0] out_re;  // sfix16_En15
  output  signed [15:0] out_im;  // sfix16_En15


  reg signed [12:0] Delay_Pipeline_reg_re [0:23];  // sfix13_En12 [24]
  reg signed [12:0] Delay_Pipeline_reg_im [0:23];  // sfix13_En12 [24]
  reg signed [12:0] Delay_Pipeline_reg_next_re [0:23];  // sfix13_En12 [24]
  reg signed [12:0] Delay_Pipeline_reg_next_im [0:23];  // sfix13_En12 [24]
  reg signed [12:0] delay_pipeline_re [0:23];  // sfix13_En12 [24]
  reg signed [12:0] delay_pipeline_im [0:23];  // sfix13_En12 [24]
  wire signed [12:0] delay_pipeline_23_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_23_im;  // sfix13_En12
  wire signed [31:0] product25_re;  // sfix32_En26
  wire signed [31:0] product25_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_22_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_22_im;  // sfix13_En12
  wire signed [31:0] product24_re;  // sfix32_En26
  wire signed [31:0] product24_im;  // sfix32_En26
  wire signed [31:0] sum1_1_re;  // sfix32_En26
  wire signed [31:0] sum1_1_im;  // sfix32_En26
  reg signed [31:0] sum1_1_re_1;  // sfix32_En26
  reg signed [31:0] sum1_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_21_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_21_im;  // sfix13_En12
  wire signed [31:0] product23_re;  // sfix32_En26
  wire signed [31:0] product23_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_20_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_20_im;  // sfix13_En12
  wire signed [31:0] product22_re;  // sfix32_En26
  wire signed [31:0] product22_im;  // sfix32_En26
  wire signed [31:0] sum1_2_re;  // sfix32_En26
  wire signed [31:0] sum1_2_im;  // sfix32_En26
  reg signed [31:0] sum1_2_re_1;  // sfix32_En26
  reg signed [31:0] sum1_2_im_1;  // sfix32_En26
  wire signed [31:0] sum2_1_re;  // sfix32_En26
  wire signed [31:0] sum2_1_im;  // sfix32_En26
  reg signed [31:0] sum2_1_re_1;  // sfix32_En26
  reg signed [31:0] sum2_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_19_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_19_im;  // sfix13_En12
  wire signed [31:0] product21_re;  // sfix32_En26
  wire signed [31:0] product21_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_18_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_18_im;  // sfix13_En12
  wire signed [31:0] product20_re;  // sfix32_En26
  wire signed [31:0] product20_im;  // sfix32_En26
  wire signed [31:0] sum1_3_re;  // sfix32_En26
  wire signed [31:0] sum1_3_im;  // sfix32_En26
  reg signed [31:0] sum1_3_re_1;  // sfix32_En26
  reg signed [31:0] sum1_3_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_17_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_17_im;  // sfix13_En12
  wire signed [31:0] product19_re;  // sfix32_En26
  wire signed [31:0] product19_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_16_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_16_im;  // sfix13_En12
  wire signed [31:0] product18_re;  // sfix32_En26
  wire signed [31:0] product18_im;  // sfix32_En26
  wire signed [31:0] sum1_4_re;  // sfix32_En26
  wire signed [31:0] sum1_4_im;  // sfix32_En26
  reg signed [31:0] sum1_4_re_1;  // sfix32_En26
  reg signed [31:0] sum1_4_im_1;  // sfix32_En26
  wire signed [31:0] sum2_2_re;  // sfix32_En26
  wire signed [31:0] sum2_2_im;  // sfix32_En26
  reg signed [31:0] sum2_2_re_1;  // sfix32_En26
  reg signed [31:0] sum2_2_im_1;  // sfix32_En26
  wire signed [31:0] sum3_1_re;  // sfix32_En26
  wire signed [31:0] sum3_1_im;  // sfix32_En26
  reg signed [31:0] sum3_1_re_1;  // sfix32_En26
  reg signed [31:0] sum3_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_15_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_15_im;  // sfix13_En12
  wire signed [31:0] product17_re;  // sfix32_En26
  wire signed [31:0] product17_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_14_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_14_im;  // sfix13_En12
  wire signed [31:0] product16_re;  // sfix32_En26
  wire signed [31:0] product16_im;  // sfix32_En26
  wire signed [31:0] sum1_5_re;  // sfix32_En26
  wire signed [31:0] sum1_5_im;  // sfix32_En26
  reg signed [31:0] sum1_5_re_1;  // sfix32_En26
  reg signed [31:0] sum1_5_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_13_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_13_im;  // sfix13_En12
  wire signed [31:0] product15_re;  // sfix32_En26
  wire signed [31:0] product15_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_12_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_12_im;  // sfix13_En12
  wire signed [31:0] product14_re;  // sfix32_En26
  wire signed [31:0] product14_im;  // sfix32_En26
  wire signed [31:0] sum1_6_re;  // sfix32_En26
  wire signed [31:0] sum1_6_im;  // sfix32_En26
  reg signed [31:0] sum1_6_re_1;  // sfix32_En26
  reg signed [31:0] sum1_6_im_1;  // sfix32_En26
  wire signed [31:0] sum2_3_re;  // sfix32_En26
  wire signed [31:0] sum2_3_im;  // sfix32_En26
  reg signed [31:0] sum2_3_re_1;  // sfix32_En26
  reg signed [31:0] sum2_3_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_11_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_11_im;  // sfix13_En12
  wire signed [31:0] product13_re;  // sfix32_En26
  wire signed [31:0] product13_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_10_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_10_im;  // sfix13_En12
  wire signed [31:0] product12_re;  // sfix32_En26
  wire signed [31:0] product12_im;  // sfix32_En26
  wire signed [31:0] sum1_7_re;  // sfix32_En26
  wire signed [31:0] sum1_7_im;  // sfix32_En26
  reg signed [31:0] sum1_7_re_1;  // sfix32_En26
  reg signed [31:0] sum1_7_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_9_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_9_im;  // sfix13_En12
  wire signed [31:0] product11_re;  // sfix32_En26
  wire signed [31:0] product11_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_8_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_8_im;  // sfix13_En12
  wire signed [31:0] product10_re;  // sfix32_En26
  wire signed [31:0] product10_im;  // sfix32_En26
  wire signed [31:0] sum1_8_re;  // sfix32_En26
  wire signed [31:0] sum1_8_im;  // sfix32_En26
  reg signed [31:0] sum1_8_re_1;  // sfix32_En26
  reg signed [31:0] sum1_8_im_1;  // sfix32_En26
  wire signed [31:0] sum2_4_re;  // sfix32_En26
  wire signed [31:0] sum2_4_im;  // sfix32_En26
  reg signed [31:0] sum2_4_re_1;  // sfix32_En26
  reg signed [31:0] sum2_4_im_1;  // sfix32_En26
  wire signed [31:0] sum3_2_re;  // sfix32_En26
  wire signed [31:0] sum3_2_im;  // sfix32_En26
  reg signed [31:0] sum3_2_re_1;  // sfix32_En26
  reg signed [31:0] sum3_2_im_1;  // sfix32_En26
  wire signed [31:0] sum4_1_re;  // sfix32_En26
  wire signed [31:0] sum4_1_im;  // sfix32_En26
  reg signed [31:0] sum4_1_re_1;  // sfix32_En26
  reg signed [31:0] sum4_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_7_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_7_im;  // sfix13_En12
  wire signed [31:0] product9_re;  // sfix32_En26
  wire signed [31:0] product9_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_6_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_6_im;  // sfix13_En12
  wire signed [31:0] product8_re;  // sfix32_En26
  wire signed [31:0] product8_im;  // sfix32_En26
  wire signed [31:0] sum1_9_re;  // sfix32_En26
  wire signed [31:0] sum1_9_im;  // sfix32_En26
  reg signed [31:0] sum1_9_re_1;  // sfix32_En26
  reg signed [31:0] sum1_9_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_5_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_5_im;  // sfix13_En12
  wire signed [31:0] product7_re;  // sfix32_En26
  wire signed [31:0] product7_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_4_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_4_im;  // sfix13_En12
  wire signed [31:0] product6_re;  // sfix32_En26
  wire signed [31:0] product6_im;  // sfix32_En26
  wire signed [31:0] sum1_10_re;  // sfix32_En26
  wire signed [31:0] sum1_10_im;  // sfix32_En26
  reg signed [31:0] sum1_10_re_1;  // sfix32_En26
  reg signed [31:0] sum1_10_im_1;  // sfix32_En26
  wire signed [31:0] sum2_5_re;  // sfix32_En26
  wire signed [31:0] sum2_5_im;  // sfix32_En26
  reg signed [31:0] sum2_5_re_1;  // sfix32_En26
  reg signed [31:0] sum2_5_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_3_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_3_im;  // sfix13_En12
  wire signed [31:0] product5_re;  // sfix32_En26
  wire signed [31:0] product5_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_2_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_2_im;  // sfix13_En12
  wire signed [31:0] product4_re;  // sfix32_En26
  wire signed [31:0] product4_im;  // sfix32_En26
  wire signed [31:0] sum1_11_re;  // sfix32_En26
  wire signed [31:0] sum1_11_im;  // sfix32_En26
  reg signed [31:0] sum1_11_re_1;  // sfix32_En26
  reg signed [31:0] sum1_11_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_1_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_1_im;  // sfix13_En12
  wire signed [31:0] product3_re;  // sfix32_En26
  wire signed [31:0] product3_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_0_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_0_im;  // sfix13_En12
  wire signed [31:0] product2_re;  // sfix32_En26
  wire signed [31:0] product2_im;  // sfix32_En26
  wire signed [31:0] sum1_12_re;  // sfix32_En26
  wire signed [31:0] sum1_12_im;  // sfix32_En26
  reg signed [31:0] sum1_12_re_1;  // sfix32_En26
  reg signed [31:0] sum1_12_im_1;  // sfix32_En26
  wire signed [31:0] sum2_6_re;  // sfix32_En26
  wire signed [31:0] sum2_6_im;  // sfix32_En26
  reg signed [31:0] sum2_6_re_1;  // sfix32_En26
  reg signed [31:0] sum2_6_im_1;  // sfix32_En26
  wire signed [31:0] sum3_3_re;  // sfix32_En26
  wire signed [31:0] sum3_3_im;  // sfix32_En26
  reg signed [31:0] sum3_3_re_1;  // sfix32_En26
  reg signed [31:0] sum3_3_im_1;  // sfix32_En26
  wire signed [31:0] product1_re;  // sfix32_En26
  wire signed [31:0] product1_im;  // sfix32_En26
  reg signed [31:0] product1_re_1;  // sfix32_En26
  reg signed [31:0] product1_im_1;  // sfix32_En26
  reg signed [31:0] product1_re_2;  // sfix32_En26
  reg signed [31:0] product1_im_2;  // sfix32_En26
  reg signed [31:0] product1_re_3;  // sfix32_En26
  reg signed [31:0] product1_im_3;  // sfix32_En26
  wire signed [31:0] sum4_2_re;  // sfix32_En26
  wire signed [31:0] sum4_2_im;  // sfix32_En26
  reg signed [31:0] sum4_2_re_1;  // sfix32_En26
  reg signed [31:0] sum4_2_im_1;  // sfix32_En26
  wire signed [31:0] sum5_1_re;  // sfix32_En26
  wire signed [31:0] sum5_1_im;  // sfix32_En26
  reg signed [31:0] sum5_1_re_1;  // sfix32_En26
  reg signed [31:0] sum5_1_im_1;  // sfix32_En26
  wire signed [15:0] output_typeconvert_re;  // sfix16_En15
  wire signed [15:0] output_typeconvert_im;  // sfix16_En15
  reg signed [31:0] Delay_Pipeline_t_0_0;  // int32
  reg signed [31:0] Delay_Pipeline_t_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_0_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_1_0;  // int32


  always @(posedge clk or negedge rst_n)
    begin : Delay_Pipeline_process
      if (rst_n == 1'b0) begin
        for(Delay_Pipeline_t_1_0 = 32'sd0; Delay_Pipeline_t_1_0 <= 32'sd23; Delay_Pipeline_t_1_0 = Delay_Pipeline_t_1_0 + 32'sd1) begin
          Delay_Pipeline_reg_re[Delay_Pipeline_t_1_0] <= 13'sb0000000000000;
          Delay_Pipeline_reg_im[Delay_Pipeline_t_1_0] <= 13'sb0000000000000;
        end
      end
      else begin
        if (en) begin
          for(Delay_Pipeline_t_0_1 = 32'sd0; Delay_Pipeline_t_0_1 <= 32'sd23; Delay_Pipeline_t_0_1 = Delay_Pipeline_t_0_1 + 32'sd1) begin
            Delay_Pipeline_reg_re[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_re[Delay_Pipeline_t_0_1];
            Delay_Pipeline_reg_im[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_im[Delay_Pipeline_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(Delay_Pipeline_t_0_0 = 32'sd0; Delay_Pipeline_t_0_0 <= 32'sd23; Delay_Pipeline_t_0_0 = Delay_Pipeline_t_0_0 + 32'sd1) begin
      delay_pipeline_re[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_re[Delay_Pipeline_t_0_0];
      delay_pipeline_im[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_im[Delay_Pipeline_t_0_0];
    end

    Delay_Pipeline_reg_next_re[0] = in_re;
    Delay_Pipeline_reg_next_im[0] = in_im;

    for(Delay_Pipeline_t_1 = 32'sd0; Delay_Pipeline_t_1 <= 32'sd22; Delay_Pipeline_t_1 = Delay_Pipeline_t_1 + 32'sd1) begin
      Delay_Pipeline_reg_next_re[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_re[Delay_Pipeline_t_1];
      Delay_Pipeline_reg_next_im[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_im[Delay_Pipeline_t_1];
    end

  end



  assign delay_pipeline_23_re = delay_pipeline_re[23];

  assign delay_pipeline_23_im = delay_pipeline_im[23];

  // coeff25
  assign product25_re = 32'sb00000000000000000000000000000000;
  assign product25_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_22_re = delay_pipeline_re[22];

  assign delay_pipeline_22_im = delay_pipeline_im[22];

  // coeff24
  assign product24_re = 32'sb00000000000000000000000000000000;
  assign product24_im = 32'sb00000000000000000000000000000000;



  assign sum1_1_re = product25_re + product24_re;
  assign sum1_1_im = product25_im + product24_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        sum1_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_1_re_1 <= sum1_1_re;
          sum1_1_im_1 <= sum1_1_im;
        end
      end
    end



  assign delay_pipeline_21_re = delay_pipeline_re[21];

  assign delay_pipeline_21_im = delay_pipeline_im[21];

  // coeff23
  assign product23_re = 32'sb00000000000000000000000000000000;
  assign product23_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_20_re = delay_pipeline_re[20];

  assign delay_pipeline_20_im = delay_pipeline_im[20];

  // coeff22
  assign product22_re = 32'sb00000000000000000000000000000000;
  assign product22_im = 32'sb00000000000000000000000000000000;



  assign sum1_2_re = product23_re + product22_re;
  assign sum1_2_im = product23_im + product22_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_1_process
      if (rst_n == 1'b0) begin
        sum1_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_2_re_1 <= sum1_2_re;
          sum1_2_im_1 <= sum1_2_im;
        end
      end
    end



  assign sum2_1_re = sum1_1_re_1 + sum1_2_re_1;
  assign sum2_1_im = sum1_1_im_1 + sum1_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_2_process
      if (rst_n == 1'b0) begin
        sum2_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_1_re_1 <= sum2_1_re;
          sum2_1_im_1 <= sum2_1_im;
        end
      end
    end



  assign delay_pipeline_19_re = delay_pipeline_re[19];

  assign delay_pipeline_19_im = delay_pipeline_im[19];

  // coeff21
  assign product21_re = 32'sb00000000000000000000000000000000;
  assign product21_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_18_re = delay_pipeline_re[18];

  assign delay_pipeline_18_im = delay_pipeline_im[18];

  // coeff20
  assign product20_re = 32'sb00000000000000000000000000000000;
  assign product20_im = 32'sb00000000000000000000000000000000;



  assign sum1_3_re = product21_re + product20_re;
  assign sum1_3_im = product21_im + product20_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_3_process
      if (rst_n == 1'b0) begin
        sum1_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_3_re_1 <= sum1_3_re;
          sum1_3_im_1 <= sum1_3_im;
        end
      end
    end



  assign delay_pipeline_17_re = delay_pipeline_re[17];

  assign delay_pipeline_17_im = delay_pipeline_im[17];

  // coeff19
  assign product19_re = 32'sb00000000000000000000000000000000;
  assign product19_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_16_re = delay_pipeline_re[16];

  assign delay_pipeline_16_im = delay_pipeline_im[16];

  // coeff18
  assign product18_re = 32'sb00000000000000000000000000000000;
  assign product18_im = 32'sb00000000000000000000000000000000;



  assign sum1_4_re = product19_re + product18_re;
  assign sum1_4_im = product19_im + product18_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_4_process
      if (rst_n == 1'b0) begin
        sum1_4_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_4_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_4_re_1 <= sum1_4_re;
          sum1_4_im_1 <= sum1_4_im;
        end
      end
    end



  assign sum2_2_re = sum1_3_re_1 + sum1_4_re_1;
  assign sum2_2_im = sum1_3_im_1 + sum1_4_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_5_process
      if (rst_n == 1'b0) begin
        sum2_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_2_re_1 <= sum2_2_re;
          sum2_2_im_1 <= sum2_2_im;
        end
      end
    end



  assign sum3_1_re = sum2_1_re_1 + sum2_2_re_1;
  assign sum3_1_im = sum2_1_im_1 + sum2_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_6_process
      if (rst_n == 1'b0) begin
        sum3_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum3_1_re_1 <= sum3_1_re;
          sum3_1_im_1 <= sum3_1_im;
        end
      end
    end



  assign delay_pipeline_15_re = delay_pipeline_re[15];

  assign delay_pipeline_15_im = delay_pipeline_im[15];

  // coeff17
  assign product17_re = 32'sb00000000000000000000000000000000;
  assign product17_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_14_re = delay_pipeline_re[14];

  assign delay_pipeline_14_im = delay_pipeline_im[14];

  // coeff16
  assign product16_re = 32'sb00000000000000000000000000000000;
  assign product16_im = 32'sb00000000000000000000000000000000;



  assign sum1_5_re = product17_re + product16_re;
  assign sum1_5_im = product17_im + product16_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_7_process
      if (rst_n == 1'b0) begin
        sum1_5_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_5_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_5_re_1 <= sum1_5_re;
          sum1_5_im_1 <= sum1_5_im;
        end
      end
    end



  assign delay_pipeline_13_re = delay_pipeline_re[13];

  assign delay_pipeline_13_im = delay_pipeline_im[13];

  // coeff15
  assign product15_re = 32'sb00000000000000000000000000000000;
  assign product15_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_12_re = delay_pipeline_re[12];

  assign delay_pipeline_12_im = delay_pipeline_im[12];

  // coeff14
  assign product14_re = 32'sb00000000000000000000000000000000;
  assign product14_im = 32'sb00000000000000000000000000000000;



  assign sum1_6_re = product15_re + product14_re;
  assign sum1_6_im = product15_im + product14_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_8_process
      if (rst_n == 1'b0) begin
        sum1_6_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_6_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_6_re_1 <= sum1_6_re;
          sum1_6_im_1 <= sum1_6_im;
        end
      end
    end



  assign sum2_3_re = sum1_5_re_1 + sum1_6_re_1;
  assign sum2_3_im = sum1_5_im_1 + sum1_6_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_9_process
      if (rst_n == 1'b0) begin
        sum2_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_3_re_1 <= sum2_3_re;
          sum2_3_im_1 <= sum2_3_im;
        end
      end
    end



  assign delay_pipeline_11_re = delay_pipeline_re[11];

  assign delay_pipeline_11_im = delay_pipeline_im[11];

  // coeff13
  assign product13_re = {{5{delay_pipeline_11_re[12]}}, {delay_pipeline_11_re, 14'b00000000000000}};
  assign product13_im = {{5{delay_pipeline_11_im[12]}}, {delay_pipeline_11_im, 14'b00000000000000}};



  assign delay_pipeline_10_re = delay_pipeline_re[10];

  assign delay_pipeline_10_im = delay_pipeline_im[10];

  // coeff12
  assign product12_re = 32'sb00000000000000000000000000000000;
  assign product12_im = 32'sb00000000000000000000000000000000;



  assign sum1_7_re = product13_re + product12_re;
  assign sum1_7_im = product13_im + product12_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_10_process
      if (rst_n == 1'b0) begin
        sum1_7_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_7_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_7_re_1 <= sum1_7_re;
          sum1_7_im_1 <= sum1_7_im;
        end
      end
    end



  assign delay_pipeline_9_re = delay_pipeline_re[9];

  assign delay_pipeline_9_im = delay_pipeline_im[9];

  // coeff11
  assign product11_re = 32'sb00000000000000000000000000000000;
  assign product11_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_8_re = delay_pipeline_re[8];

  assign delay_pipeline_8_im = delay_pipeline_im[8];

  // coeff10
  assign product10_re = 32'sb00000000000000000000000000000000;
  assign product10_im = 32'sb00000000000000000000000000000000;



  assign sum1_8_re = product11_re + product10_re;
  assign sum1_8_im = product11_im + product10_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_11_process
      if (rst_n == 1'b0) begin
        sum1_8_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_8_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_8_re_1 <= sum1_8_re;
          sum1_8_im_1 <= sum1_8_im;
        end
      end
    end



  assign sum2_4_re = sum1_7_re_1 + sum1_8_re_1;
  assign sum2_4_im = sum1_7_im_1 + sum1_8_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_12_process
      if (rst_n == 1'b0) begin
        sum2_4_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_4_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_4_re_1 <= sum2_4_re;
          sum2_4_im_1 <= sum2_4_im;
        end
      end
    end



  assign sum3_2_re = sum2_3_re_1 + sum2_4_re_1;
  assign sum3_2_im = sum2_3_im_1 + sum2_4_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_13_process
      if (rst_n == 1'b0) begin
        sum3_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum3_2_re_1 <= sum3_2_re;
          sum3_2_im_1 <= sum3_2_im;
        end
      end
    end



  assign sum4_1_re = sum3_1_re_1 + sum3_2_re_1;
  assign sum4_1_im = sum3_1_im_1 + sum3_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_14_process
      if (rst_n == 1'b0) begin
        sum4_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum4_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum4_1_re_1 <= sum4_1_re;
          sum4_1_im_1 <= sum4_1_im;
        end
      end
    end



  assign delay_pipeline_7_re = delay_pipeline_re[7];

  assign delay_pipeline_7_im = delay_pipeline_im[7];

  // coeff9
  assign product9_re = 32'sb00000000000000000000000000000000;
  assign product9_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_6_re = delay_pipeline_re[6];

  assign delay_pipeline_6_im = delay_pipeline_im[6];

  // coeff8
  assign product8_re = 32'sb00000000000000000000000000000000;
  assign product8_im = 32'sb00000000000000000000000000000000;



  assign sum1_9_re = product9_re + product8_re;
  assign sum1_9_im = product9_im + product8_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_15_process
      if (rst_n == 1'b0) begin
        sum1_9_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_9_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_9_re_1 <= sum1_9_re;
          sum1_9_im_1 <= sum1_9_im;
        end
      end
    end



  assign delay_pipeline_5_re = delay_pipeline_re[5];

  assign delay_pipeline_5_im = delay_pipeline_im[5];

  // coeff7
  assign product7_re = 32'sb00000000000000000000000000000000;
  assign product7_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_4_re = delay_pipeline_re[4];

  assign delay_pipeline_4_im = delay_pipeline_im[4];

  // coeff6
  assign product6_re = 32'sb00000000000000000000000000000000;
  assign product6_im = 32'sb00000000000000000000000000000000;



  assign sum1_10_re = product7_re + product6_re;
  assign sum1_10_im = product7_im + product6_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_16_process
      if (rst_n == 1'b0) begin
        sum1_10_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_10_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_10_re_1 <= sum1_10_re;
          sum1_10_im_1 <= sum1_10_im;
        end
      end
    end



  assign sum2_5_re = sum1_9_re_1 + sum1_10_re_1;
  assign sum2_5_im = sum1_9_im_1 + sum1_10_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_17_process
      if (rst_n == 1'b0) begin
        sum2_5_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_5_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_5_re_1 <= sum2_5_re;
          sum2_5_im_1 <= sum2_5_im;
        end
      end
    end



  assign delay_pipeline_3_re = delay_pipeline_re[3];

  assign delay_pipeline_3_im = delay_pipeline_im[3];

  // coeff5
  assign product5_re = 32'sb00000000000000000000000000000000;
  assign product5_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_2_re = delay_pipeline_re[2];

  assign delay_pipeline_2_im = delay_pipeline_im[2];

  // coeff4
  assign product4_re = 32'sb00000000000000000000000000000000;
  assign product4_im = 32'sb00000000000000000000000000000000;



  assign sum1_11_re = product5_re + product4_re;
  assign sum1_11_im = product5_im + product4_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_18_process
      if (rst_n == 1'b0) begin
        sum1_11_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_11_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_11_re_1 <= sum1_11_re;
          sum1_11_im_1 <= sum1_11_im;
        end
      end
    end



  assign delay_pipeline_1_re = delay_pipeline_re[1];

  assign delay_pipeline_1_im = delay_pipeline_im[1];

  // coeff3
  assign product3_re = 32'sb00000000000000000000000000000000;
  assign product3_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_0_re = delay_pipeline_re[0];

  assign delay_pipeline_0_im = delay_pipeline_im[0];

  // coeff2
  assign product2_re = 32'sb00000000000000000000000000000000;
  assign product2_im = 32'sb00000000000000000000000000000000;



  assign sum1_12_re = product3_re + product2_re;
  assign sum1_12_im = product3_im + product2_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_19_process
      if (rst_n == 1'b0) begin
        sum1_12_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_12_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_12_re_1 <= sum1_12_re;
          sum1_12_im_1 <= sum1_12_im;
        end
      end
    end



  assign sum2_6_re = sum1_11_re_1 + sum1_12_re_1;
  assign sum2_6_im = sum1_11_im_1 + sum1_12_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_20_process
      if (rst_n == 1'b0) begin
        sum2_6_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_6_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_6_re_1 <= sum2_6_re;
          sum2_6_im_1 <= sum2_6_im;
        end
      end
    end



  assign sum3_3_re = sum2_5_re_1 + sum2_6_re_1;
  assign sum3_3_im = sum2_5_im_1 + sum2_6_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_21_process
      if (rst_n == 1'b0) begin
        sum3_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum3_3_re_1 <= sum3_3_re;
          sum3_3_im_1 <= sum3_3_im;
        end
      end
    end



  // coeff1
  assign product1_re = 32'sb00000000000000000000000000000000;
  assign product1_im = 32'sb00000000000000000000000000000000;



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        product1_re_1 <= 32'sb00000000000000000000000000000000;
        product1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          product1_re_1 <= product1_re;
          product1_im_1 <= product1_im;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        product1_re_2 <= 32'sb00000000000000000000000000000000;
        product1_im_2 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          product1_re_2 <= product1_re_1;
          product1_im_2 <= product1_im_1;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : gain_out_buff_out_buff_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        product1_re_3 <= 32'sb00000000000000000000000000000000;
        product1_im_3 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          product1_re_3 <= product1_re_2;
          product1_im_3 <= product1_im_2;
        end
      end
    end



  assign sum4_2_re = sum3_3_re_1 + product1_re_3;
  assign sum4_2_im = sum3_3_im_1 + product1_im_3;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_22_process
      if (rst_n == 1'b0) begin
        sum4_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum4_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum4_2_re_1 <= sum4_2_re;
          sum4_2_im_1 <= sum4_2_im;
        end
      end
    end



  assign sum5_1_re = sum4_1_re_1 + sum4_2_re_1;
  assign sum5_1_im = sum4_1_im_1 + sum4_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_23_process
      if (rst_n == 1'b0) begin
        sum5_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum5_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum5_1_re_1 <= sum5_1_re;
          sum5_1_im_1 <= sum5_1_im;
        end
      end
    end



  assign output_typeconvert_re = sum5_1_re_1[26:11];
  assign output_typeconvert_im = sum5_1_im_1[26:11];



  assign out_re = output_typeconvert_re;

  assign out_im = output_typeconvert_im;

endmodule  // fir_int_p0

