// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_int_fir_multiclk\fir_int_p11.v
// Created: 2025-01-20 08:19:43
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fir_int_p11
// Source Path: scpa_int_fir_multiclk/pp_int_x4/fir_int_p11
// Hierarchy Level: 1
// Model version: 1.13
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fir_int_p2
          (clk,
           rst_n,
           en,
           in_re,
           in_im,
           out_re,
           out_im);


  input   clk;
  input   rst_n;
  input   en;
  input   signed [12:0] in_re;  // sfix13_En12
  input   signed [12:0] in_im;  // sfix13_En12
  output  signed [15:0] out_re;  // sfix16_En15
  output  signed [15:0] out_im;  // sfix16_En15


  reg signed [12:0] Delay_Pipeline_reg_re [0:23];  // sfix13_En12 [24]
  reg signed [12:0] Delay_Pipeline_reg_im [0:23];  // sfix13_En12 [24]
  reg signed [12:0] Delay_Pipeline_reg_next_re [0:23];  // sfix13_En12 [24]
  reg signed [12:0] Delay_Pipeline_reg_next_im [0:23];  // sfix13_En12 [24]
  reg signed [12:0] delay_pipeline_re [0:23];  // sfix13_En12 [24]
  reg signed [12:0] delay_pipeline_im [0:23];  // sfix13_En12 [24]
  wire signed [12:0] delay_pipeline_23_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_23_im;  // sfix13_En12
  wire signed [31:0] product25_re;  // sfix32_En26
  wire signed [31:0] product25_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_22_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_22_im;  // sfix13_En12
  wire signed [15:0] coeff24;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_1;  // sfix29_En26
  wire signed [31:0] product24_re;  // sfix32_En26
  wire signed [31:0] product24_im;  // sfix32_En26
  wire signed [31:0] sum1_1_re;  // sfix32_En26
  wire signed [31:0] sum1_1_im;  // sfix32_En26
  reg signed [31:0] sum1_1_re_1;  // sfix32_En26
  reg signed [31:0] sum1_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_21_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_21_im;  // sfix13_En12
  wire signed [15:0] coeff23;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_2;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_3;  // sfix29_En26
  wire signed [31:0] product23_re;  // sfix32_En26
  wire signed [31:0] product23_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_20_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_20_im;  // sfix13_En12
  wire signed [15:0] coeff22;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_4;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_5;  // sfix29_En26
  wire signed [31:0] product22_re;  // sfix32_En26
  wire signed [31:0] product22_im;  // sfix32_En26
  wire signed [31:0] sum1_2_re;  // sfix32_En26
  wire signed [31:0] sum1_2_im;  // sfix32_En26
  reg signed [31:0] sum1_2_re_1;  // sfix32_En26
  reg signed [31:0] sum1_2_im_1;  // sfix32_En26
  wire signed [31:0] sum2_1_re;  // sfix32_En26
  wire signed [31:0] sum2_1_im;  // sfix32_En26
  reg signed [31:0] sum2_1_re_1;  // sfix32_En26
  reg signed [31:0] sum2_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_19_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_19_im;  // sfix13_En12
  wire signed [15:0] coeff21;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_6;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_7;  // sfix29_En26
  wire signed [31:0] product21_re;  // sfix32_En26
  wire signed [31:0] product21_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_18_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_18_im;  // sfix13_En12
  wire signed [15:0] coeff20;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_8;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_9;  // sfix29_En26
  wire signed [31:0] product20_re;  // sfix32_En26
  wire signed [31:0] product20_im;  // sfix32_En26
  wire signed [31:0] sum1_3_re;  // sfix32_En26
  wire signed [31:0] sum1_3_im;  // sfix32_En26
  reg signed [31:0] sum1_3_re_1;  // sfix32_En26
  reg signed [31:0] sum1_3_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_17_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_17_im;  // sfix13_En12
  wire signed [15:0] coeff19;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_10;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_11;  // sfix29_En26
  wire signed [31:0] product19_re;  // sfix32_En26
  wire signed [31:0] product19_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_16_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_16_im;  // sfix13_En12
  wire signed [15:0] coeff18;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_12;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_13;  // sfix29_En26
  wire signed [31:0] product18_re;  // sfix32_En26
  wire signed [31:0] product18_im;  // sfix32_En26
  wire signed [31:0] sum1_4_re;  // sfix32_En26
  wire signed [31:0] sum1_4_im;  // sfix32_En26
  reg signed [31:0] sum1_4_re_1;  // sfix32_En26
  reg signed [31:0] sum1_4_im_1;  // sfix32_En26
  wire signed [31:0] sum2_2_re;  // sfix32_En26
  wire signed [31:0] sum2_2_im;  // sfix32_En26
  reg signed [31:0] sum2_2_re_1;  // sfix32_En26
  reg signed [31:0] sum2_2_im_1;  // sfix32_En26
  wire signed [31:0] sum3_1_re;  // sfix32_En26
  wire signed [31:0] sum3_1_im;  // sfix32_En26
  reg signed [31:0] sum3_1_re_1;  // sfix32_En26
  reg signed [31:0] sum3_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_15_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_15_im;  // sfix13_En12
  wire signed [15:0] coeff17;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_14;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_15;  // sfix29_En26
  wire signed [31:0] product17_re;  // sfix32_En26
  wire signed [31:0] product17_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_14_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_14_im;  // sfix13_En12
  wire signed [15:0] coeff16;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_16;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_17;  // sfix29_En26
  wire signed [31:0] product16_re;  // sfix32_En26
  wire signed [31:0] product16_im;  // sfix32_En26
  wire signed [31:0] sum1_5_re;  // sfix32_En26
  wire signed [31:0] sum1_5_im;  // sfix32_En26
  reg signed [31:0] sum1_5_re_1;  // sfix32_En26
  reg signed [31:0] sum1_5_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_13_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_13_im;  // sfix13_En12
  wire signed [15:0] coeff15;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_18;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_19;  // sfix29_En26
  wire signed [31:0] product15_re;  // sfix32_En26
  wire signed [31:0] product15_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_12_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_12_im;  // sfix13_En12
  wire signed [15:0] coeff14;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_20;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_21;  // sfix29_En26
  wire signed [31:0] product14_re;  // sfix32_En26
  wire signed [31:0] product14_im;  // sfix32_En26
  wire signed [31:0] sum1_6_re;  // sfix32_En26
  wire signed [31:0] sum1_6_im;  // sfix32_En26
  reg signed [31:0] sum1_6_re_1;  // sfix32_En26
  reg signed [31:0] sum1_6_im_1;  // sfix32_En26
  wire signed [31:0] sum2_3_re;  // sfix32_En26
  wire signed [31:0] sum2_3_im;  // sfix32_En26
  reg signed [31:0] sum2_3_re_1;  // sfix32_En26
  reg signed [31:0] sum2_3_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_11_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_11_im;  // sfix13_En12
  wire signed [15:0] coeff13;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_22;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_23;  // sfix29_En26
  wire signed [31:0] product13_re;  // sfix32_En26
  wire signed [31:0] product13_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_10_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_10_im;  // sfix13_En12
  wire signed [15:0] coeff12;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_24;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_25;  // sfix29_En26
  wire signed [31:0] product12_re;  // sfix32_En26
  wire signed [31:0] product12_im;  // sfix32_En26
  wire signed [31:0] sum1_7_re;  // sfix32_En26
  wire signed [31:0] sum1_7_im;  // sfix32_En26
  reg signed [31:0] sum1_7_re_1;  // sfix32_En26
  reg signed [31:0] sum1_7_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_9_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_9_im;  // sfix13_En12
  wire signed [15:0] coeff11;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_26;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_27;  // sfix29_En26
  wire signed [31:0] product11_re;  // sfix32_En26
  wire signed [31:0] product11_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_8_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_8_im;  // sfix13_En12
  wire signed [15:0] coeff10;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_28;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_29;  // sfix29_En26
  wire signed [31:0] product10_re;  // sfix32_En26
  wire signed [31:0] product10_im;  // sfix32_En26
  wire signed [31:0] sum1_8_re;  // sfix32_En26
  wire signed [31:0] sum1_8_im;  // sfix32_En26
  reg signed [31:0] sum1_8_re_1;  // sfix32_En26
  reg signed [31:0] sum1_8_im_1;  // sfix32_En26
  wire signed [31:0] sum2_4_re;  // sfix32_En26
  wire signed [31:0] sum2_4_im;  // sfix32_En26
  reg signed [31:0] sum2_4_re_1;  // sfix32_En26
  reg signed [31:0] sum2_4_im_1;  // sfix32_En26
  wire signed [31:0] sum3_2_re;  // sfix32_En26
  wire signed [31:0] sum3_2_im;  // sfix32_En26
  reg signed [31:0] sum3_2_re_1;  // sfix32_En26
  reg signed [31:0] sum3_2_im_1;  // sfix32_En26
  wire signed [31:0] sum4_1_re;  // sfix32_En26
  wire signed [31:0] sum4_1_im;  // sfix32_En26
  reg signed [31:0] sum4_1_re_1;  // sfix32_En26
  reg signed [31:0] sum4_1_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_7_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_7_im;  // sfix13_En12
  wire signed [15:0] coeff9;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_30;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_31;  // sfix29_En26
  wire signed [31:0] product9_re;  // sfix32_En26
  wire signed [31:0] product9_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_6_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_6_im;  // sfix13_En12
  wire signed [15:0] coeff8;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_32;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_33;  // sfix29_En26
  wire signed [31:0] product8_re;  // sfix32_En26
  wire signed [31:0] product8_im;  // sfix32_En26
  wire signed [31:0] sum1_9_re;  // sfix32_En26
  wire signed [31:0] sum1_9_im;  // sfix32_En26
  reg signed [31:0] sum1_9_re_1;  // sfix32_En26
  reg signed [31:0] sum1_9_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_5_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_5_im;  // sfix13_En12
  wire signed [15:0] coeff7;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_34;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_35;  // sfix29_En26
  wire signed [31:0] product7_re;  // sfix32_En26
  wire signed [31:0] product7_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_4_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_4_im;  // sfix13_En12
  wire signed [15:0] coeff6;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_36;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_37;  // sfix29_En26
  wire signed [31:0] product6_re;  // sfix32_En26
  wire signed [31:0] product6_im;  // sfix32_En26
  wire signed [31:0] sum1_10_re;  // sfix32_En26
  wire signed [31:0] sum1_10_im;  // sfix32_En26
  reg signed [31:0] sum1_10_re_1;  // sfix32_En26
  reg signed [31:0] sum1_10_im_1;  // sfix32_En26
  wire signed [31:0] sum2_5_re;  // sfix32_En26
  wire signed [31:0] sum2_5_im;  // sfix32_En26
  reg signed [31:0] sum2_5_re_1;  // sfix32_En26
  reg signed [31:0] sum2_5_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_3_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_3_im;  // sfix13_En12
  wire signed [15:0] coeff5;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_38;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_39;  // sfix29_En26
  wire signed [31:0] product5_re;  // sfix32_En26
  wire signed [31:0] product5_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_2_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_2_im;  // sfix13_En12
  wire signed [15:0] coeff4;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_40;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_41;  // sfix29_En26
  wire signed [31:0] product4_re;  // sfix32_En26
  wire signed [31:0] product4_im;  // sfix32_En26
  wire signed [31:0] sum1_11_re;  // sfix32_En26
  wire signed [31:0] sum1_11_im;  // sfix32_En26
  reg signed [31:0] sum1_11_re_1;  // sfix32_En26
  reg signed [31:0] sum1_11_im_1;  // sfix32_En26
  wire signed [12:0] delay_pipeline_1_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_1_im;  // sfix13_En12
  wire signed [15:0] coeff3;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_42;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_43;  // sfix29_En26
  wire signed [31:0] product3_re;  // sfix32_En26
  wire signed [31:0] product3_im;  // sfix32_En26
  wire signed [12:0] delay_pipeline_0_re;  // sfix13_En12
  wire signed [12:0] delay_pipeline_0_im;  // sfix13_En12
  wire signed [15:0] coeff2;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_44;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_45;  // sfix29_En26
  wire signed [31:0] product2_re;  // sfix32_En26
  wire signed [31:0] product2_im;  // sfix32_En26
  wire signed [31:0] sum1_12_re;  // sfix32_En26
  wire signed [31:0] sum1_12_im;  // sfix32_En26
  reg signed [31:0] sum1_12_re_1;  // sfix32_En26
  reg signed [31:0] sum1_12_im_1;  // sfix32_En26
  wire signed [31:0] sum2_6_re;  // sfix32_En26
  wire signed [31:0] sum2_6_im;  // sfix32_En26
  reg signed [31:0] sum2_6_re_1;  // sfix32_En26
  reg signed [31:0] sum2_6_im_1;  // sfix32_En26
  wire signed [31:0] sum3_3_re;  // sfix32_En26
  wire signed [31:0] sum3_3_im;  // sfix32_En26
  reg signed [31:0] sum3_3_re_1;  // sfix32_En26
  reg signed [31:0] sum3_3_im_1;  // sfix32_En26
  wire signed [15:0] coeff1;  // sfix16_En14
  wire signed [28:0] multiplier_mul_temp_46;  // sfix29_En26
  wire signed [28:0] multiplier_mul_temp_47;  // sfix29_En26
  wire signed [31:0] product1_re;  // sfix32_En26
  wire signed [31:0] product1_im;  // sfix32_En26
  reg signed [31:0] product1_re_1;  // sfix32_En26
  reg signed [31:0] product1_im_1;  // sfix32_En26
  reg signed [31:0] product1_re_2;  // sfix32_En26
  reg signed [31:0] product1_im_2;  // sfix32_En26
  reg signed [31:0] product1_re_3;  // sfix32_En26
  reg signed [31:0] product1_im_3;  // sfix32_En26
  wire signed [31:0] sum4_2_re;  // sfix32_En26
  wire signed [31:0] sum4_2_im;  // sfix32_En26
  reg signed [31:0] sum4_2_re_1;  // sfix32_En26
  reg signed [31:0] sum4_2_im_1;  // sfix32_En26
  wire signed [31:0] sum5_1_re;  // sfix32_En26
  wire signed [31:0] sum5_1_im;  // sfix32_En26
  reg signed [31:0] sum5_1_re_1;  // sfix32_En26
  reg signed [31:0] sum5_1_im_1;  // sfix32_En26
  wire signed [15:0] output_typeconvert_re;  // sfix16_En15
  wire signed [15:0] output_typeconvert_im;  // sfix16_En15
  reg signed [31:0] Delay_Pipeline_t_0_0;  // int32
  reg signed [31:0] Delay_Pipeline_t_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_0_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_1_0;  // int32


  always @(posedge clk or negedge rst_n)
    begin : Delay_Pipeline_process
      if (rst_n == 1'b0) begin
        for(Delay_Pipeline_t_1_0 = 32'sd0; Delay_Pipeline_t_1_0 <= 32'sd23; Delay_Pipeline_t_1_0 = Delay_Pipeline_t_1_0 + 32'sd1) begin
          Delay_Pipeline_reg_re[Delay_Pipeline_t_1_0] <= 13'sb0000000000000;
          Delay_Pipeline_reg_im[Delay_Pipeline_t_1_0] <= 13'sb0000000000000;
        end
      end
      else begin
        if (en) begin
          for(Delay_Pipeline_t_0_1 = 32'sd0; Delay_Pipeline_t_0_1 <= 32'sd23; Delay_Pipeline_t_0_1 = Delay_Pipeline_t_0_1 + 32'sd1) begin
            Delay_Pipeline_reg_re[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_re[Delay_Pipeline_t_0_1];
            Delay_Pipeline_reg_im[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_im[Delay_Pipeline_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(Delay_Pipeline_t_0_0 = 32'sd0; Delay_Pipeline_t_0_0 <= 32'sd23; Delay_Pipeline_t_0_0 = Delay_Pipeline_t_0_0 + 32'sd1) begin
      delay_pipeline_re[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_re[Delay_Pipeline_t_0_0];
      delay_pipeline_im[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_im[Delay_Pipeline_t_0_0];
    end

    Delay_Pipeline_reg_next_re[0] = in_re;
    Delay_Pipeline_reg_next_im[0] = in_im;

    for(Delay_Pipeline_t_1 = 32'sd0; Delay_Pipeline_t_1 <= 32'sd22; Delay_Pipeline_t_1 = Delay_Pipeline_t_1 + 32'sd1) begin
      Delay_Pipeline_reg_next_re[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_re[Delay_Pipeline_t_1];
      Delay_Pipeline_reg_next_im[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_im[Delay_Pipeline_t_1];
    end

  end



  assign delay_pipeline_23_re = delay_pipeline_re[23];

  assign delay_pipeline_23_im = delay_pipeline_im[23];

  // coeff25
  assign product25_re = 32'sb00000000000000000000000000000000;
  assign product25_im = 32'sb00000000000000000000000000000000;



  assign delay_pipeline_22_re = delay_pipeline_re[22];

  assign delay_pipeline_22_im = delay_pipeline_im[22];

  assign coeff24 = 16'sb1111111111111101;



  assign multiplier_mul_temp = delay_pipeline_22_re * coeff24;
  assign product24_re = {{3{multiplier_mul_temp[28]}}, multiplier_mul_temp};
  assign multiplier_mul_temp_1 = delay_pipeline_22_im * coeff24;
  assign product24_im = {{3{multiplier_mul_temp_1[28]}}, multiplier_mul_temp_1};



  assign sum1_1_re = product25_re + product24_re;
  assign sum1_1_im = product25_im + product24_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        sum1_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_1_re_1 <= sum1_1_re;
          sum1_1_im_1 <= sum1_1_im;
        end
      end
    end



  assign delay_pipeline_21_re = delay_pipeline_re[21];

  assign delay_pipeline_21_im = delay_pipeline_im[21];

  assign coeff23 = 16'sb0000000000001101;



  assign multiplier_mul_temp_2 = delay_pipeline_21_re * coeff23;
  assign product23_re = {{3{multiplier_mul_temp_2[28]}}, multiplier_mul_temp_2};
  assign multiplier_mul_temp_3 = delay_pipeline_21_im * coeff23;
  assign product23_im = {{3{multiplier_mul_temp_3[28]}}, multiplier_mul_temp_3};



  assign delay_pipeline_20_re = delay_pipeline_re[20];

  assign delay_pipeline_20_im = delay_pipeline_im[20];

  assign coeff22 = 16'sb1111111111011111;



  assign multiplier_mul_temp_4 = delay_pipeline_20_re * coeff22;
  assign product22_re = {{3{multiplier_mul_temp_4[28]}}, multiplier_mul_temp_4};
  assign multiplier_mul_temp_5 = delay_pipeline_20_im * coeff22;
  assign product22_im = {{3{multiplier_mul_temp_5[28]}}, multiplier_mul_temp_5};



  assign sum1_2_re = product23_re + product22_re;
  assign sum1_2_im = product23_im + product22_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_1_process
      if (rst_n == 1'b0) begin
        sum1_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_2_re_1 <= sum1_2_re;
          sum1_2_im_1 <= sum1_2_im;
        end
      end
    end



  assign sum2_1_re = sum1_1_re_1 + sum1_2_re_1;
  assign sum2_1_im = sum1_1_im_1 + sum1_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_2_process
      if (rst_n == 1'b0) begin
        sum2_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_1_re_1 <= sum2_1_re;
          sum2_1_im_1 <= sum2_1_im;
        end
      end
    end



  assign delay_pipeline_19_re = delay_pipeline_re[19];

  assign delay_pipeline_19_im = delay_pipeline_im[19];

  assign coeff21 = 16'sb0000000001001001;



  assign multiplier_mul_temp_6 = delay_pipeline_19_re * coeff21;
  assign product21_re = {{3{multiplier_mul_temp_6[28]}}, multiplier_mul_temp_6};
  assign multiplier_mul_temp_7 = delay_pipeline_19_im * coeff21;
  assign product21_im = {{3{multiplier_mul_temp_7[28]}}, multiplier_mul_temp_7};



  assign delay_pipeline_18_re = delay_pipeline_re[18];

  assign delay_pipeline_18_im = delay_pipeline_im[18];

  assign coeff20 = 16'sb1111111101110011;



  assign multiplier_mul_temp_8 = delay_pipeline_18_re * coeff20;
  assign product20_re = {{3{multiplier_mul_temp_8[28]}}, multiplier_mul_temp_8};
  assign multiplier_mul_temp_9 = delay_pipeline_18_im * coeff20;
  assign product20_im = {{3{multiplier_mul_temp_9[28]}}, multiplier_mul_temp_9};



  assign sum1_3_re = product21_re + product20_re;
  assign sum1_3_im = product21_im + product20_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_3_process
      if (rst_n == 1'b0) begin
        sum1_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_3_re_1 <= sum1_3_re;
          sum1_3_im_1 <= sum1_3_im;
        end
      end
    end



  assign delay_pipeline_17_re = delay_pipeline_re[17];

  assign delay_pipeline_17_im = delay_pipeline_im[17];

  assign coeff19 = 16'sb0000000011111011;



  assign multiplier_mul_temp_10 = delay_pipeline_17_re * coeff19;
  assign product19_re = {{3{multiplier_mul_temp_10[28]}}, multiplier_mul_temp_10};
  assign multiplier_mul_temp_11 = delay_pipeline_17_im * coeff19;
  assign product19_im = {{3{multiplier_mul_temp_11[28]}}, multiplier_mul_temp_11};



  assign delay_pipeline_16_re = delay_pipeline_re[16];

  assign delay_pipeline_16_im = delay_pipeline_im[16];

  assign coeff18 = 16'sb1111111001011011;



  assign multiplier_mul_temp_12 = delay_pipeline_16_re * coeff18;
  assign product18_re = {{3{multiplier_mul_temp_12[28]}}, multiplier_mul_temp_12};
  assign multiplier_mul_temp_13 = delay_pipeline_16_im * coeff18;
  assign product18_im = {{3{multiplier_mul_temp_13[28]}}, multiplier_mul_temp_13};



  assign sum1_4_re = product19_re + product18_re;
  assign sum1_4_im = product19_im + product18_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_4_process
      if (rst_n == 1'b0) begin
        sum1_4_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_4_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_4_re_1 <= sum1_4_re;
          sum1_4_im_1 <= sum1_4_im;
        end
      end
    end



  assign sum2_2_re = sum1_3_re_1 + sum1_4_re_1;
  assign sum2_2_im = sum1_3_im_1 + sum1_4_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_5_process
      if (rst_n == 1'b0) begin
        sum2_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_2_re_1 <= sum2_2_re;
          sum2_2_im_1 <= sum2_2_im;
        end
      end
    end



  assign sum3_1_re = sum2_1_re_1 + sum2_2_re_1;
  assign sum3_1_im = sum2_1_im_1 + sum2_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_6_process
      if (rst_n == 1'b0) begin
        sum3_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum3_1_re_1 <= sum3_1_re;
          sum3_1_im_1 <= sum3_1_im;
        end
      end
    end



  assign delay_pipeline_15_re = delay_pipeline_re[15];

  assign delay_pipeline_15_im = delay_pipeline_im[15];

  assign coeff17 = 16'sb0000001010100111;



  assign multiplier_mul_temp_14 = delay_pipeline_15_re * coeff17;
  assign product17_re = {{3{multiplier_mul_temp_14[28]}}, multiplier_mul_temp_14};
  assign multiplier_mul_temp_15 = delay_pipeline_15_im * coeff17;
  assign product17_im = {{3{multiplier_mul_temp_15[28]}}, multiplier_mul_temp_15};



  assign delay_pipeline_14_re = delay_pipeline_re[14];

  assign delay_pipeline_14_im = delay_pipeline_im[14];

  assign coeff16 = 16'sb1111101111000100;



  assign multiplier_mul_temp_16 = delay_pipeline_14_re * coeff16;
  assign product16_re = {{3{multiplier_mul_temp_16[28]}}, multiplier_mul_temp_16};
  assign multiplier_mul_temp_17 = delay_pipeline_14_im * coeff16;
  assign product16_im = {{3{multiplier_mul_temp_17[28]}}, multiplier_mul_temp_17};



  assign sum1_5_re = product17_re + product16_re;
  assign sum1_5_im = product17_im + product16_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_7_process
      if (rst_n == 1'b0) begin
        sum1_5_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_5_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_5_re_1 <= sum1_5_re;
          sum1_5_im_1 <= sum1_5_im;
        end
      end
    end



  assign delay_pipeline_13_re = delay_pipeline_re[13];

  assign delay_pipeline_13_im = delay_pipeline_im[13];

  assign coeff15 = 16'sb0000011011110000;



  assign multiplier_mul_temp_18 = delay_pipeline_13_re * coeff15;
  assign product15_re = {{3{multiplier_mul_temp_18[28]}}, multiplier_mul_temp_18};
  assign multiplier_mul_temp_19 = delay_pipeline_13_im * coeff15;
  assign product15_im = {{3{multiplier_mul_temp_19[28]}}, multiplier_mul_temp_19};



  assign delay_pipeline_12_re = delay_pipeline_re[12];

  assign delay_pipeline_12_im = delay_pipeline_im[12];

  assign coeff14 = 16'sb1111001100101110;



  assign multiplier_mul_temp_20 = delay_pipeline_12_re * coeff14;
  assign product14_re = {{3{multiplier_mul_temp_20[28]}}, multiplier_mul_temp_20};
  assign multiplier_mul_temp_21 = delay_pipeline_12_im * coeff14;
  assign product14_im = {{3{multiplier_mul_temp_21[28]}}, multiplier_mul_temp_21};



  assign sum1_6_re = product15_re + product14_re;
  assign sum1_6_im = product15_im + product14_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_8_process
      if (rst_n == 1'b0) begin
        sum1_6_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_6_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_6_re_1 <= sum1_6_re;
          sum1_6_im_1 <= sum1_6_im;
        end
      end
    end



  assign sum2_3_re = sum1_5_re_1 + sum1_6_re_1;
  assign sum2_3_im = sum1_5_im_1 + sum1_6_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_9_process
      if (rst_n == 1'b0) begin
        sum2_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_3_re_1 <= sum2_3_re;
          sum2_3_im_1 <= sum2_3_im;
        end
      end
    end



  assign delay_pipeline_11_re = delay_pipeline_re[11];

  assign delay_pipeline_11_im = delay_pipeline_im[11];

  assign coeff13 = 16'sb0010100001111100;



  assign multiplier_mul_temp_22 = delay_pipeline_11_re * coeff13;
  assign product13_re = {{3{multiplier_mul_temp_22[28]}}, multiplier_mul_temp_22};
  assign multiplier_mul_temp_23 = delay_pipeline_11_im * coeff13;
  assign product13_im = {{3{multiplier_mul_temp_23[28]}}, multiplier_mul_temp_23};



  assign delay_pipeline_10_re = delay_pipeline_re[10];

  assign delay_pipeline_10_im = delay_pipeline_im[10];

  assign coeff12 = 16'sb0010100001111100;



  assign multiplier_mul_temp_24 = delay_pipeline_10_re * coeff12;
  assign product12_re = {{3{multiplier_mul_temp_24[28]}}, multiplier_mul_temp_24};
  assign multiplier_mul_temp_25 = delay_pipeline_10_im * coeff12;
  assign product12_im = {{3{multiplier_mul_temp_25[28]}}, multiplier_mul_temp_25};



  assign sum1_7_re = product13_re + product12_re;
  assign sum1_7_im = product13_im + product12_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_10_process
      if (rst_n == 1'b0) begin
        sum1_7_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_7_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_7_re_1 <= sum1_7_re;
          sum1_7_im_1 <= sum1_7_im;
        end
      end
    end



  assign delay_pipeline_9_re = delay_pipeline_re[9];

  assign delay_pipeline_9_im = delay_pipeline_im[9];

  assign coeff11 = 16'sb1111001100101110;



  assign multiplier_mul_temp_26 = delay_pipeline_9_re * coeff11;
  assign product11_re = {{3{multiplier_mul_temp_26[28]}}, multiplier_mul_temp_26};
  assign multiplier_mul_temp_27 = delay_pipeline_9_im * coeff11;
  assign product11_im = {{3{multiplier_mul_temp_27[28]}}, multiplier_mul_temp_27};



  assign delay_pipeline_8_re = delay_pipeline_re[8];

  assign delay_pipeline_8_im = delay_pipeline_im[8];

  assign coeff10 = 16'sb0000011011110000;



  assign multiplier_mul_temp_28 = delay_pipeline_8_re * coeff10;
  assign product10_re = {{3{multiplier_mul_temp_28[28]}}, multiplier_mul_temp_28};
  assign multiplier_mul_temp_29 = delay_pipeline_8_im * coeff10;
  assign product10_im = {{3{multiplier_mul_temp_29[28]}}, multiplier_mul_temp_29};



  assign sum1_8_re = product11_re + product10_re;
  assign sum1_8_im = product11_im + product10_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_11_process
      if (rst_n == 1'b0) begin
        sum1_8_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_8_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_8_re_1 <= sum1_8_re;
          sum1_8_im_1 <= sum1_8_im;
        end
      end
    end



  assign sum2_4_re = sum1_7_re_1 + sum1_8_re_1;
  assign sum2_4_im = sum1_7_im_1 + sum1_8_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_12_process
      if (rst_n == 1'b0) begin
        sum2_4_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_4_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_4_re_1 <= sum2_4_re;
          sum2_4_im_1 <= sum2_4_im;
        end
      end
    end



  assign sum3_2_re = sum2_3_re_1 + sum2_4_re_1;
  assign sum3_2_im = sum2_3_im_1 + sum2_4_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_13_process
      if (rst_n == 1'b0) begin
        sum3_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum3_2_re_1 <= sum3_2_re;
          sum3_2_im_1 <= sum3_2_im;
        end
      end
    end



  assign sum4_1_re = sum3_1_re_1 + sum3_2_re_1;
  assign sum4_1_im = sum3_1_im_1 + sum3_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_14_process
      if (rst_n == 1'b0) begin
        sum4_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum4_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum4_1_re_1 <= sum4_1_re;
          sum4_1_im_1 <= sum4_1_im;
        end
      end
    end



  assign delay_pipeline_7_re = delay_pipeline_re[7];

  assign delay_pipeline_7_im = delay_pipeline_im[7];

  assign coeff9 = 16'sb1111101111000100;



  assign multiplier_mul_temp_30 = delay_pipeline_7_re * coeff9;
  assign product9_re = {{3{multiplier_mul_temp_30[28]}}, multiplier_mul_temp_30};
  assign multiplier_mul_temp_31 = delay_pipeline_7_im * coeff9;
  assign product9_im = {{3{multiplier_mul_temp_31[28]}}, multiplier_mul_temp_31};



  assign delay_pipeline_6_re = delay_pipeline_re[6];

  assign delay_pipeline_6_im = delay_pipeline_im[6];

  assign coeff8 = 16'sb0000001010100111;



  assign multiplier_mul_temp_32 = delay_pipeline_6_re * coeff8;
  assign product8_re = {{3{multiplier_mul_temp_32[28]}}, multiplier_mul_temp_32};
  assign multiplier_mul_temp_33 = delay_pipeline_6_im * coeff8;
  assign product8_im = {{3{multiplier_mul_temp_33[28]}}, multiplier_mul_temp_33};



  assign sum1_9_re = product9_re + product8_re;
  assign sum1_9_im = product9_im + product8_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_15_process
      if (rst_n == 1'b0) begin
        sum1_9_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_9_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_9_re_1 <= sum1_9_re;
          sum1_9_im_1 <= sum1_9_im;
        end
      end
    end



  assign delay_pipeline_5_re = delay_pipeline_re[5];

  assign delay_pipeline_5_im = delay_pipeline_im[5];

  assign coeff7 = 16'sb1111111001011011;



  assign multiplier_mul_temp_34 = delay_pipeline_5_re * coeff7;
  assign product7_re = {{3{multiplier_mul_temp_34[28]}}, multiplier_mul_temp_34};
  assign multiplier_mul_temp_35 = delay_pipeline_5_im * coeff7;
  assign product7_im = {{3{multiplier_mul_temp_35[28]}}, multiplier_mul_temp_35};



  assign delay_pipeline_4_re = delay_pipeline_re[4];

  assign delay_pipeline_4_im = delay_pipeline_im[4];

  assign coeff6 = 16'sb0000000011111011;



  assign multiplier_mul_temp_36 = delay_pipeline_4_re * coeff6;
  assign product6_re = {{3{multiplier_mul_temp_36[28]}}, multiplier_mul_temp_36};
  assign multiplier_mul_temp_37 = delay_pipeline_4_im * coeff6;
  assign product6_im = {{3{multiplier_mul_temp_37[28]}}, multiplier_mul_temp_37};



  assign sum1_10_re = product7_re + product6_re;
  assign sum1_10_im = product7_im + product6_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_16_process
      if (rst_n == 1'b0) begin
        sum1_10_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_10_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_10_re_1 <= sum1_10_re;
          sum1_10_im_1 <= sum1_10_im;
        end
      end
    end



  assign sum2_5_re = sum1_9_re_1 + sum1_10_re_1;
  assign sum2_5_im = sum1_9_im_1 + sum1_10_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_17_process
      if (rst_n == 1'b0) begin
        sum2_5_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_5_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_5_re_1 <= sum2_5_re;
          sum2_5_im_1 <= sum2_5_im;
        end
      end
    end



  assign delay_pipeline_3_re = delay_pipeline_re[3];

  assign delay_pipeline_3_im = delay_pipeline_im[3];

  assign coeff5 = 16'sb1111111101110011;



  assign multiplier_mul_temp_38 = delay_pipeline_3_re * coeff5;
  assign product5_re = {{3{multiplier_mul_temp_38[28]}}, multiplier_mul_temp_38};
  assign multiplier_mul_temp_39 = delay_pipeline_3_im * coeff5;
  assign product5_im = {{3{multiplier_mul_temp_39[28]}}, multiplier_mul_temp_39};



  assign delay_pipeline_2_re = delay_pipeline_re[2];

  assign delay_pipeline_2_im = delay_pipeline_im[2];

  assign coeff4 = 16'sb0000000001001001;



  assign multiplier_mul_temp_40 = delay_pipeline_2_re * coeff4;
  assign product4_re = {{3{multiplier_mul_temp_40[28]}}, multiplier_mul_temp_40};
  assign multiplier_mul_temp_41 = delay_pipeline_2_im * coeff4;
  assign product4_im = {{3{multiplier_mul_temp_41[28]}}, multiplier_mul_temp_41};



  assign sum1_11_re = product5_re + product4_re;
  assign sum1_11_im = product5_im + product4_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_18_process
      if (rst_n == 1'b0) begin
        sum1_11_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_11_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_11_re_1 <= sum1_11_re;
          sum1_11_im_1 <= sum1_11_im;
        end
      end
    end



  assign delay_pipeline_1_re = delay_pipeline_re[1];

  assign delay_pipeline_1_im = delay_pipeline_im[1];

  assign coeff3 = 16'sb1111111111011111;



  assign multiplier_mul_temp_42 = delay_pipeline_1_re * coeff3;
  assign product3_re = {{3{multiplier_mul_temp_42[28]}}, multiplier_mul_temp_42};
  assign multiplier_mul_temp_43 = delay_pipeline_1_im * coeff3;
  assign product3_im = {{3{multiplier_mul_temp_43[28]}}, multiplier_mul_temp_43};



  assign delay_pipeline_0_re = delay_pipeline_re[0];

  assign delay_pipeline_0_im = delay_pipeline_im[0];

  assign coeff2 = 16'sb0000000000001101;



  assign multiplier_mul_temp_44 = delay_pipeline_0_re * coeff2;
  assign product2_re = {{3{multiplier_mul_temp_44[28]}}, multiplier_mul_temp_44};
  assign multiplier_mul_temp_45 = delay_pipeline_0_im * coeff2;
  assign product2_im = {{3{multiplier_mul_temp_45[28]}}, multiplier_mul_temp_45};



  assign sum1_12_re = product3_re + product2_re;
  assign sum1_12_im = product3_im + product2_im;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_19_process
      if (rst_n == 1'b0) begin
        sum1_12_re_1 <= 32'sb00000000000000000000000000000000;
        sum1_12_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum1_12_re_1 <= sum1_12_re;
          sum1_12_im_1 <= sum1_12_im;
        end
      end
    end



  assign sum2_6_re = sum1_11_re_1 + sum1_12_re_1;
  assign sum2_6_im = sum1_11_im_1 + sum1_12_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_20_process
      if (rst_n == 1'b0) begin
        sum2_6_re_1 <= 32'sb00000000000000000000000000000000;
        sum2_6_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum2_6_re_1 <= sum2_6_re;
          sum2_6_im_1 <= sum2_6_im;
        end
      end
    end



  assign sum3_3_re = sum2_5_re_1 + sum2_6_re_1;
  assign sum3_3_im = sum2_5_im_1 + sum2_6_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_21_process
      if (rst_n == 1'b0) begin
        sum3_3_re_1 <= 32'sb00000000000000000000000000000000;
        sum3_3_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum3_3_re_1 <= sum3_3_re;
          sum3_3_im_1 <= sum3_3_im;
        end
      end
    end



  assign coeff1 = 16'sb1111111111111101;



  assign multiplier_mul_temp_46 = in_re * coeff1;
  assign product1_re = {{3{multiplier_mul_temp_46[28]}}, multiplier_mul_temp_46};
  assign multiplier_mul_temp_47 = in_im * coeff1;
  assign product1_im = {{3{multiplier_mul_temp_47[28]}}, multiplier_mul_temp_47};



  always @(posedge clk or negedge rst_n)
    begin : multiplier_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        product1_re_1 <= 32'sb00000000000000000000000000000000;
        product1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          product1_re_1 <= product1_re;
          product1_im_1 <= product1_im;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : multiplier_out_buff_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        product1_re_2 <= 32'sb00000000000000000000000000000000;
        product1_im_2 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          product1_re_2 <= product1_re_1;
          product1_im_2 <= product1_im_1;
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : multiplier_out_buff_out_buff_out_buff_out_pipe_process
      if (rst_n == 1'b0) begin
        product1_re_3 <= 32'sb00000000000000000000000000000000;
        product1_im_3 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          product1_re_3 <= product1_re_2;
          product1_im_3 <= product1_im_2;
        end
      end
    end



  assign sum4_2_re = sum3_3_re_1 + product1_re_3;
  assign sum4_2_im = sum3_3_im_1 + product1_im_3;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_22_process
      if (rst_n == 1'b0) begin
        sum4_2_re_1 <= 32'sb00000000000000000000000000000000;
        sum4_2_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum4_2_re_1 <= sum4_2_re;
          sum4_2_im_1 <= sum4_2_im;
        end
      end
    end



  assign sum5_1_re = sum4_1_re_1 + sum4_2_re_1;
  assign sum5_1_im = sum4_1_im_1 + sum4_2_im_1;



  always @(posedge clk or negedge rst_n)
    begin : adder_out_buff_out_pipe_23_process
      if (rst_n == 1'b0) begin
        sum5_1_re_1 <= 32'sb00000000000000000000000000000000;
        sum5_1_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (en) begin
          sum5_1_re_1 <= sum5_1_re;
          sum5_1_im_1 <= sum5_1_im;
        end
      end
    end



  assign output_typeconvert_re = sum5_1_re_1[26:11];
  assign output_typeconvert_im = sum5_1_im_1[26:11];



  assign out_re = output_typeconvert_re;

  assign out_im = output_typeconvert_im;

endmodule  // fir_int_p11

