// -------------------------------------------------------------
// 
// File Name: hdlsrc\scpa_int_fir\pp_int_x4_tc.v
// Created: 2025-01-19 09:27:40
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_int_x4_tc
// Source Path: pp_int_x4_tc
// Hierarchy Level: 1
// 
// Master clock enable input: en
// 
// enb         : identical to en
// enb_1_1_1   : identical to en
// enb_1_4_0   : 4x slower than clk with last phase
// enb_1_4_1   : 4x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1ps / 1ps

module pp_int_x4_tc
          (clk,
           rst_n,
           en,
           enb,
           enb_1_1_1,
           enb_1_4_0,
           enb_1_4_1);


  input   clk;
  input   rst_n;
  input   en;
  output  enb;
  output  enb_1_1_1;
  output  enb_1_4_0;
  output  enb_1_4_1;


  reg [1:0] count4;  // ufix2
  wire comp_0_tmp;
  wire phase_0_tmp;
  reg  phase_0;
  wire enb_1_4_0_1;
  wire comp_1_tmp;
  wire phase_1_tmp;
  reg  phase_1;
  wire enb_1_4_1_1;


  assign enb = en;

  assign enb_1_1_1 = en;

  // Count limited, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  //  count to value  = 3
  always @(posedge clk or negedge rst_n)
    begin : counter_4_process
      if (rst_n == 1'b0) begin
        count4 <= 2'b01;
      end
      else begin
        if (en) begin
          count4 <= count4 + 2'b01;
        end
      end
    end



  assign comp_0_tmp = count4 == 2'b11;



  assign phase_0_tmp = comp_0_tmp & en;



  always @(posedge clk or negedge rst_n)
    begin : phase_delay_process
      if (rst_n == 1'b0) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (en) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end



  assign enb_1_4_0_1 = phase_0 & en;



  assign enb_1_4_0 = enb_1_4_0_1;

  assign comp_1_tmp = count4 == 2'b00;



  assign phase_1_tmp = comp_1_tmp & en;



  always @(posedge clk or negedge rst_n)
    begin : phase_delay_1_process
      if (rst_n == 1'b0) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (en) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end



  assign enb_1_4_1_1 = phase_1 & en;



  assign enb_1_4_1 = enb_1_4_1_1;

endmodule  // pp_int_x4_tc

