
//input ports
add mapped point clk clk -type PI PI
add mapped point reset reset -type PI PI
add mapped point enb enb -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[15] Discrete_FIR_Filter_1_in_re[15] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[14] Discrete_FIR_Filter_1_in_re[14] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[13] Discrete_FIR_Filter_1_in_re[13] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[12] Discrete_FIR_Filter_1_in_re[12] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[11] Discrete_FIR_Filter_1_in_re[11] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[10] Discrete_FIR_Filter_1_in_re[10] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[9] Discrete_FIR_Filter_1_in_re[9] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[8] Discrete_FIR_Filter_1_in_re[8] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[7] Discrete_FIR_Filter_1_in_re[7] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[6] Discrete_FIR_Filter_1_in_re[6] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[5] Discrete_FIR_Filter_1_in_re[5] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[4] Discrete_FIR_Filter_1_in_re[4] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[3] Discrete_FIR_Filter_1_in_re[3] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[2] Discrete_FIR_Filter_1_in_re[2] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[1] Discrete_FIR_Filter_1_in_re[1] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_re[0] Discrete_FIR_Filter_1_in_re[0] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[15] Discrete_FIR_Filter_1_in_im[15] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[14] Discrete_FIR_Filter_1_in_im[14] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[13] Discrete_FIR_Filter_1_in_im[13] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[12] Discrete_FIR_Filter_1_in_im[12] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[11] Discrete_FIR_Filter_1_in_im[11] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[10] Discrete_FIR_Filter_1_in_im[10] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[9] Discrete_FIR_Filter_1_in_im[9] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[8] Discrete_FIR_Filter_1_in_im[8] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[7] Discrete_FIR_Filter_1_in_im[7] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[6] Discrete_FIR_Filter_1_in_im[6] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[5] Discrete_FIR_Filter_1_in_im[5] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[4] Discrete_FIR_Filter_1_in_im[4] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[3] Discrete_FIR_Filter_1_in_im[3] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[2] Discrete_FIR_Filter_1_in_im[2] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[1] Discrete_FIR_Filter_1_in_im[1] -type PI PI
add mapped point Discrete_FIR_Filter_1_in_im[0] Discrete_FIR_Filter_1_in_im[0] -type PI PI

//output ports
add mapped point Discrete_FIR_Filter_1_out_re[15] Discrete_FIR_Filter_1_out_re[15] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[14] Discrete_FIR_Filter_1_out_re[14] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[13] Discrete_FIR_Filter_1_out_re[13] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[12] Discrete_FIR_Filter_1_out_re[12] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[11] Discrete_FIR_Filter_1_out_re[11] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[10] Discrete_FIR_Filter_1_out_re[10] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[9] Discrete_FIR_Filter_1_out_re[9] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[8] Discrete_FIR_Filter_1_out_re[8] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[7] Discrete_FIR_Filter_1_out_re[7] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[6] Discrete_FIR_Filter_1_out_re[6] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[5] Discrete_FIR_Filter_1_out_re[5] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[4] Discrete_FIR_Filter_1_out_re[4] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[3] Discrete_FIR_Filter_1_out_re[3] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[2] Discrete_FIR_Filter_1_out_re[2] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[1] Discrete_FIR_Filter_1_out_re[1] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_re[0] Discrete_FIR_Filter_1_out_re[0] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[15] Discrete_FIR_Filter_1_out_im[15] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[14] Discrete_FIR_Filter_1_out_im[14] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[13] Discrete_FIR_Filter_1_out_im[13] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[12] Discrete_FIR_Filter_1_out_im[12] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[11] Discrete_FIR_Filter_1_out_im[11] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[10] Discrete_FIR_Filter_1_out_im[10] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[9] Discrete_FIR_Filter_1_out_im[9] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[8] Discrete_FIR_Filter_1_out_im[8] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[7] Discrete_FIR_Filter_1_out_im[7] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[6] Discrete_FIR_Filter_1_out_im[6] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[5] Discrete_FIR_Filter_1_out_im[5] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[4] Discrete_FIR_Filter_1_out_im[4] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[3] Discrete_FIR_Filter_1_out_im[3] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[2] Discrete_FIR_Filter_1_out_im[2] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[1] Discrete_FIR_Filter_1_out_im[1] -type PO PO
add mapped point Discrete_FIR_Filter_1_out_im[0] Discrete_FIR_Filter_1_out_im[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point tapped_delay_reg_im[0][0]/q tapped_delay_reg_im_reg[0][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][1]/q tapped_delay_reg_im_reg[0][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][2]/q tapped_delay_reg_im_reg[0][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][3]/q tapped_delay_reg_im_reg[0][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][4]/q tapped_delay_reg_im_reg[0][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][5]/q tapped_delay_reg_im_reg[0][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][6]/q tapped_delay_reg_im_reg[0][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][7]/q tapped_delay_reg_im_reg[0][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][8]/q tapped_delay_reg_im_reg[0][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][9]/q tapped_delay_reg_im_reg[0][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][10]/q tapped_delay_reg_im_reg[0][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][11]/q tapped_delay_reg_im_reg[0][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][12]/q tapped_delay_reg_im_reg[0][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][13]/q tapped_delay_reg_im_reg[0][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][14]/q tapped_delay_reg_im_reg[0][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[0][15]/q tapped_delay_reg_im_reg[0][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][0]/q tapped_delay_reg_im_reg[1][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][1]/q tapped_delay_reg_im_reg[1][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[1][2]/q tapped_delay_reg_im_reg[1][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][3]/q tapped_delay_reg_im_reg[1][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][4]/q tapped_delay_reg_im_reg[1][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][5]/q tapped_delay_reg_im_reg[1][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][6]/q tapped_delay_reg_im_reg[1][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][7]/q tapped_delay_reg_im_reg[1][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][8]/q tapped_delay_reg_im_reg[1][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][9]/q tapped_delay_reg_im_reg[1][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][10]/q tapped_delay_reg_im_reg[1][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][11]/q tapped_delay_reg_im_reg[1][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][12]/q tapped_delay_reg_im_reg[1][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][13]/q tapped_delay_reg_im_reg[1][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][14]/q tapped_delay_reg_im_reg[1][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[1][15]/q tapped_delay_reg_im_reg[1][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][0]/q tapped_delay_reg_im_reg[2][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[2][1]/q tapped_delay_reg_im_reg[2][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][2]/q tapped_delay_reg_im_reg[2][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][3]/q tapped_delay_reg_im_reg[2][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][4]/q tapped_delay_reg_im_reg[2][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][5]/q tapped_delay_reg_im_reg[2][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][6]/q tapped_delay_reg_im_reg[2][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][7]/q tapped_delay_reg_im_reg[2][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][8]/q tapped_delay_reg_im_reg[2][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[2][9]/q tapped_delay_reg_im_reg[2][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[2][10]/q tapped_delay_reg_im_reg[2][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[2][11]/q tapped_delay_reg_im_reg[2][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[2][12]/q tapped_delay_reg_im_reg[2][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][13]/q tapped_delay_reg_im_reg[2][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][14]/q tapped_delay_reg_im_reg[2][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[2][15]/q tapped_delay_reg_im_reg[2][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][0]/q tapped_delay_reg_im_reg[3][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][1]/q tapped_delay_reg_im_reg[3][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][2]/q tapped_delay_reg_im_reg[3][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][3]/q tapped_delay_reg_im_reg[3][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][4]/q tapped_delay_reg_im_reg[3][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][5]/q tapped_delay_reg_im_reg[3][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][6]/q tapped_delay_reg_im_reg[3][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][7]/q tapped_delay_reg_im_reg[3][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[3][8]/q tapped_delay_reg_im_reg[3][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[3][9]/q tapped_delay_reg_im_reg[3][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[3][10]/q tapped_delay_reg_im_reg[3][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[3][11]/q tapped_delay_reg_im_reg[3][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][12]/q tapped_delay_reg_im_reg[3][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][13]/q tapped_delay_reg_im_reg[3][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][14]/q tapped_delay_reg_im_reg[3][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[3][15]/q tapped_delay_reg_im_reg[3][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[4][0]/q tapped_delay_reg_im_reg[4][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][1]/q tapped_delay_reg_im_reg[4][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][2]/q tapped_delay_reg_im_reg[4][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][3]/q tapped_delay_reg_im_reg[4][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][4]/q tapped_delay_reg_im_reg[4][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][5]/q tapped_delay_reg_im_reg[4][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][6]/q tapped_delay_reg_im_reg[4][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][7]/q tapped_delay_reg_im_reg[4][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][8]/q tapped_delay_reg_im_reg[4][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][9]/q tapped_delay_reg_im_reg[4][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][10]/q tapped_delay_reg_im_reg[4][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][11]/q tapped_delay_reg_im_reg[4][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[4][12]/q tapped_delay_reg_im_reg[4][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][13]/q tapped_delay_reg_im_reg[4][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][14]/q tapped_delay_reg_im_reg[4][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[4][15]/q tapped_delay_reg_im_reg[4][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][0]/q tapped_delay_reg_im_reg[5][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[5][1]/q tapped_delay_reg_im_reg[5][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[5][2]/q tapped_delay_reg_im_reg[5][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[5][3]/q tapped_delay_reg_im_reg[5][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[5][4]/q tapped_delay_reg_im_reg[5][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[5][5]/q tapped_delay_reg_im_reg[5][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[5][6]/q tapped_delay_reg_im_reg[5][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[5][7]/q tapped_delay_reg_im_reg[5][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][8]/q tapped_delay_reg_im_reg[5][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][9]/q tapped_delay_reg_im_reg[5][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][10]/q tapped_delay_reg_im_reg[5][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][11]/q tapped_delay_reg_im_reg[5][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][12]/q tapped_delay_reg_im_reg[5][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][13]/q tapped_delay_reg_im_reg[5][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][14]/q tapped_delay_reg_im_reg[5][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[5][15]/q tapped_delay_reg_im_reg[5][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[6][0]/q tapped_delay_reg_im_reg[6][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[6][1]/q tapped_delay_reg_im_reg[6][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][2]/q tapped_delay_reg_im_reg[6][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][3]/q tapped_delay_reg_im_reg[6][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][4]/q tapped_delay_reg_im_reg[6][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][5]/q tapped_delay_reg_im_reg[6][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][6]/q tapped_delay_reg_im_reg[6][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][7]/q tapped_delay_reg_im_reg[6][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][8]/q tapped_delay_reg_im_reg[6][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][9]/q tapped_delay_reg_im_reg[6][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][10]/q tapped_delay_reg_im_reg[6][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][11]/q tapped_delay_reg_im_reg[6][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][12]/q tapped_delay_reg_im_reg[6][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][13]/q tapped_delay_reg_im_reg[6][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][14]/q tapped_delay_reg_im_reg[6][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[6][15]/q tapped_delay_reg_im_reg[6][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][0]/q tapped_delay_reg_im_reg[7][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[7][1]/q tapped_delay_reg_im_reg[7][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][2]/q tapped_delay_reg_im_reg[7][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][3]/q tapped_delay_reg_im_reg[7][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][4]/q tapped_delay_reg_im_reg[7][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][5]/q tapped_delay_reg_im_reg[7][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][6]/q tapped_delay_reg_im_reg[7][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][7]/q tapped_delay_reg_im_reg[7][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][8]/q tapped_delay_reg_im_reg[7][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][9]/q tapped_delay_reg_im_reg[7][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][10]/q tapped_delay_reg_im_reg[7][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][11]/q tapped_delay_reg_im_reg[7][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][12]/q tapped_delay_reg_im_reg[7][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][13]/q tapped_delay_reg_im_reg[7][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][14]/q tapped_delay_reg_im_reg[7][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[7][15]/q tapped_delay_reg_im_reg[7][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[8][0]/q tapped_delay_reg_im_reg[8][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][1]/q tapped_delay_reg_im_reg[8][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][2]/q tapped_delay_reg_im_reg[8][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][3]/q tapped_delay_reg_im_reg[8][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][4]/q tapped_delay_reg_im_reg[8][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][5]/q tapped_delay_reg_im_reg[8][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][6]/q tapped_delay_reg_im_reg[8][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][7]/q tapped_delay_reg_im_reg[8][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][8]/q tapped_delay_reg_im_reg[8][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][9]/q tapped_delay_reg_im_reg[8][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][10]/q tapped_delay_reg_im_reg[8][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][11]/q tapped_delay_reg_im_reg[8][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][12]/q tapped_delay_reg_im_reg[8][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][13]/q tapped_delay_reg_im_reg[8][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][14]/q tapped_delay_reg_im_reg[8][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[8][15]/q tapped_delay_reg_im_reg[8][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[9][0]/q tapped_delay_reg_im_reg[9][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][1]/q tapped_delay_reg_im_reg[9][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][2]/q tapped_delay_reg_im_reg[9][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][3]/q tapped_delay_reg_im_reg[9][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][4]/q tapped_delay_reg_im_reg[9][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][5]/q tapped_delay_reg_im_reg[9][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][6]/q tapped_delay_reg_im_reg[9][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][7]/q tapped_delay_reg_im_reg[9][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][8]/q tapped_delay_reg_im_reg[9][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][9]/q tapped_delay_reg_im_reg[9][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][10]/q tapped_delay_reg_im_reg[9][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][11]/q tapped_delay_reg_im_reg[9][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][12]/q tapped_delay_reg_im_reg[9][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][13]/q tapped_delay_reg_im_reg[9][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][14]/q tapped_delay_reg_im_reg[9][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[9][15]/q tapped_delay_reg_im_reg[9][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][0]/q tapped_delay_reg_im_reg[10][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][1]/q tapped_delay_reg_im_reg[10][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][2]/q tapped_delay_reg_im_reg[10][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][3]/q tapped_delay_reg_im_reg[10][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][4]/q tapped_delay_reg_im_reg[10][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][5]/q tapped_delay_reg_im_reg[10][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][6]/q tapped_delay_reg_im_reg[10][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][7]/q tapped_delay_reg_im_reg[10][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[10][8]/q tapped_delay_reg_im_reg[10][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][9]/q tapped_delay_reg_im_reg[10][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][10]/q tapped_delay_reg_im_reg[10][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][11]/q tapped_delay_reg_im_reg[10][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][12]/q tapped_delay_reg_im_reg[10][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][13]/q tapped_delay_reg_im_reg[10][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][14]/q tapped_delay_reg_im_reg[10][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[10][15]/q tapped_delay_reg_im_reg[10][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[11][0]/q tapped_delay_reg_im_reg[11][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][1]/q tapped_delay_reg_im_reg[11][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][2]/q tapped_delay_reg_im_reg[11][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][3]/q tapped_delay_reg_im_reg[11][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][4]/q tapped_delay_reg_im_reg[11][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][5]/q tapped_delay_reg_im_reg[11][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][6]/q tapped_delay_reg_im_reg[11][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][7]/q tapped_delay_reg_im_reg[11][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][8]/q tapped_delay_reg_im_reg[11][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][9]/q tapped_delay_reg_im_reg[11][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][10]/q tapped_delay_reg_im_reg[11][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][11]/q tapped_delay_reg_im_reg[11][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][12]/q tapped_delay_reg_im_reg[11][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][13]/q tapped_delay_reg_im_reg[11][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][14]/q tapped_delay_reg_im_reg[11][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[11][15]/q tapped_delay_reg_im_reg[11][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][0]/q tapped_delay_reg_im_reg[12][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][1]/q tapped_delay_reg_im_reg[12][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[12][2]/q tapped_delay_reg_im_reg[12][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][3]/q tapped_delay_reg_im_reg[12][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][4]/q tapped_delay_reg_im_reg[12][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[12][5]/q tapped_delay_reg_im_reg[12][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][6]/q tapped_delay_reg_im_reg[12][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][7]/q tapped_delay_reg_im_reg[12][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][8]/q tapped_delay_reg_im_reg[12][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][9]/q tapped_delay_reg_im_reg[12][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[12][10]/q tapped_delay_reg_im_reg[12][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[12][11]/q tapped_delay_reg_im_reg[12][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[12][12]/q tapped_delay_reg_im_reg[12][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][13]/q tapped_delay_reg_im_reg[12][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][14]/q tapped_delay_reg_im_reg[12][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[12][15]/q tapped_delay_reg_im_reg[12][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][0]/q tapped_delay_reg_im_reg[13][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][1]/q tapped_delay_reg_im_reg[13][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][2]/q tapped_delay_reg_im_reg[13][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][3]/q tapped_delay_reg_im_reg[13][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][4]/q tapped_delay_reg_im_reg[13][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][5]/q tapped_delay_reg_im_reg[13][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[13][6]/q tapped_delay_reg_im_reg[13][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][7]/q tapped_delay_reg_im_reg[13][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][8]/q tapped_delay_reg_im_reg[13][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[13][9]/q tapped_delay_reg_im_reg[13][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][10]/q tapped_delay_reg_im_reg[13][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][11]/q tapped_delay_reg_im_reg[13][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][12]/q tapped_delay_reg_im_reg[13][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][13]/q tapped_delay_reg_im_reg[13][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][14]/q tapped_delay_reg_im_reg[13][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[13][15]/q tapped_delay_reg_im_reg[13][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][0]/q tapped_delay_reg_im_reg[14][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[14][1]/q tapped_delay_reg_im_reg[14][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[14][2]/q tapped_delay_reg_im_reg[14][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[14][3]/q tapped_delay_reg_im_reg[14][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[14][4]/q tapped_delay_reg_im_reg[14][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][5]/q tapped_delay_reg_im_reg[14][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][6]/q tapped_delay_reg_im_reg[14][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][7]/q tapped_delay_reg_im_reg[14][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][8]/q tapped_delay_reg_im_reg[14][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][9]/q tapped_delay_reg_im_reg[14][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][10]/q tapped_delay_reg_im_reg[14][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][11]/q tapped_delay_reg_im_reg[14][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][12]/q tapped_delay_reg_im_reg[14][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][13]/q tapped_delay_reg_im_reg[14][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][14]/q tapped_delay_reg_im_reg[14][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[14][15]/q tapped_delay_reg_im_reg[14][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][0]/q tapped_delay_reg_im_reg[15][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][1]/q tapped_delay_reg_im_reg[15][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][2]/q tapped_delay_reg_im_reg[15][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][3]/q tapped_delay_reg_im_reg[15][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][4]/q tapped_delay_reg_im_reg[15][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[15][5]/q tapped_delay_reg_im_reg[15][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[15][6]/q tapped_delay_reg_im_reg[15][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][7]/q tapped_delay_reg_im_reg[15][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][8]/q tapped_delay_reg_im_reg[15][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][9]/q tapped_delay_reg_im_reg[15][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][10]/q tapped_delay_reg_im_reg[15][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[15][11]/q tapped_delay_reg_im_reg[15][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][12]/q tapped_delay_reg_im_reg[15][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][13]/q tapped_delay_reg_im_reg[15][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][14]/q tapped_delay_reg_im_reg[15][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[15][15]/q tapped_delay_reg_im_reg[15][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][0]/q tapped_delay_reg_im_reg[16][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[16][1]/q tapped_delay_reg_im_reg[16][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][2]/q tapped_delay_reg_im_reg[16][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][3]/q tapped_delay_reg_im_reg[16][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][4]/q tapped_delay_reg_im_reg[16][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][5]/q tapped_delay_reg_im_reg[16][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[16][6]/q tapped_delay_reg_im_reg[16][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][7]/q tapped_delay_reg_im_reg[16][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][8]/q tapped_delay_reg_im_reg[16][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][9]/q tapped_delay_reg_im_reg[16][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][10]/q tapped_delay_reg_im_reg[16][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][11]/q tapped_delay_reg_im_reg[16][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][12]/q tapped_delay_reg_im_reg[16][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][13]/q tapped_delay_reg_im_reg[16][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][14]/q tapped_delay_reg_im_reg[16][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[16][15]/q tapped_delay_reg_im_reg[16][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][0]/q tapped_delay_reg_im_reg[17][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[17][1]/q tapped_delay_reg_im_reg[17][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][2]/q tapped_delay_reg_im_reg[17][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[17][3]/q tapped_delay_reg_im_reg[17][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][4]/q tapped_delay_reg_im_reg[17][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[17][5]/q tapped_delay_reg_im_reg[17][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][6]/q tapped_delay_reg_im_reg[17][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][7]/q tapped_delay_reg_im_reg[17][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][8]/q tapped_delay_reg_im_reg[17][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[17][9]/q tapped_delay_reg_im_reg[17][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][10]/q tapped_delay_reg_im_reg[17][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][11]/q tapped_delay_reg_im_reg[17][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][12]/q tapped_delay_reg_im_reg[17][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][13]/q tapped_delay_reg_im_reg[17][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[17][14]/q tapped_delay_reg_im_reg[17][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[17][15]/q tapped_delay_reg_im_reg[17][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[18][0]/q tapped_delay_reg_im_reg[18][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][1]/q tapped_delay_reg_im_reg[18][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][2]/q tapped_delay_reg_im_reg[18][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][3]/q tapped_delay_reg_im_reg[18][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][4]/q tapped_delay_reg_im_reg[18][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][5]/q tapped_delay_reg_im_reg[18][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][6]/q tapped_delay_reg_im_reg[18][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][7]/q tapped_delay_reg_im_reg[18][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][8]/q tapped_delay_reg_im_reg[18][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][9]/q tapped_delay_reg_im_reg[18][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][10]/q tapped_delay_reg_im_reg[18][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][11]/q tapped_delay_reg_im_reg[18][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][12]/q tapped_delay_reg_im_reg[18][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][13]/q tapped_delay_reg_im_reg[18][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][14]/q tapped_delay_reg_im_reg[18][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[18][15]/q tapped_delay_reg_im_reg[18][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][0]/q tapped_delay_reg_im_reg[19][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[19][1]/q tapped_delay_reg_im_reg[19][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][2]/q tapped_delay_reg_im_reg[19][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][3]/q tapped_delay_reg_im_reg[19][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][4]/q tapped_delay_reg_im_reg[19][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][5]/q tapped_delay_reg_im_reg[19][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][6]/q tapped_delay_reg_im_reg[19][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][7]/q tapped_delay_reg_im_reg[19][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][8]/q tapped_delay_reg_im_reg[19][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][9]/q tapped_delay_reg_im_reg[19][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][10]/q tapped_delay_reg_im_reg[19][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][11]/q tapped_delay_reg_im_reg[19][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][12]/q tapped_delay_reg_im_reg[19][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[19][13]/q tapped_delay_reg_im_reg[19][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][14]/q tapped_delay_reg_im_reg[19][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[19][15]/q tapped_delay_reg_im_reg[19][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[20][0]/q tapped_delay_reg_im_reg[20][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[20][1]/q tapped_delay_reg_im_reg[20][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][2]/q tapped_delay_reg_im_reg[20][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[20][3]/q tapped_delay_reg_im_reg[20][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[20][4]/q tapped_delay_reg_im_reg[20][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][5]/q tapped_delay_reg_im_reg[20][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][6]/q tapped_delay_reg_im_reg[20][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][7]/q tapped_delay_reg_im_reg[20][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][8]/q tapped_delay_reg_im_reg[20][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][9]/q tapped_delay_reg_im_reg[20][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][10]/q tapped_delay_reg_im_reg[20][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[20][11]/q tapped_delay_reg_im_reg[20][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][12]/q tapped_delay_reg_im_reg[20][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][13]/q tapped_delay_reg_im_reg[20][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][14]/q tapped_delay_reg_im_reg[20][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[20][15]/q tapped_delay_reg_im_reg[20][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[21][0]/q tapped_delay_reg_im_reg[21][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[21][1]/q tapped_delay_reg_im_reg[21][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[21][2]/q tapped_delay_reg_im_reg[21][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][3]/q tapped_delay_reg_im_reg[21][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][4]/q tapped_delay_reg_im_reg[21][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][5]/q tapped_delay_reg_im_reg[21][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][6]/q tapped_delay_reg_im_reg[21][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][7]/q tapped_delay_reg_im_reg[21][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][8]/q tapped_delay_reg_im_reg[21][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][9]/q tapped_delay_reg_im_reg[21][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][10]/q tapped_delay_reg_im_reg[21][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][11]/q tapped_delay_reg_im_reg[21][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[21][12]/q tapped_delay_reg_im_reg[21][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[21][13]/q tapped_delay_reg_im_reg[21][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[21][14]/q tapped_delay_reg_im_reg[21][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[21][15]/q tapped_delay_reg_im_reg[21][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[22][0]/q tapped_delay_reg_im_reg[22][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[22][1]/q tapped_delay_reg_im_reg[22][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[22][2]/q tapped_delay_reg_im_reg[22][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][3]/q tapped_delay_reg_im_reg[22][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][4]/q tapped_delay_reg_im_reg[22][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][5]/q tapped_delay_reg_im_reg[22][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[22][6]/q tapped_delay_reg_im_reg[22][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][7]/q tapped_delay_reg_im_reg[22][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][8]/q tapped_delay_reg_im_reg[22][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][9]/q tapped_delay_reg_im_reg[22][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][10]/q tapped_delay_reg_im_reg[22][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][11]/q tapped_delay_reg_im_reg[22][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][12]/q tapped_delay_reg_im_reg[22][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][13]/q tapped_delay_reg_im_reg[22][13]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][14]/q tapped_delay_reg_im_reg[22][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[22][15]/q tapped_delay_reg_im_reg[22][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][0]/q tapped_delay_reg_im_reg[23][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][1]/q tapped_delay_reg_im_reg[23][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][2]/q tapped_delay_reg_im_reg[23][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][3]/q tapped_delay_reg_im_reg[23][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][4]/q tapped_delay_reg_im_reg[23][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][5]/q tapped_delay_reg_im_reg[23][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][6]/q tapped_delay_reg_im_reg[23][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][7]/q tapped_delay_reg_im_reg[23][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][8]/q tapped_delay_reg_im_reg[23][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][9]/q tapped_delay_reg_im_reg[23][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][10]/q tapped_delay_reg_im_reg[23][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][11]/q tapped_delay_reg_im_reg[23][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][12]/q tapped_delay_reg_im_reg[23][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][13]/q tapped_delay_reg_im_reg[23][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][14]/q tapped_delay_reg_im_reg[23][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[23][15]/q tapped_delay_reg_im_reg[23][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][0]/q tapped_delay_reg_im_reg[24][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_im[24][1]/q tapped_delay_reg_im_reg[24][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][2]/q tapped_delay_reg_im_reg[24][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][3]/q tapped_delay_reg_im_reg[24][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][4]/q tapped_delay_reg_im_reg[24][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][5]/q tapped_delay_reg_im_reg[24][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][6]/q tapped_delay_reg_im_reg[24][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][7]/q tapped_delay_reg_im_reg[24][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][8]/q tapped_delay_reg_im_reg[24][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][9]/q tapped_delay_reg_im_reg[24][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][10]/q tapped_delay_reg_im_reg[24][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][11]/q tapped_delay_reg_im_reg[24][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][12]/q tapped_delay_reg_im_reg[24][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][13]/q tapped_delay_reg_im_reg[24][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][14]/q tapped_delay_reg_im_reg[24][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_im[24][15]/q tapped_delay_reg_im_reg[24][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][0]/q tapped_delay_reg_re_reg[0][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][1]/q tapped_delay_reg_re_reg[0][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][2]/q tapped_delay_reg_re_reg[0][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][3]/q tapped_delay_reg_re_reg[0][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][4]/q tapped_delay_reg_re_reg[0][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][5]/q tapped_delay_reg_re_reg[0][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][6]/q tapped_delay_reg_re_reg[0][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][7]/q tapped_delay_reg_re_reg[0][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][8]/q tapped_delay_reg_re_reg[0][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][9]/q tapped_delay_reg_re_reg[0][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][10]/q tapped_delay_reg_re_reg[0][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][11]/q tapped_delay_reg_re_reg[0][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][12]/q tapped_delay_reg_re_reg[0][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][13]/q tapped_delay_reg_re_reg[0][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][14]/q tapped_delay_reg_re_reg[0][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[0][15]/q tapped_delay_reg_re_reg[0][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][0]/q tapped_delay_reg_re_reg[1][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][1]/q tapped_delay_reg_re_reg[1][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][2]/q tapped_delay_reg_re_reg[1][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][3]/q tapped_delay_reg_re_reg[1][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][4]/q tapped_delay_reg_re_reg[1][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][5]/q tapped_delay_reg_re_reg[1][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][6]/q tapped_delay_reg_re_reg[1][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][7]/q tapped_delay_reg_re_reg[1][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][8]/q tapped_delay_reg_re_reg[1][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][9]/q tapped_delay_reg_re_reg[1][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][10]/q tapped_delay_reg_re_reg[1][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][11]/q tapped_delay_reg_re_reg[1][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][12]/q tapped_delay_reg_re_reg[1][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][13]/q tapped_delay_reg_re_reg[1][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][14]/q tapped_delay_reg_re_reg[1][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[1][15]/q tapped_delay_reg_re_reg[1][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][0]/q tapped_delay_reg_re_reg[2][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][1]/q tapped_delay_reg_re_reg[2][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][2]/q tapped_delay_reg_re_reg[2][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][3]/q tapped_delay_reg_re_reg[2][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][4]/q tapped_delay_reg_re_reg[2][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][5]/q tapped_delay_reg_re_reg[2][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][6]/q tapped_delay_reg_re_reg[2][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][7]/q tapped_delay_reg_re_reg[2][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][8]/q tapped_delay_reg_re_reg[2][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][9]/q tapped_delay_reg_re_reg[2][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][10]/q tapped_delay_reg_re_reg[2][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][11]/q tapped_delay_reg_re_reg[2][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][12]/q tapped_delay_reg_re_reg[2][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][13]/q tapped_delay_reg_re_reg[2][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][14]/q tapped_delay_reg_re_reg[2][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[2][15]/q tapped_delay_reg_re_reg[2][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][0]/q tapped_delay_reg_re_reg[3][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][1]/q tapped_delay_reg_re_reg[3][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][2]/q tapped_delay_reg_re_reg[3][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][3]/q tapped_delay_reg_re_reg[3][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][4]/q tapped_delay_reg_re_reg[3][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][5]/q tapped_delay_reg_re_reg[3][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][6]/q tapped_delay_reg_re_reg[3][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][7]/q tapped_delay_reg_re_reg[3][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][8]/q tapped_delay_reg_re_reg[3][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][9]/q tapped_delay_reg_re_reg[3][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][10]/q tapped_delay_reg_re_reg[3][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][11]/q tapped_delay_reg_re_reg[3][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][12]/q tapped_delay_reg_re_reg[3][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][13]/q tapped_delay_reg_re_reg[3][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][14]/q tapped_delay_reg_re_reg[3][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[3][15]/q tapped_delay_reg_re_reg[3][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][0]/q tapped_delay_reg_re_reg[4][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][1]/q tapped_delay_reg_re_reg[4][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][2]/q tapped_delay_reg_re_reg[4][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][3]/q tapped_delay_reg_re_reg[4][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][4]/q tapped_delay_reg_re_reg[4][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][5]/q tapped_delay_reg_re_reg[4][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[4][6]/q tapped_delay_reg_re_reg[4][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][7]/q tapped_delay_reg_re_reg[4][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][8]/q tapped_delay_reg_re_reg[4][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[4][9]/q tapped_delay_reg_re_reg[4][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[4][10]/q tapped_delay_reg_re_reg[4][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[4][11]/q tapped_delay_reg_re_reg[4][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][12]/q tapped_delay_reg_re_reg[4][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[4][13]/q tapped_delay_reg_re_reg[4][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[4][14]/q tapped_delay_reg_re_reg[4][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[4][15]/q tapped_delay_reg_re_reg[4][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][0]/q tapped_delay_reg_re_reg[5][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][1]/q tapped_delay_reg_re_reg[5][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][2]/q tapped_delay_reg_re_reg[5][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][3]/q tapped_delay_reg_re_reg[5][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][4]/q tapped_delay_reg_re_reg[5][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][5]/q tapped_delay_reg_re_reg[5][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][6]/q tapped_delay_reg_re_reg[5][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][7]/q tapped_delay_reg_re_reg[5][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][8]/q tapped_delay_reg_re_reg[5][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][9]/q tapped_delay_reg_re_reg[5][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][10]/q tapped_delay_reg_re_reg[5][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][11]/q tapped_delay_reg_re_reg[5][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][12]/q tapped_delay_reg_re_reg[5][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][13]/q tapped_delay_reg_re_reg[5][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][14]/q tapped_delay_reg_re_reg[5][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[5][15]/q tapped_delay_reg_re_reg[5][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][0]/q tapped_delay_reg_re_reg[6][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][1]/q tapped_delay_reg_re_reg[6][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][2]/q tapped_delay_reg_re_reg[6][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][3]/q tapped_delay_reg_re_reg[6][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][4]/q tapped_delay_reg_re_reg[6][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][5]/q tapped_delay_reg_re_reg[6][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][6]/q tapped_delay_reg_re_reg[6][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][7]/q tapped_delay_reg_re_reg[6][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][8]/q tapped_delay_reg_re_reg[6][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][9]/q tapped_delay_reg_re_reg[6][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][10]/q tapped_delay_reg_re_reg[6][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][11]/q tapped_delay_reg_re_reg[6][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][12]/q tapped_delay_reg_re_reg[6][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][13]/q tapped_delay_reg_re_reg[6][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][14]/q tapped_delay_reg_re_reg[6][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[6][15]/q tapped_delay_reg_re_reg[6][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][0]/q tapped_delay_reg_re_reg[7][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][1]/q tapped_delay_reg_re_reg[7][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][2]/q tapped_delay_reg_re_reg[7][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][3]/q tapped_delay_reg_re_reg[7][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][4]/q tapped_delay_reg_re_reg[7][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][5]/q tapped_delay_reg_re_reg[7][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][6]/q tapped_delay_reg_re_reg[7][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][7]/q tapped_delay_reg_re_reg[7][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][8]/q tapped_delay_reg_re_reg[7][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][9]/q tapped_delay_reg_re_reg[7][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][10]/q tapped_delay_reg_re_reg[7][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][11]/q tapped_delay_reg_re_reg[7][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][12]/q tapped_delay_reg_re_reg[7][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][13]/q tapped_delay_reg_re_reg[7][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][14]/q tapped_delay_reg_re_reg[7][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[7][15]/q tapped_delay_reg_re_reg[7][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][0]/q tapped_delay_reg_re_reg[8][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][1]/q tapped_delay_reg_re_reg[8][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][2]/q tapped_delay_reg_re_reg[8][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][3]/q tapped_delay_reg_re_reg[8][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][4]/q tapped_delay_reg_re_reg[8][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][5]/q tapped_delay_reg_re_reg[8][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][6]/q tapped_delay_reg_re_reg[8][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][7]/q tapped_delay_reg_re_reg[8][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][8]/q tapped_delay_reg_re_reg[8][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][9]/q tapped_delay_reg_re_reg[8][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][10]/q tapped_delay_reg_re_reg[8][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][11]/q tapped_delay_reg_re_reg[8][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][12]/q tapped_delay_reg_re_reg[8][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][13]/q tapped_delay_reg_re_reg[8][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][14]/q tapped_delay_reg_re_reg[8][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[8][15]/q tapped_delay_reg_re_reg[8][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][0]/q tapped_delay_reg_re_reg[9][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][1]/q tapped_delay_reg_re_reg[9][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][2]/q tapped_delay_reg_re_reg[9][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][3]/q tapped_delay_reg_re_reg[9][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][4]/q tapped_delay_reg_re_reg[9][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][5]/q tapped_delay_reg_re_reg[9][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][6]/q tapped_delay_reg_re_reg[9][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][7]/q tapped_delay_reg_re_reg[9][7]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][8]/q tapped_delay_reg_re_reg[9][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][9]/q tapped_delay_reg_re_reg[9][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][10]/q tapped_delay_reg_re_reg[9][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][11]/q tapped_delay_reg_re_reg[9][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][12]/q tapped_delay_reg_re_reg[9][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][13]/q tapped_delay_reg_re_reg[9][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[9][14]/q tapped_delay_reg_re_reg[9][14]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[9][15]/q tapped_delay_reg_re_reg[9][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][0]/q tapped_delay_reg_re_reg[10][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][1]/q tapped_delay_reg_re_reg[10][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][2]/q tapped_delay_reg_re_reg[10][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][3]/q tapped_delay_reg_re_reg[10][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][4]/q tapped_delay_reg_re_reg[10][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][5]/q tapped_delay_reg_re_reg[10][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][6]/q tapped_delay_reg_re_reg[10][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][7]/q tapped_delay_reg_re_reg[10][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][8]/q tapped_delay_reg_re_reg[10][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][9]/q tapped_delay_reg_re_reg[10][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][10]/q tapped_delay_reg_re_reg[10][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[10][11]/q tapped_delay_reg_re_reg[10][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][12]/q tapped_delay_reg_re_reg[10][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][13]/q tapped_delay_reg_re_reg[10][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][14]/q tapped_delay_reg_re_reg[10][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[10][15]/q tapped_delay_reg_re_reg[10][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][0]/q tapped_delay_reg_re_reg[11][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][1]/q tapped_delay_reg_re_reg[11][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][2]/q tapped_delay_reg_re_reg[11][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][3]/q tapped_delay_reg_re_reg[11][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][4]/q tapped_delay_reg_re_reg[11][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][5]/q tapped_delay_reg_re_reg[11][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][6]/q tapped_delay_reg_re_reg[11][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][7]/q tapped_delay_reg_re_reg[11][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][8]/q tapped_delay_reg_re_reg[11][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][9]/q tapped_delay_reg_re_reg[11][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][10]/q tapped_delay_reg_re_reg[11][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][11]/q tapped_delay_reg_re_reg[11][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][12]/q tapped_delay_reg_re_reg[11][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][13]/q tapped_delay_reg_re_reg[11][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][14]/q tapped_delay_reg_re_reg[11][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[11][15]/q tapped_delay_reg_re_reg[11][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][0]/q tapped_delay_reg_re_reg[12][0]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[12][1]/q tapped_delay_reg_re_reg[12][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][2]/q tapped_delay_reg_re_reg[12][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][3]/q tapped_delay_reg_re_reg[12][3]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[12][4]/q tapped_delay_reg_re_reg[12][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][5]/q tapped_delay_reg_re_reg[12][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[12][6]/q tapped_delay_reg_re_reg[12][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[12][7]/q tapped_delay_reg_re_reg[12][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][8]/q tapped_delay_reg_re_reg[12][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[12][9]/q tapped_delay_reg_re_reg[12][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][10]/q tapped_delay_reg_re_reg[12][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][11]/q tapped_delay_reg_re_reg[12][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][12]/q tapped_delay_reg_re_reg[12][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[12][13]/q tapped_delay_reg_re_reg[12][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][14]/q tapped_delay_reg_re_reg[12][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[12][15]/q tapped_delay_reg_re_reg[12][15]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[13][0]/q tapped_delay_reg_re_reg[13][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][1]/q tapped_delay_reg_re_reg[13][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][2]/q tapped_delay_reg_re_reg[13][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][3]/q tapped_delay_reg_re_reg[13][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][4]/q tapped_delay_reg_re_reg[13][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][5]/q tapped_delay_reg_re_reg[13][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][6]/q tapped_delay_reg_re_reg[13][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][7]/q tapped_delay_reg_re_reg[13][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][8]/q tapped_delay_reg_re_reg[13][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][9]/q tapped_delay_reg_re_reg[13][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[13][10]/q tapped_delay_reg_re_reg[13][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][11]/q tapped_delay_reg_re_reg[13][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][12]/q tapped_delay_reg_re_reg[13][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][13]/q tapped_delay_reg_re_reg[13][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][14]/q tapped_delay_reg_re_reg[13][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[13][15]/q tapped_delay_reg_re_reg[13][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][0]/q tapped_delay_reg_re_reg[14][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][1]/q tapped_delay_reg_re_reg[14][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][2]/q tapped_delay_reg_re_reg[14][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][3]/q tapped_delay_reg_re_reg[14][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][4]/q tapped_delay_reg_re_reg[14][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][5]/q tapped_delay_reg_re_reg[14][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][6]/q tapped_delay_reg_re_reg[14][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][7]/q tapped_delay_reg_re_reg[14][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][8]/q tapped_delay_reg_re_reg[14][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][9]/q tapped_delay_reg_re_reg[14][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][10]/q tapped_delay_reg_re_reg[14][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][11]/q tapped_delay_reg_re_reg[14][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][12]/q tapped_delay_reg_re_reg[14][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][13]/q tapped_delay_reg_re_reg[14][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][14]/q tapped_delay_reg_re_reg[14][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[14][15]/q tapped_delay_reg_re_reg[14][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][0]/q tapped_delay_reg_re_reg[15][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][1]/q tapped_delay_reg_re_reg[15][1]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][2]/q tapped_delay_reg_re_reg[15][2]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][3]/q tapped_delay_reg_re_reg[15][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][4]/q tapped_delay_reg_re_reg[15][4]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][5]/q tapped_delay_reg_re_reg[15][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][6]/q tapped_delay_reg_re_reg[15][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][7]/q tapped_delay_reg_re_reg[15][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][8]/q tapped_delay_reg_re_reg[15][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][9]/q tapped_delay_reg_re_reg[15][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][10]/q tapped_delay_reg_re_reg[15][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][11]/q tapped_delay_reg_re_reg[15][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][12]/q tapped_delay_reg_re_reg[15][12]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[15][13]/q tapped_delay_reg_re_reg[15][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][14]/q tapped_delay_reg_re_reg[15][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[15][15]/q tapped_delay_reg_re_reg[15][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][0]/q tapped_delay_reg_re_reg[16][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][1]/q tapped_delay_reg_re_reg[16][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][2]/q tapped_delay_reg_re_reg[16][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][3]/q tapped_delay_reg_re_reg[16][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][4]/q tapped_delay_reg_re_reg[16][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][5]/q tapped_delay_reg_re_reg[16][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][6]/q tapped_delay_reg_re_reg[16][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][7]/q tapped_delay_reg_re_reg[16][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][8]/q tapped_delay_reg_re_reg[16][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][9]/q tapped_delay_reg_re_reg[16][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][10]/q tapped_delay_reg_re_reg[16][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][11]/q tapped_delay_reg_re_reg[16][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][12]/q tapped_delay_reg_re_reg[16][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][13]/q tapped_delay_reg_re_reg[16][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][14]/q tapped_delay_reg_re_reg[16][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[16][15]/q tapped_delay_reg_re_reg[16][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][0]/q tapped_delay_reg_re_reg[17][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][1]/q tapped_delay_reg_re_reg[17][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][2]/q tapped_delay_reg_re_reg[17][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][3]/q tapped_delay_reg_re_reg[17][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][4]/q tapped_delay_reg_re_reg[17][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][5]/q tapped_delay_reg_re_reg[17][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][6]/q tapped_delay_reg_re_reg[17][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][7]/q tapped_delay_reg_re_reg[17][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][8]/q tapped_delay_reg_re_reg[17][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][9]/q tapped_delay_reg_re_reg[17][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][10]/q tapped_delay_reg_re_reg[17][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][11]/q tapped_delay_reg_re_reg[17][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][12]/q tapped_delay_reg_re_reg[17][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][13]/q tapped_delay_reg_re_reg[17][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][14]/q tapped_delay_reg_re_reg[17][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[17][15]/q tapped_delay_reg_re_reg[17][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][0]/q tapped_delay_reg_re_reg[18][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][1]/q tapped_delay_reg_re_reg[18][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][2]/q tapped_delay_reg_re_reg[18][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][3]/q tapped_delay_reg_re_reg[18][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][4]/q tapped_delay_reg_re_reg[18][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][5]/q tapped_delay_reg_re_reg[18][5]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[18][6]/q tapped_delay_reg_re_reg[18][6]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[18][7]/q tapped_delay_reg_re_reg[18][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][8]/q tapped_delay_reg_re_reg[18][8]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[18][9]/q tapped_delay_reg_re_reg[18][9]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[18][10]/q tapped_delay_reg_re_reg[18][10]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[18][11]/q tapped_delay_reg_re_reg[18][11]/QN -type DFF DFF
add mapped point tapped_delay_reg_re[18][12]/q tapped_delay_reg_re_reg[18][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][13]/q tapped_delay_reg_re_reg[18][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][14]/q tapped_delay_reg_re_reg[18][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[18][15]/q tapped_delay_reg_re_reg[18][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][0]/q tapped_delay_reg_re_reg[19][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][1]/q tapped_delay_reg_re_reg[19][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][2]/q tapped_delay_reg_re_reg[19][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][3]/q tapped_delay_reg_re_reg[19][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][4]/q tapped_delay_reg_re_reg[19][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][5]/q tapped_delay_reg_re_reg[19][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][6]/q tapped_delay_reg_re_reg[19][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][7]/q tapped_delay_reg_re_reg[19][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][8]/q tapped_delay_reg_re_reg[19][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][9]/q tapped_delay_reg_re_reg[19][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][10]/q tapped_delay_reg_re_reg[19][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][11]/q tapped_delay_reg_re_reg[19][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][12]/q tapped_delay_reg_re_reg[19][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][13]/q tapped_delay_reg_re_reg[19][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][14]/q tapped_delay_reg_re_reg[19][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[19][15]/q tapped_delay_reg_re_reg[19][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][0]/q tapped_delay_reg_re_reg[20][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][1]/q tapped_delay_reg_re_reg[20][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][2]/q tapped_delay_reg_re_reg[20][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][3]/q tapped_delay_reg_re_reg[20][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][4]/q tapped_delay_reg_re_reg[20][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][5]/q tapped_delay_reg_re_reg[20][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][6]/q tapped_delay_reg_re_reg[20][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][7]/q tapped_delay_reg_re_reg[20][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][8]/q tapped_delay_reg_re_reg[20][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][9]/q tapped_delay_reg_re_reg[20][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][10]/q tapped_delay_reg_re_reg[20][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][11]/q tapped_delay_reg_re_reg[20][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][12]/q tapped_delay_reg_re_reg[20][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][13]/q tapped_delay_reg_re_reg[20][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][14]/q tapped_delay_reg_re_reg[20][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[20][15]/q tapped_delay_reg_re_reg[20][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][0]/q tapped_delay_reg_re_reg[21][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][1]/q tapped_delay_reg_re_reg[21][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][2]/q tapped_delay_reg_re_reg[21][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][3]/q tapped_delay_reg_re_reg[21][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][4]/q tapped_delay_reg_re_reg[21][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][5]/q tapped_delay_reg_re_reg[21][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][6]/q tapped_delay_reg_re_reg[21][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][7]/q tapped_delay_reg_re_reg[21][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][8]/q tapped_delay_reg_re_reg[21][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][9]/q tapped_delay_reg_re_reg[21][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][10]/q tapped_delay_reg_re_reg[21][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][11]/q tapped_delay_reg_re_reg[21][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][12]/q tapped_delay_reg_re_reg[21][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][13]/q tapped_delay_reg_re_reg[21][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][14]/q tapped_delay_reg_re_reg[21][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[21][15]/q tapped_delay_reg_re_reg[21][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][0]/q tapped_delay_reg_re_reg[22][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][1]/q tapped_delay_reg_re_reg[22][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][2]/q tapped_delay_reg_re_reg[22][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][3]/q tapped_delay_reg_re_reg[22][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][4]/q tapped_delay_reg_re_reg[22][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][5]/q tapped_delay_reg_re_reg[22][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][6]/q tapped_delay_reg_re_reg[22][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][7]/q tapped_delay_reg_re_reg[22][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][8]/q tapped_delay_reg_re_reg[22][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][9]/q tapped_delay_reg_re_reg[22][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][10]/q tapped_delay_reg_re_reg[22][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][11]/q tapped_delay_reg_re_reg[22][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][12]/q tapped_delay_reg_re_reg[22][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][13]/q tapped_delay_reg_re_reg[22][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][14]/q tapped_delay_reg_re_reg[22][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[22][15]/q tapped_delay_reg_re_reg[22][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][0]/q tapped_delay_reg_re_reg[23][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][1]/q tapped_delay_reg_re_reg[23][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][2]/q tapped_delay_reg_re_reg[23][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][3]/q tapped_delay_reg_re_reg[23][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][4]/q tapped_delay_reg_re_reg[23][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][5]/q tapped_delay_reg_re_reg[23][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][6]/q tapped_delay_reg_re_reg[23][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][7]/q tapped_delay_reg_re_reg[23][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][8]/q tapped_delay_reg_re_reg[23][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][9]/q tapped_delay_reg_re_reg[23][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][10]/q tapped_delay_reg_re_reg[23][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][11]/q tapped_delay_reg_re_reg[23][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][12]/q tapped_delay_reg_re_reg[23][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][13]/q tapped_delay_reg_re_reg[23][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][14]/q tapped_delay_reg_re_reg[23][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[23][15]/q tapped_delay_reg_re_reg[23][15]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][0]/q tapped_delay_reg_re_reg[24][0]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][1]/q tapped_delay_reg_re_reg[24][1]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][2]/q tapped_delay_reg_re_reg[24][2]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][3]/q tapped_delay_reg_re_reg[24][3]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][4]/q tapped_delay_reg_re_reg[24][4]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][5]/q tapped_delay_reg_re_reg[24][5]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][6]/q tapped_delay_reg_re_reg[24][6]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][7]/q tapped_delay_reg_re_reg[24][7]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][8]/q tapped_delay_reg_re_reg[24][8]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][9]/q tapped_delay_reg_re_reg[24][9]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][10]/q tapped_delay_reg_re_reg[24][10]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][11]/q tapped_delay_reg_re_reg[24][11]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][12]/q tapped_delay_reg_re_reg[24][12]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][13]/q tapped_delay_reg_re_reg[24][13]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][14]/q tapped_delay_reg_re_reg[24][14]/Q -type DFF DFF
add mapped point tapped_delay_reg_re[24][15]/q tapped_delay_reg_re_reg[24][15]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
