###############################################################
#  Generated by:      Cadence Innovus 21.12-s106_1
#  OS:                Linux x86_64(Host ID cluster12)
#  Generated on:      Fri May 10 17:03:16 2024
#  Design:            topVcoDigital
###############################################################
current_design topVcoDigital
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {sclk}]  -name sclk -period 31.250000 -waveform {0.000000 15.625000}
create_clock [get_ports {clk}]  -name clk -period 20.000000 -waveform {0.000000 10.000000}
set_load -pin_load -max  1  [get_ports {vcoTrim[15]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[15]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[14]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[14]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[13]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[13]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[12]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[12]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[11]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[11]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[10]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[10]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[9]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[9]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[8]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[8]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[7]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[7]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[6]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[6]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[5]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[5]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[4]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[4]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[3]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[3]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[2]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[2]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[1]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[1]}]
set_load -pin_load -max  1  [get_ports {vcoTrim[0]}]
set_load -pin_load -min  1  [get_ports {vcoTrim[0]}]
set_max_fanout 15  [get_designs {topVcoDigital}]
set_max_transition 4  [get_designs {topVcoDigital}]
set_input_delay -add_delay 1 -clock [get_clocks {sclk}] [get_ports {mosi}]
set_input_delay -add_delay 1 -clock [get_clocks {sclk}] [get_ports {ss}]
set_input_delay -add_delay 1 -clock [get_clocks {sclk}] [get_ports {rst}]
set_false_path  -from [get_clocks {clk}] -to [get_clocks {sclk}]
set_clock_groups -name async_clk_sclk -asynchronous  -group  [get_clocks {clk sclk}]
