// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_hybrid\scpa_ppfir_blocked_hybrid\digPhaseCombiner.v
// Created: 2026-01-12 13:19:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: digPhaseCombiner
// Source Path: scpa_ppfir_blocked_hybrid/scpa_dig_ana_ppfir/digPhaseCombiner
// Hierarchy Level: 1
// Model version: 1.67
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module digPhaseCombiner
          (clk,
           rst_n,
           enb_1_4_0,
           In1,
           In2,
           re_dig_0);


  input   clk;
  input   rst_n;
  input   enb_1_4_0;
  input   [7:0] In1;  // uint8
  input   [7:0] In2;  // uint8
  output  [7:0] re_dig_0;  // uint8


  reg  Upsample1_muxsel;  // ufix1
  wire [7:0] Upsample1_zero;  // uint8
  wire [7:0] Upsample1_out1;  // uint8
  reg  Upsample4_muxsel;  // ufix1
  wire [7:0] Upsample4_zero;  // uint8
  wire [7:0] Upsample4_out1;  // uint8
  wire [7:0] Add26_out1;  // uint8


  // Free running, Unsigned Counter
  //  initial value   = 1
  //  step value      = 1
  always @(posedge clk or negedge rst_n)
    begin : Upsample1_cnt_process
      if (rst_n == 1'b0) begin
        Upsample1_muxsel <= 1'b1;
      end
      else begin
        if (enb_1_4_0) begin
          Upsample1_muxsel <=  ~ Upsample1_muxsel;
        end
      end
    end



  assign Upsample1_zero = 8'b00000000;



  // Upsample1: Upsample by 2, Sample offset 0 
  assign Upsample1_out1 = (Upsample1_muxsel == 1'b1 ? In1 :
              Upsample1_zero);



  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  always @(posedge clk or negedge rst_n)
    begin : Upsample4_cnt_process
      if (rst_n == 1'b0) begin
        Upsample4_muxsel <= 1'b0;
      end
      else begin
        if (enb_1_4_0) begin
          Upsample4_muxsel <=  ~ Upsample4_muxsel;
        end
      end
    end



  assign Upsample4_zero = 8'b00000000;



  // Upsample4: Upsample by 2, Sample offset 1 
  assign Upsample4_out1 = (Upsample4_muxsel == 1'b1 ? In2 :
              Upsample4_zero);



  assign Add26_out1 = Upsample1_out1 + Upsample4_out1;

  assign re_dig_0 = Add26_out1;

endmodule  // digPhaseCombiner

