// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_blocked_total_v2\scpa_ppfir_blocked_total\FilterTapSystolicWvldin_block.v
// Created: 2025-04-08 12:29:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicWvldin_block

// Source Path: scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR Interpolator/scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR 
// Interpolator/FIRFilter3/Filter/subFilter/FilterTapSystolicWvldi
// Hierarchy Level: 6
// Model version: 1.91
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicWvldin_block
          (clk,
           rst_n,
           enb_1_32_0,
           dinReg2_0_re,
           coefIn_0,
           addin,
           dinRegVld,
           syncReset,
           dinDly2,
           tapout);


  input   clk;
  input   rst_n;
  input   enb_1_32_0;
  input   signed [12:0] dinReg2_0_re;  // sfix13_En12
  input   signed [15:0] coefIn_0;  // sfix16_En15
  input   signed [29:0] addin;  // sfix30_En27
  input   dinRegVld;
  input   syncReset;
  output  signed [12:0] dinDly2;  // sfix13_En12
  output  signed [29:0] tapout;  // sfix30_En27


  reg signed [12:0] fTap_din_reg1;  // sfix13
  reg signed [15:0] fTap_coef_reg1;  // sfix16
  reg signed [12:0] fTap_din_reg2;  // sfix13
  reg signed [15:0] fTap_coef_reg2;  // sfix16
  reg signed [28:0] fTap_mult_reg;  // sfix29
  reg signed [29:0] fTap_addout_reg;  // sfix30
  reg signed [12:0] fTap_din_reg1_next;  // sfix13_En12
  reg signed [15:0] fTap_coef_reg1_next;  // sfix16_En15
  reg signed [12:0] fTap_din_reg2_next;  // sfix13_En12
  reg signed [15:0] fTap_coef_reg2_next;  // sfix16_En15
  reg signed [28:0] fTap_mult_reg_next;  // sfix29_En27
  reg signed [29:0] fTap_addout_reg_next;  // sfix30_En27
  reg signed [12:0] dinDly2_1;  // sfix13_En12
  reg signed [29:0] tapout_1;  // sfix30_En27
  reg signed [29:0] fTap_add_cast;  // sfix30_En27


  // FilterTapSystlicWvldIn
  always @(posedge clk or negedge rst_n)
    begin : fTap_process
      if (rst_n == 1'b0) begin
        fTap_din_reg1 <= 13'sb0000000000000;
        fTap_coef_reg1 <= 16'sb0000000000000000;
        fTap_din_reg2 <= 13'sb0000000000000;
        fTap_coef_reg2 <= 16'sb0000000000000000;
        fTap_mult_reg <= 29'sb00000000000000000000000000000;
        fTap_addout_reg <= 30'sb000000000000000000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            fTap_din_reg1 <= 13'sb0000000000000;
            fTap_coef_reg1 <= 16'sb0000000000000000;
            fTap_din_reg2 <= 13'sb0000000000000;
            fTap_coef_reg2 <= 16'sb0000000000000000;
            fTap_mult_reg <= 29'sb00000000000000000000000000000;
            fTap_addout_reg <= 30'sb000000000000000000000000000000;
          end
          else begin
            fTap_din_reg1 <= fTap_din_reg1_next;
            fTap_coef_reg1 <= fTap_coef_reg1_next;
            fTap_din_reg2 <= fTap_din_reg2_next;
            fTap_coef_reg2 <= fTap_coef_reg2_next;
            fTap_mult_reg <= fTap_mult_reg_next;
            fTap_addout_reg <= fTap_addout_reg_next;
          end
        end
      end
    end

  always @(addin, coefIn_0, dinReg2_0_re, dinRegVld, fTap_addout_reg, fTap_coef_reg1,
       fTap_coef_reg2, fTap_din_reg1, fTap_din_reg2, fTap_mult_reg) begin
    fTap_add_cast = 30'sb000000000000000000000000000000;
    fTap_din_reg1_next = fTap_din_reg1;
    fTap_coef_reg1_next = fTap_coef_reg1;
    fTap_din_reg2_next = fTap_din_reg2;
    fTap_coef_reg2_next = fTap_coef_reg2;
    fTap_mult_reg_next = fTap_mult_reg;
    fTap_addout_reg_next = fTap_addout_reg;
    if (dinRegVld) begin
      fTap_add_cast = {fTap_mult_reg[28], fTap_mult_reg};
      fTap_addout_reg_next = fTap_add_cast + addin;
      fTap_mult_reg_next = fTap_din_reg2 * fTap_coef_reg2;
      fTap_din_reg2_next = fTap_din_reg1;
      fTap_coef_reg2_next = fTap_coef_reg1;
      fTap_din_reg1_next = dinReg2_0_re;
      fTap_coef_reg1_next = coefIn_0;
    end
    dinDly2_1 = fTap_din_reg2;
    tapout_1 = fTap_addout_reg;
  end



  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // FilterTapSystolicWvldin_block

