// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_blocked_total_v2\scpa_ppfir_blocked_total\FilterTapSystolicWvldInC0_block2.v
// Created: 2025-04-08 12:29:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicWvldInC0_block2

// Source Path: scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR Interpolator/scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR 
// Interpolator/FIRFilter4/Filter/subFilter/FilterTapSystolicWvldInC
// Hierarchy Level: 6
// Model version: 1.91
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicWvldInC0_block2
          (clk,
           rst_n,
           enb_1_32_0,
           dinReg2_0_re,
           addin,
           dinRegVld,
           syncReset,
           tapout);


  input   clk;
  input   rst_n;
  input   enb_1_32_0;
  input   signed [12:0] dinReg2_0_re;  // sfix13_En12
  input   signed [28:0] addin;  // sfix29_En27
  input   dinRegVld;
  input   syncReset;
  output  signed [28:0] tapout;  // sfix29_En27


  reg signed [12:0] fTap_din1_reg1;  // sfix13
  reg signed [12:0] fTap_din1_reg2;  // sfix13
  reg signed [28:0] fTap_addout_reg;  // sfix29
  reg signed [12:0] fTap_din1_reg1_next;  // sfix13_En12
  reg signed [12:0] fTap_din1_reg2_next;  // sfix13_En12
  reg signed [28:0] fTap_addout_reg_next;  // sfix29_En27
  reg signed [12:0] dinDly2;  // sfix13_En12
  reg signed [28:0] tapout_1;  // sfix29_En27


  // FilterTapSystolicWvldInC0
  always @(posedge clk or negedge rst_n)
    begin : fTap_process
      if (rst_n == 1'b0) begin
        fTap_din1_reg1 <= 13'sb0000000000000;
        fTap_din1_reg2 <= 13'sb0000000000000;
        fTap_addout_reg <= 29'sb00000000000000000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            fTap_din1_reg1 <= 13'sb0000000000000;
            fTap_din1_reg2 <= 13'sb0000000000000;
            fTap_addout_reg <= 29'sb00000000000000000000000000000;
          end
          else begin
            fTap_din1_reg1 <= fTap_din1_reg1_next;
            fTap_din1_reg2 <= fTap_din1_reg2_next;
            fTap_addout_reg <= fTap_addout_reg_next;
          end
        end
      end
    end

  always @(addin, dinReg2_0_re, dinRegVld, fTap_addout_reg, fTap_din1_reg1,
       fTap_din1_reg2) begin
    fTap_din1_reg1_next = fTap_din1_reg1;
    fTap_din1_reg2_next = fTap_din1_reg2;
    fTap_addout_reg_next = fTap_addout_reg;
    if (dinRegVld) begin
      fTap_addout_reg_next = addin;
    end
    if (dinRegVld) begin
      fTap_din1_reg2_next = fTap_din1_reg1;
      fTap_din1_reg1_next = dinReg2_0_re;
    end
    dinDly2 = fTap_din1_reg2;
    tapout_1 = fTap_addout_reg;
  end



  assign tapout = tapout_1;

endmodule  // FilterTapSystolicWvldInC0_block2

