// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_blocked_total_v2\scpa_ppfir_blocked_total\Filter_block2.v
// Created: 2025-04-08 12:29:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter_block2

// Source Path: scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR Interpolator/scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR 
// Interpolator/FIRFilter4/Filte
// Hierarchy Level: 4
// Model version: 1.91
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter_block2
          (clk,
           rst_n,
           enb_1_32_0,
           dataIn_re,
           dataIn_im,
           validIn,
           syncReset,
           dataOut_re,
           dataOut_im);


  input   clk;
  input   rst_n;
  input   enb_1_32_0;
  input   signed [12:0] dataIn_re;  // sfix13_En12
  input   signed [12:0] dataIn_im;  // sfix13_En12
  input   validIn;
  input   syncReset;
  output  signed [15:0] dataOut_re;  // sfix16_En15
  output  signed [15:0] dataOut_im;  // sfix16_En15


  reg  dinRegVld;
  reg signed [12:0] dinReg_0_re;  // sfix13_En12
  reg signed [12:0] dinReg2_0_re;  // sfix13_En12
  wire signed [15:0] CoefOut_0;  // sfix16_En15
  wire signed [15:0] CoefOut_1;  // sfix16_En15
  wire signed [15:0] CoefOut_2;  // sfix16_En15
  wire signed [15:0] CoefOut_3;  // sfix16_En15
  wire signed [15:0] CoefOut_4;  // sfix16_En15
  wire signed [15:0] CoefOut_5;  // sfix16_En15
  wire signed [15:0] CoefOut_6;  // sfix16_En15
  wire signed [15:0] CoefOut_7;  // sfix16_En15
  wire signed [15:0] CoefOut_8;  // sfix16_En15
  wire signed [15:0] CoefOut_9;  // sfix16_En15
  wire signed [15:0] CoefOut_10;  // sfix16_En15
  wire signed [15:0] CoefOut_11;  // sfix16_En15
  wire signed [15:0] CoefOut_12;  // sfix16_En15
  wire signed [15:0] CoefOut_13;  // sfix16_En15
  wire signed [15:0] CoefOut_14;  // sfix16_En15
  wire signed [15:0] CoefOut_15;  // sfix16_En15
  wire signed [15:0] CoefOut_16;  // sfix16_En15
  wire signed [15:0] CoefOut_17;  // sfix16_En15
  wire signed [15:0] CoefOut_18;  // sfix16_En15
  wire signed [15:0] CoefOut_19;  // sfix16_En15
  wire signed [15:0] CoefOut_20;  // sfix16_En15
  wire signed [15:0] CoefOut_21;  // sfix16_En15
  wire signed [15:0] CoefOut_22;  // sfix16_En15
  wire signed [15:0] CoefOut_23;  // sfix16_En15
  wire signed [15:0] CoefOut_24;  // sfix16_En15
  reg  dinReg2Vld;
  wire signed [15:0] dout_1_re;  // sfix16_En15
  reg signed [12:0] dinReg_0_im;  // sfix13_En12
  reg signed [12:0] dinReg2_0_im;  // sfix13_En12
  wire signed [15:0] dout_1_im;  // sfix16_En15


  always @(posedge clk or negedge rst_n)
    begin : intdelay_process
      if (rst_n == 1'b0) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : intdelay_1_process
      if (rst_n == 1'b0) begin
        dinReg_0_re <= 13'sb0000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 13'sb0000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn_re;
            end
          end
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : intdelay_2_process
      if (rst_n == 1'b0) begin
        dinReg2_0_re <= 13'sb0000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 13'sb0000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end



  FilterCoef_block2 CoefTable_1_3 (.CoefOut_0(CoefOut_0),  // sfix16_En15
                                   .CoefOut_1(CoefOut_1),  // sfix16_En15
                                   .CoefOut_2(CoefOut_2),  // sfix16_En15
                                   .CoefOut_3(CoefOut_3),  // sfix16_En15
                                   .CoefOut_4(CoefOut_4),  // sfix16_En15
                                   .CoefOut_5(CoefOut_5),  // sfix16_En15
                                   .CoefOut_6(CoefOut_6),  // sfix16_En15
                                   .CoefOut_7(CoefOut_7),  // sfix16_En15
                                   .CoefOut_8(CoefOut_8),  // sfix16_En15
                                   .CoefOut_9(CoefOut_9),  // sfix16_En15
                                   .CoefOut_10(CoefOut_10),  // sfix16_En15
                                   .CoefOut_11(CoefOut_11),  // sfix16_En15
                                   .CoefOut_12(CoefOut_12),  // sfix16_En15
                                   .CoefOut_13(CoefOut_13),  // sfix16_En15
                                   .CoefOut_14(CoefOut_14),  // sfix16_En15
                                   .CoefOut_15(CoefOut_15),  // sfix16_En15
                                   .CoefOut_16(CoefOut_16),  // sfix16_En15
                                   .CoefOut_17(CoefOut_17),  // sfix16_En15
                                   .CoefOut_18(CoefOut_18),  // sfix16_En15
                                   .CoefOut_19(CoefOut_19),  // sfix16_En15
                                   .CoefOut_20(CoefOut_20),  // sfix16_En15
                                   .CoefOut_21(CoefOut_21),  // sfix16_En15
                                   .CoefOut_22(CoefOut_22),  // sfix16_En15
                                   .CoefOut_23(CoefOut_23),  // sfix16_En15
                                   .CoefOut_24(CoefOut_24)  // sfix16_En15
                                   );

  always @(posedge clk or negedge rst_n)
    begin : intdelay_3_process
      if (rst_n == 1'b0) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end



  subFilter_block2 subFilter_1_re_3 (.clk(clk),
                                     .rst_n(rst_n),
                                     .enb_1_32_0(enb_1_32_0),
                                     .dinReg2_0_re(dinReg2_0_re),  // sfix13_En12
                                     .coefIn_0(CoefOut_0),  // sfix16_En15
                                     .coefIn_1(CoefOut_1),  // sfix16_En15
                                     .coefIn_2(CoefOut_2),  // sfix16_En15
                                     .coefIn_3(CoefOut_3),  // sfix16_En15
                                     .coefIn_4(CoefOut_4),  // sfix16_En15
                                     .coefIn_5(CoefOut_5),  // sfix16_En15
                                     .coefIn_6(CoefOut_6),  // sfix16_En15
                                     .coefIn_7(CoefOut_7),  // sfix16_En15
                                     .coefIn_8(CoefOut_8),  // sfix16_En15
                                     .coefIn_9(CoefOut_9),  // sfix16_En15
                                     .coefIn_10(CoefOut_10),  // sfix16_En15
                                     .coefIn_11(CoefOut_11),  // sfix16_En15
                                     .coefIn_12(CoefOut_12),  // sfix16_En15
                                     .coefIn_13(CoefOut_13),  // sfix16_En15
                                     .coefIn_14(CoefOut_14),  // sfix16_En15
                                     .coefIn_15(CoefOut_15),  // sfix16_En15
                                     .coefIn_16(CoefOut_16),  // sfix16_En15
                                     .coefIn_17(CoefOut_17),  // sfix16_En15
                                     .coefIn_18(CoefOut_18),  // sfix16_En15
                                     .coefIn_19(CoefOut_19),  // sfix16_En15
                                     .coefIn_20(CoefOut_20),  // sfix16_En15
                                     .coefIn_21(CoefOut_21),  // sfix16_En15
                                     .coefIn_22(CoefOut_22),  // sfix16_En15
                                     .coefIn_23(CoefOut_23),  // sfix16_En15
                                     .coefIn_24(CoefOut_24),  // sfix16_En15
                                     .dinRegVld(dinReg2Vld),
                                     .syncReset(syncReset),
                                     .dout_1_re(dout_1_re)  // sfix16_En15
                                     );

  assign dataOut_re = dout_1_re;

  always @(posedge clk or negedge rst_n)
    begin : intdelay_4_process
      if (rst_n == 1'b0) begin
        dinReg_0_im <= 13'sb0000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg_0_im <= 13'sb0000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_im <= dataIn_im;
            end
          end
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : intdelay_5_process
      if (rst_n == 1'b0) begin
        dinReg2_0_im <= 13'sb0000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_im <= 13'sb0000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_im <= dinReg_0_im;
            end
          end
        end
      end
    end



  subFilter_block2 subFilter_1_im_3 (.clk(clk),
                                     .rst_n(rst_n),
                                     .enb_1_32_0(enb_1_32_0),
                                     .dinReg2_0_re(dinReg2_0_im),  // sfix13_En12
                                     .coefIn_0(CoefOut_0),  // sfix16_En15
                                     .coefIn_1(CoefOut_1),  // sfix16_En15
                                     .coefIn_2(CoefOut_2),  // sfix16_En15
                                     .coefIn_3(CoefOut_3),  // sfix16_En15
                                     .coefIn_4(CoefOut_4),  // sfix16_En15
                                     .coefIn_5(CoefOut_5),  // sfix16_En15
                                     .coefIn_6(CoefOut_6),  // sfix16_En15
                                     .coefIn_7(CoefOut_7),  // sfix16_En15
                                     .coefIn_8(CoefOut_8),  // sfix16_En15
                                     .coefIn_9(CoefOut_9),  // sfix16_En15
                                     .coefIn_10(CoefOut_10),  // sfix16_En15
                                     .coefIn_11(CoefOut_11),  // sfix16_En15
                                     .coefIn_12(CoefOut_12),  // sfix16_En15
                                     .coefIn_13(CoefOut_13),  // sfix16_En15
                                     .coefIn_14(CoefOut_14),  // sfix16_En15
                                     .coefIn_15(CoefOut_15),  // sfix16_En15
                                     .coefIn_16(CoefOut_16),  // sfix16_En15
                                     .coefIn_17(CoefOut_17),  // sfix16_En15
                                     .coefIn_18(CoefOut_18),  // sfix16_En15
                                     .coefIn_19(CoefOut_19),  // sfix16_En15
                                     .coefIn_20(CoefOut_20),  // sfix16_En15
                                     .coefIn_21(CoefOut_21),  // sfix16_En15
                                     .coefIn_22(CoefOut_22),  // sfix16_En15
                                     .coefIn_23(CoefOut_23),  // sfix16_En15
                                     .coefIn_24(CoefOut_24),  // sfix16_En15
                                     .dinRegVld(dinReg2Vld),
                                     .syncReset(syncReset),
                                     .dout_1_re(dout_1_im)  // sfix16_En15
                                     );

  assign dataOut_im = dout_1_im;

endmodule  // Filter_block2

