// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_blocked_total_v2\scpa_ppfir_blocked_total\FIR_Interpolator.v
// Created: 2025-04-08 12:29:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIR_Interpolator
// Source Path: scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR Interpolator
// Hierarchy Level: 2
// Model version: 1.91
// 
// HDLFIRInterpolation
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIR_Interpolator
          (clk,
           rst_n,
           enb_1_32_0,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re_0,
           dataOut_re_1,
           dataOut_re_2,
           dataOut_re_3,
           dataOut_im_0,
           dataOut_im_1,
           dataOut_im_2,
           dataOut_im_3);


  input   clk;
  input   rst_n;
  input   enb_1_32_0;
  input   signed [12:0] dataIn_re;  // sfix13_En12
  input   signed [12:0] dataIn_im;  // sfix13_En12
  input   validIn;
  output  signed [15:0] dataOut_re_0;  // sfix16_En15
  output  signed [15:0] dataOut_re_1;  // sfix16_En15
  output  signed [15:0] dataOut_re_2;  // sfix16_En15
  output  signed [15:0] dataOut_re_3;  // sfix16_En15
  output  signed [15:0] dataOut_im_0;  // sfix16_En15
  output  signed [15:0] dataOut_im_1;  // sfix16_En15
  output  signed [15:0] dataOut_im_2;  // sfix16_En15
  output  signed [15:0] dataOut_im_3;  // sfix16_En15


  wire syncReset;
  wire signed [15:0] FIROutput2_re;  // sfix16_En15
  wire signed [15:0] FIROutput2_im;  // sfix16_En15
  wire FIRValid2;
  wire signed [15:0] FIRVector_re [0:3];  // sfix16_En15 [4]
  wire signed [15:0] FIRVector_im [0:3];  // sfix16_En15 [4]
  wire signed [15:0] FIROutput1_re;  // sfix16_En15
  wire signed [15:0] FIROutput1_im;  // sfix16_En15
  wire FIRValid1;
  reg signed [15:0] intdelay_reg_re [0:10];  // sfix16_En15 [11]
  reg signed [15:0] intdelay_reg_im [0:10];  // sfix16_En15 [11]
  reg signed [15:0] intdelay_reg_next_re [0:10];  // sfix16_En15 [11]
  reg signed [15:0] intdelay_reg_next_im [0:10];  // sfix16_En15 [11]
  reg signed [15:0] FIROutputCastDB1_re;  // sfix16_En15
  reg signed [15:0] FIROutputCastDB1_im;  // sfix16_En15
  wire signed [15:0] FIROutput3_re;  // sfix16_En15
  wire signed [15:0] FIROutput3_im;  // sfix16_En15
  wire signed [15:0] FIROutput4_re;  // sfix16_En15
  wire signed [15:0] FIROutput4_im;  // sfix16_En15
  wire signed [15:0] FIRVector_re_1 [0:3];  // sfix16_En15 [4]
  wire signed [15:0] FIRVector_im_1 [0:3];  // sfix16_En15 [4]
  reg signed [15:0] FIRVector_re_2 [0:3];  // sfix16_En15 [4]
  reg signed [15:0] FIRVector_im_2 [0:3];  // sfix16_En15 [4]
  reg signed [15:0] dataOut_re [0:3];  // sfix16_En15 [4]
  reg signed [15:0] dataOut_im [0:3];  // sfix16_En15 [4]
  reg signed [31:0] intdelay_t_0_0;  // int32
  reg signed [31:0] intdelay_t_0_1;  // int32
  reg signed [31:0] intdelay_t_1;  // int32
  reg signed [31:0] mux_t_0_0;  // int32
  reg signed [31:0] mux_t_1;  // int32
  reg signed [31:0] intdelay_t_0;  // int32


  assign syncReset = 1'b0;



  FIRFilter2 filterInstantiation_4 (.clk(clk),
                                    .rst_n(rst_n),
                                    .enb_1_32_0(enb_1_32_0),
                                    .dataIn_re(dataIn_re),  // sfix13_En12
                                    .dataIn_im(dataIn_im),  // sfix13_En12
                                    .validIn(validIn),
                                    .dataOut_re(FIROutput2_re),  // sfix16_En15
                                    .dataOut_im(FIROutput2_im),  // sfix16_En15
                                    .validOut(FIRValid2)
                                    );

  assign FIRVector_re[0] = 16'sb0000000000000000;
  assign FIRVector_im[0] = 16'sb0000000000000000;
  assign FIRVector_re[1] = 16'sb0000000000000000;
  assign FIRVector_im[1] = 16'sb0000000000000000;
  assign FIRVector_re[2] = 16'sb0000000000000000;
  assign FIRVector_im[2] = 16'sb0000000000000000;
  assign FIRVector_re[3] = 16'sb0000000000000000;
  assign FIRVector_im[3] = 16'sb0000000000000000;



  FIRFilter1 filterInstantiation_1_1 (.clk(clk),
                                      .rst_n(rst_n),
                                      .enb_1_32_0(enb_1_32_0),
                                      .dataIn_re(dataIn_re),  // sfix13_En12
                                      .dataIn_im(dataIn_im),  // sfix13_En12
                                      .validIn(validIn),
                                      .dataOut_re(FIROutput1_re),  // sfix16_En15
                                      .dataOut_im(FIROutput1_im),  // sfix16_En15
                                      .validOut(FIRValid1)
                                      );

  always @(posedge clk or negedge rst_n)
    begin : intdelay_process
      if (rst_n == 1'b0) begin
        for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd10; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
          intdelay_reg_re[intdelay_t_1] <= 16'sb0000000000000000;
          intdelay_reg_im[intdelay_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd10; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
              intdelay_reg_re[intdelay_t_1] <= 16'sb0000000000000000;
              intdelay_reg_im[intdelay_t_1] <= 16'sb0000000000000000;
            end
          end
          else begin
            if (FIRValid1) begin
              for(intdelay_t_0_1 = 32'sd0; intdelay_t_0_1 <= 32'sd10; intdelay_t_0_1 = intdelay_t_0_1 + 
                32'sd1) begin
                intdelay_reg_re[intdelay_t_0_1] <= intdelay_reg_next_re[intdelay_t_0_1];
                intdelay_reg_im[intdelay_t_0_1] <= intdelay_reg_next_im[intdelay_t_0_1];
              end
            end
          end
        end
      end
    end

  always @* begin
    FIROutputCastDB1_re = intdelay_reg_re[10];
    FIROutputCastDB1_im = intdelay_reg_im[10];
    intdelay_reg_next_re[0] = FIROutput1_re;
    intdelay_reg_next_im[0] = FIROutput1_im;

    for(intdelay_t_0_0 = 32'sd0; intdelay_t_0_0 <= 32'sd9; intdelay_t_0_0 = intdelay_t_0_0 + 32'sd1) begin
      intdelay_reg_next_re[intdelay_t_0_0 + 32'sd1] = intdelay_reg_re[intdelay_t_0_0];
      intdelay_reg_next_im[intdelay_t_0_0 + 32'sd1] = intdelay_reg_im[intdelay_t_0_0];
    end

  end



  FIRFilter3 filterInstantiation_2_1 (.clk(clk),
                                      .rst_n(rst_n),
                                      .enb_1_32_0(enb_1_32_0),
                                      .dataIn_re(dataIn_re),  // sfix13_En12
                                      .dataIn_im(dataIn_im),  // sfix13_En12
                                      .validIn(validIn),
                                      .dataOut_re(FIROutput3_re),  // sfix16_En15
                                      .dataOut_im(FIROutput3_im)  // sfix16_En15
                                      );

  FIRFilter4 filterInstantiation_3_1 (.clk(clk),
                                      .rst_n(rst_n),
                                      .enb_1_32_0(enb_1_32_0),
                                      .dataIn_re(dataIn_re),  // sfix13_En12
                                      .dataIn_im(dataIn_im),  // sfix13_En12
                                      .validIn(validIn),
                                      .dataOut_re(FIROutput4_re),  // sfix16_En15
                                      .dataOut_im(FIROutput4_im)  // sfix16_En15
                                      );

  assign FIRVector_re_1[0] = FIROutputCastDB1_re;
  assign FIRVector_re_1[1] = FIROutput2_re;
  assign FIRVector_re_1[2] = FIROutput3_re;
  assign FIRVector_re_1[3] = FIROutput4_re;

  assign FIRVector_im_1[0] = FIROutputCastDB1_im;
  assign FIRVector_im_1[1] = FIROutput2_im;
  assign FIRVector_im_1[2] = FIROutput3_im;
  assign FIRVector_im_1[3] = FIROutput4_im;

  always @* begin
    if (FIRValid2 == 1'b0) begin
      for(mux_t_1 = 32'sd0; mux_t_1 <= 32'sd3; mux_t_1 = mux_t_1 + 32'sd1) begin
        FIRVector_re_2[mux_t_1] = FIRVector_re[mux_t_1];
        FIRVector_im_2[mux_t_1] = FIRVector_im[mux_t_1];
      end
    end
    else begin
      for(mux_t_0_0 = 32'sd0; mux_t_0_0 <= 32'sd3; mux_t_0_0 = mux_t_0_0 + 32'sd1) begin
        FIRVector_re_2[mux_t_0_0] = FIRVector_re_1[mux_t_0_0];
        FIRVector_im_2[mux_t_0_0] = FIRVector_im_1[mux_t_0_0];
      end
    end
  end



  always @(posedge clk or negedge rst_n)
    begin : intdelay_1_process
      if (rst_n == 1'b0) begin
        for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd3; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
          dataOut_re[intdelay_t_1] <= 16'sb0000000000000000;
          dataOut_im[intdelay_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            for(intdelay_t_1 = 32'sd0; intdelay_t_1 <= 32'sd3; intdelay_t_1 = intdelay_t_1 + 32'sd1) begin
              dataOut_re[intdelay_t_1] <= 16'sb0000000000000000;
              dataOut_im[intdelay_t_1] <= 16'sb0000000000000000;
            end
          end
          else begin
            for(intdelay_t_0 = 32'sd0; intdelay_t_0 <= 32'sd3; intdelay_t_0 = intdelay_t_0 + 32'sd1) begin
              dataOut_re[intdelay_t_0] <= FIRVector_re_2[intdelay_t_0];
              dataOut_im[intdelay_t_0] <= FIRVector_im_2[intdelay_t_0];
            end
          end
        end
      end
    end



  assign dataOut_re_0 = dataOut_re[0];

  assign dataOut_re_1 = dataOut_re[1];

  assign dataOut_re_2 = dataOut_re[2];

  assign dataOut_re_3 = dataOut_re[3];

  assign dataOut_im_0 = dataOut_im[0];

  assign dataOut_im_1 = dataOut_im[1];

  assign dataOut_im_2 = dataOut_im[2];

  assign dataOut_im_3 = dataOut_im[3];

endmodule  // FIR_Interpolator

