// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_blocked_total_v2\scpa_ppfir_blocked_total\FIRFilter4.v
// Created: 2025-04-08 12:29:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FIRFilter4

// Source Path: scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR Interpolator/scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR 
// Interpolator/FIRFilter
// Hierarchy Level: 3
// Model version: 1.91
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FIRFilter4
          (clk,
           rst_n,
           enb_1_32_0,
           dataIn_re,
           dataIn_im,
           validIn,
           dataOut_re,
           dataOut_im);


  input   clk;
  input   rst_n;
  input   enb_1_32_0;
  input   signed [12:0] dataIn_re;  // sfix13_En12
  input   signed [12:0] dataIn_im;  // sfix13_En12
  input   validIn;
  output  signed [15:0] dataOut_re;  // sfix16_En15
  output  signed [15:0] dataOut_im;  // sfix16_En15


  wire syncReset;


  assign syncReset = 1'b0;



  Filter_block2 FilterBank_3 (.clk(clk),
                              .rst_n(rst_n),
                              .enb_1_32_0(enb_1_32_0),
                              .dataIn_re(dataIn_re),  // sfix13_En12
                              .dataIn_im(dataIn_im),  // sfix13_En12
                              .validIn(validIn),
                              .syncReset(syncReset),
                              .dataOut_re(dataOut_re),  // sfix16_En15
                              .dataOut_im(dataOut_im)  // sfix16_En15
                              );

endmodule  // FIRFilter4

