// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_hybrid\scpa_ppfir_blocked_hybrid\pp_fir_top_half.v
// Created: 2026-01-15 14:01:13
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_fir_top_half
// Source Path: scpa_ppfir_blocked_hybrid/scpa_dig_ana_ppfir/pp_fir_blocked/pp_fir_top_half
// Hierarchy Level: 2
// Model version: 1.71
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_fir_top_half
          (clk_1_8,
           rst_n_1_8,
           enb_1_8_0,
           In1_re,
           In1_im,
           mag_re_6,
           sign_re_6,
           mag_im_6,
           sign_im_6,
           mag_re_1,
           sign_re_1,
           mag_im_1,
           sign_im_1,
           mag_re_5,
           sign_re_5,
           mag_im_5,
           sign_im_5,
           mag_re_2,
           sign_re_2,
           mag_im_2,
           sign_im_2);


  input   clk_1_8;
  input   rst_n_1_8;
  input   enb_1_8_0;
  input   signed [15:0] In1_re;  // sfix16_En15
  input   signed [15:0] In1_im;  // sfix16_En15
  output  [7:0] mag_re_6;  // uint8
  output  sign_re_6;  // ufix1
  output  [7:0] mag_im_6;  // uint8
  output  sign_im_6;  // ufix1
  output  [7:0] mag_re_1;  // uint8
  output  sign_re_1;  // ufix1
  output  [7:0] mag_im_1;  // uint8
  output  sign_im_1;  // ufix1
  output  [7:0] mag_re_5;  // uint8
  output  sign_re_5;  // ufix1
  output  [7:0] mag_im_5;  // uint8
  output  sign_im_5;  // ufix1
  output  [7:0] mag_re_2;  // uint8
  output  sign_re_2;  // ufix1
  output  [7:0] mag_im_2;  // uint8
  output  sign_im_2;  // ufix1


  wire [7:0] pp_fir_u_6_out1;  // uint8
  wire pp_fir_u_6_out2;  // ufix1
  wire [7:0] pp_fir_u_6_out3;  // uint8
  wire pp_fir_u_6_out4;  // ufix1
  wire [7:0] pp_fir_u_1_out1;  // uint8
  wire pp_fir_u_1_out2;  // ufix1
  wire [7:0] pp_fir_u_1_out3;  // uint8
  wire pp_fir_u_1_out4;  // ufix1
  wire [7:0] pp_fir_u_5_out1;  // uint8
  wire pp_fir_u_5_out2;  // ufix1
  wire [7:0] pp_fir_u_5_out3;  // uint8
  wire pp_fir_u_5_out4;  // ufix1
  wire [7:0] pp_fir_u_2_out1;  // uint8
  wire pp_fir_u_2_out2;  // ufix1
  wire [7:0] pp_fir_u_2_out3;  // uint8
  wire pp_fir_u_2_out4;  // ufix1


  pp_fir_u_6 pp_fir_u_6_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_6_out1),  // uint8
                             .sign_re(pp_fir_u_6_out2),  // ufix1
                             .mag_im(pp_fir_u_6_out3),  // uint8
                             .sign_im(pp_fir_u_6_out4)  // ufix1
                             );

  assign mag_re_6 = pp_fir_u_6_out1;

  assign sign_re_6 = pp_fir_u_6_out2;

  assign mag_im_6 = pp_fir_u_6_out3;

  assign sign_im_6 = pp_fir_u_6_out4;

  pp_fir_u_1 pp_fir_u_1_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_1_out1),  // uint8
                             .sign_re(pp_fir_u_1_out2),  // ufix1
                             .mag_im(pp_fir_u_1_out3),  // uint8
                             .sign_im(pp_fir_u_1_out4)  // ufix1
                             );

  assign mag_re_1 = pp_fir_u_1_out1;

  assign sign_re_1 = pp_fir_u_1_out2;

  assign mag_im_1 = pp_fir_u_1_out3;

  assign sign_im_1 = pp_fir_u_1_out4;

  pp_fir_u_5 pp_fir_u_5_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_5_out1),  // uint8
                             .sign_re(pp_fir_u_5_out2),  // ufix1
                             .mag_im(pp_fir_u_5_out3),  // uint8
                             .sign_im(pp_fir_u_5_out4)  // ufix1
                             );

  assign mag_re_5 = pp_fir_u_5_out1;

  assign sign_re_5 = pp_fir_u_5_out2;

  assign mag_im_5 = pp_fir_u_5_out3;

  assign sign_im_5 = pp_fir_u_5_out4;

  pp_fir_u_2 pp_fir_u_2_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_2_out1),  // uint8
                             .sign_re(pp_fir_u_2_out2),  // ufix1
                             .mag_im(pp_fir_u_2_out3),  // uint8
                             .sign_im(pp_fir_u_2_out4)  // ufix1
                             );

  assign mag_re_2 = pp_fir_u_2_out1;

  assign sign_re_2 = pp_fir_u_2_out2;

  assign mag_im_2 = pp_fir_u_2_out3;

  assign sign_im_2 = pp_fir_u_2_out4;

endmodule  // pp_fir_top_half

