// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_hybrid\scpa_ppfir_blocked_hybrid\pp_fir_7.v
// Created: 2026-01-15 14:01:13
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_fir_7

// Source Path: scpa_ppfir_blocked_hybrid/scpa_dig_ana_ppfir/pp_fir_blocked/pp_fir_bottom_half/pp_fir_u_7/pp_fir_7
// Hierarchy Level: 4
// Model version: 1.71
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_fir_7
          (clk_1_8,
           rst_n_1_8,
           enb_1_8_0,
           pp_fir_7_in_re,
           pp_fir_7_in_im,
           pp_fir_7_out_re,
           pp_fir_7_out_im);


  input   clk_1_8;
  input   rst_n_1_8;
  input   enb_1_8_0;
  input   signed [15:0] pp_fir_7_in_re;  // sfix16_En15
  input   signed [15:0] pp_fir_7_in_im;  // sfix16_En15
  output  signed [15:0] pp_fir_7_out_re;  // sfix16_En4
  output  signed [15:0] pp_fir_7_out_im;  // sfix16_En4


  reg signed [15:0] Delay_Pipeline_reg_re [0:21];  // sfix16_En15 [22]
  reg signed [15:0] Delay_Pipeline_reg_im [0:21];  // sfix16_En15 [22]
  reg signed [15:0] Delay_Pipeline_reg_next_re [0:21];  // sfix16_En15 [22]
  reg signed [15:0] Delay_Pipeline_reg_next_im [0:21];  // sfix16_En15 [22]
  reg signed [15:0] delay_pipeline_re [0:21];  // sfix16_En15 [22]
  reg signed [15:0] delay_pipeline_im [0:21];  // sfix16_En15 [22]
  wire signed [15:0] delay_pipeline_21_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_21_im;  // sfix16_En15
  wire signed [30:0] product23_re;  // sfix31_En20
  wire signed [30:0] product23_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_20_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_20_im;  // sfix16_En15
  wire signed [30:0] product22_re;  // sfix31_En20
  wire signed [30:0] product22_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast;  // sfix33_En20
  wire signed [32:0] adder_add_cast_1;  // sfix33_En20
  wire signed [32:0] adder_add_cast_2;  // sfix33_En20
  wire signed [32:0] adder_add_cast_3;  // sfix33_En20
  wire signed [32:0] sum1_1_re;  // sfix33_En20
  wire signed [32:0] sum1_1_im;  // sfix33_En20
  reg signed [32:0] sum1_1_re_1;  // sfix33_En20
  reg signed [32:0] sum1_1_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_19_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_19_im;  // sfix16_En15
  wire signed [15:0] coeff21;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_1;  // sfix32_En20
  wire signed [30:0] product21_re;  // sfix31_En20
  wire signed [30:0] product21_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_18_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_18_im;  // sfix16_En15
  wire signed [15:0] coeff20;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_2;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_3;  // sfix32_En20
  wire signed [30:0] product20_re;  // sfix31_En20
  wire signed [30:0] product20_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_4;  // sfix33_En20
  wire signed [32:0] adder_add_cast_5;  // sfix33_En20
  wire signed [32:0] adder_add_cast_6;  // sfix33_En20
  wire signed [32:0] adder_add_cast_7;  // sfix33_En20
  wire signed [32:0] sum1_2_re;  // sfix33_En20
  wire signed [32:0] sum1_2_im;  // sfix33_En20
  reg signed [32:0] sum1_2_re_1;  // sfix33_En20
  reg signed [32:0] sum1_2_im_1;  // sfix33_En20
  wire signed [32:0] sum2_1_re;  // sfix33_En20
  wire signed [32:0] sum2_1_im;  // sfix33_En20
  reg signed [32:0] sum2_1_re_1;  // sfix33_En20
  reg signed [32:0] sum2_1_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_17_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_17_im;  // sfix16_En15
  wire signed [15:0] coeff19;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_4;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_5;  // sfix32_En20
  wire signed [30:0] product19_re;  // sfix31_En20
  wire signed [30:0] product19_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_16_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_16_im;  // sfix16_En15
  wire signed [15:0] coeff18;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_6;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_7;  // sfix32_En20
  wire signed [30:0] product18_re;  // sfix31_En20
  wire signed [30:0] product18_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_8;  // sfix33_En20
  wire signed [32:0] adder_add_cast_9;  // sfix33_En20
  wire signed [32:0] adder_add_cast_10;  // sfix33_En20
  wire signed [32:0] adder_add_cast_11;  // sfix33_En20
  wire signed [32:0] sum1_3_re;  // sfix33_En20
  wire signed [32:0] sum1_3_im;  // sfix33_En20
  reg signed [32:0] sum1_3_re_1;  // sfix33_En20
  reg signed [32:0] sum1_3_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_15_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_15_im;  // sfix16_En15
  wire signed [15:0] coeff17;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_8;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_9;  // sfix32_En20
  wire signed [30:0] product17_re;  // sfix31_En20
  wire signed [30:0] product17_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_14_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_14_im;  // sfix16_En15
  wire signed [15:0] coeff16;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_10;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_11;  // sfix32_En20
  wire signed [30:0] product16_re;  // sfix31_En20
  wire signed [30:0] product16_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_12;  // sfix33_En20
  wire signed [32:0] adder_add_cast_13;  // sfix33_En20
  wire signed [32:0] adder_add_cast_14;  // sfix33_En20
  wire signed [32:0] adder_add_cast_15;  // sfix33_En20
  wire signed [32:0] sum1_4_re;  // sfix33_En20
  wire signed [32:0] sum1_4_im;  // sfix33_En20
  reg signed [32:0] sum1_4_re_1;  // sfix33_En20
  reg signed [32:0] sum1_4_im_1;  // sfix33_En20
  wire signed [32:0] sum2_2_re;  // sfix33_En20
  wire signed [32:0] sum2_2_im;  // sfix33_En20
  reg signed [32:0] sum2_2_re_1;  // sfix33_En20
  reg signed [32:0] sum2_2_im_1;  // sfix33_En20
  wire signed [32:0] sum3_1_re;  // sfix33_En20
  wire signed [32:0] sum3_1_im;  // sfix33_En20
  reg signed [32:0] sum3_1_re_1;  // sfix33_En20
  reg signed [32:0] sum3_1_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_13_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_13_im;  // sfix16_En15
  wire signed [15:0] coeff15;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_12;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_13;  // sfix32_En20
  wire signed [30:0] product15_re;  // sfix31_En20
  wire signed [30:0] product15_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_12_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_12_im;  // sfix16_En15
  wire signed [15:0] coeff14;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_14;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_15;  // sfix32_En20
  wire signed [30:0] product14_re;  // sfix31_En20
  wire signed [30:0] product14_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_16;  // sfix33_En20
  wire signed [32:0] adder_add_cast_17;  // sfix33_En20
  wire signed [32:0] adder_add_cast_18;  // sfix33_En20
  wire signed [32:0] adder_add_cast_19;  // sfix33_En20
  wire signed [32:0] sum1_5_re;  // sfix33_En20
  wire signed [32:0] sum1_5_im;  // sfix33_En20
  reg signed [32:0] sum1_5_re_1;  // sfix33_En20
  reg signed [32:0] sum1_5_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_11_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_11_im;  // sfix16_En15
  wire signed [15:0] coeff13;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_16;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_17;  // sfix32_En20
  wire signed [30:0] product13_re;  // sfix31_En20
  wire signed [30:0] product13_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_10_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_10_im;  // sfix16_En15
  wire signed [15:0] coeff12;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_18;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_19;  // sfix32_En20
  wire signed [30:0] product12_re;  // sfix31_En20
  wire signed [30:0] product12_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_20;  // sfix33_En20
  wire signed [32:0] adder_add_cast_21;  // sfix33_En20
  wire signed [32:0] adder_add_cast_22;  // sfix33_En20
  wire signed [32:0] adder_add_cast_23;  // sfix33_En20
  wire signed [32:0] sum1_6_re;  // sfix33_En20
  wire signed [32:0] sum1_6_im;  // sfix33_En20
  reg signed [32:0] sum1_6_re_1;  // sfix33_En20
  reg signed [32:0] sum1_6_im_1;  // sfix33_En20
  wire signed [32:0] sum2_3_re;  // sfix33_En20
  wire signed [32:0] sum2_3_im;  // sfix33_En20
  reg signed [32:0] sum2_3_re_1;  // sfix33_En20
  reg signed [32:0] sum2_3_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_9_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_9_im;  // sfix16_En15
  wire signed [15:0] coeff11;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_20;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_21;  // sfix32_En20
  wire signed [30:0] product11_re;  // sfix31_En20
  wire signed [30:0] product11_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_8_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_8_im;  // sfix16_En15
  wire signed [15:0] coeff10;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_22;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_23;  // sfix32_En20
  wire signed [30:0] product10_re;  // sfix31_En20
  wire signed [30:0] product10_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_24;  // sfix33_En20
  wire signed [32:0] adder_add_cast_25;  // sfix33_En20
  wire signed [32:0] adder_add_cast_26;  // sfix33_En20
  wire signed [32:0] adder_add_cast_27;  // sfix33_En20
  wire signed [32:0] sum1_7_re;  // sfix33_En20
  wire signed [32:0] sum1_7_im;  // sfix33_En20
  reg signed [32:0] sum1_7_re_1;  // sfix33_En20
  reg signed [32:0] sum1_7_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_7_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_7_im;  // sfix16_En15
  wire signed [15:0] coeff9;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_24;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_25;  // sfix32_En20
  wire signed [30:0] product9_re;  // sfix31_En20
  wire signed [30:0] product9_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_6_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_6_im;  // sfix16_En15
  wire signed [15:0] coeff8;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_26;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_27;  // sfix32_En20
  wire signed [30:0] product8_re;  // sfix31_En20
  wire signed [30:0] product8_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_28;  // sfix33_En20
  wire signed [32:0] adder_add_cast_29;  // sfix33_En20
  wire signed [32:0] adder_add_cast_30;  // sfix33_En20
  wire signed [32:0] adder_add_cast_31;  // sfix33_En20
  wire signed [32:0] sum1_8_re;  // sfix33_En20
  wire signed [32:0] sum1_8_im;  // sfix33_En20
  reg signed [32:0] sum1_8_re_1;  // sfix33_En20
  reg signed [32:0] sum1_8_im_1;  // sfix33_En20
  wire signed [32:0] sum2_4_re;  // sfix33_En20
  wire signed [32:0] sum2_4_im;  // sfix33_En20
  reg signed [32:0] sum2_4_re_1;  // sfix33_En20
  reg signed [32:0] sum2_4_im_1;  // sfix33_En20
  wire signed [32:0] sum3_2_re;  // sfix33_En20
  wire signed [32:0] sum3_2_im;  // sfix33_En20
  reg signed [32:0] sum3_2_re_1;  // sfix33_En20
  reg signed [32:0] sum3_2_im_1;  // sfix33_En20
  wire signed [32:0] sum4_1_re;  // sfix33_En20
  wire signed [32:0] sum4_1_im;  // sfix33_En20
  reg signed [32:0] sum4_1_re_1;  // sfix33_En20
  reg signed [32:0] sum4_1_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_5_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_5_im;  // sfix16_En15
  wire signed [15:0] coeff7;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_28;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_29;  // sfix32_En20
  wire signed [30:0] product7_re;  // sfix31_En20
  wire signed [30:0] product7_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_4_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_4_im;  // sfix16_En15
  wire signed [15:0] coeff6;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_30;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_31;  // sfix32_En20
  wire signed [30:0] product6_re;  // sfix31_En20
  wire signed [30:0] product6_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_32;  // sfix33_En20
  wire signed [32:0] adder_add_cast_33;  // sfix33_En20
  wire signed [32:0] adder_add_cast_34;  // sfix33_En20
  wire signed [32:0] adder_add_cast_35;  // sfix33_En20
  wire signed [32:0] sum1_9_re;  // sfix33_En20
  wire signed [32:0] sum1_9_im;  // sfix33_En20
  reg signed [32:0] sum1_9_re_1;  // sfix33_En20
  reg signed [32:0] sum1_9_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_3_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_3_im;  // sfix16_En15
  wire signed [15:0] coeff5;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_32;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_33;  // sfix32_En20
  wire signed [30:0] product5_re;  // sfix31_En20
  wire signed [30:0] product5_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_2_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_2_im;  // sfix16_En15
  wire signed [15:0] coeff4;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_34;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_35;  // sfix32_En20
  wire signed [30:0] product4_re;  // sfix31_En20
  wire signed [30:0] product4_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_36;  // sfix33_En20
  wire signed [32:0] adder_add_cast_37;  // sfix33_En20
  wire signed [32:0] adder_add_cast_38;  // sfix33_En20
  wire signed [32:0] adder_add_cast_39;  // sfix33_En20
  wire signed [32:0] sum1_10_re;  // sfix33_En20
  wire signed [32:0] sum1_10_im;  // sfix33_En20
  reg signed [32:0] sum1_10_re_1;  // sfix33_En20
  reg signed [32:0] sum1_10_im_1;  // sfix33_En20
  wire signed [32:0] sum2_5_re;  // sfix33_En20
  wire signed [32:0] sum2_5_im;  // sfix33_En20
  reg signed [32:0] sum2_5_re_1;  // sfix33_En20
  reg signed [32:0] sum2_5_im_1;  // sfix33_En20
  wire signed [15:0] delay_pipeline_1_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_1_im;  // sfix16_En15
  wire signed [15:0] coeff3;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_36;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_37;  // sfix32_En20
  wire signed [30:0] product3_re;  // sfix31_En20
  wire signed [30:0] product3_im;  // sfix31_En20
  wire signed [15:0] delay_pipeline_0_re;  // sfix16_En15
  wire signed [15:0] delay_pipeline_0_im;  // sfix16_En15
  wire signed [15:0] coeff2;  // sfix16_En5
  wire signed [31:0] multiplier_mul_temp_38;  // sfix32_En20
  wire signed [31:0] multiplier_mul_temp_39;  // sfix32_En20
  wire signed [30:0] product2_re;  // sfix31_En20
  wire signed [30:0] product2_im;  // sfix31_En20
  wire signed [32:0] adder_add_cast_40;  // sfix33_En20
  wire signed [32:0] adder_add_cast_41;  // sfix33_En20
  wire signed [32:0] adder_add_cast_42;  // sfix33_En20
  wire signed [32:0] adder_add_cast_43;  // sfix33_En20
  wire signed [32:0] sum1_11_re;  // sfix33_En20
  wire signed [32:0] sum1_11_im;  // sfix33_En20
  reg signed [32:0] sum1_11_re_1;  // sfix33_En20
  reg signed [32:0] sum1_11_im_1;  // sfix33_En20
  wire signed [30:0] product1_re;  // sfix31_En20
  wire signed [30:0] product1_im;  // sfix31_En20
  reg signed [30:0] product1_re_1;  // sfix31_En20
  reg signed [30:0] product1_im_1;  // sfix31_En20
  wire signed [32:0] adder_add_cast_44;  // sfix33_En20
  wire signed [32:0] adder_add_cast_45;  // sfix33_En20
  wire signed [32:0] sum2_6_re;  // sfix33_En20
  wire signed [32:0] sum2_6_im;  // sfix33_En20
  reg signed [32:0] sum2_6_re_1;  // sfix33_En20
  reg signed [32:0] sum2_6_im_1;  // sfix33_En20
  wire signed [32:0] sum3_3_re;  // sfix33_En20
  wire signed [32:0] sum3_3_im;  // sfix33_En20
  reg signed [32:0] sum3_3_re_1;  // sfix33_En20
  reg signed [32:0] sum3_3_im_1;  // sfix33_En20
  reg signed [32:0] sum3_3_re_2;  // sfix33_En20
  reg signed [32:0] sum3_3_im_2;  // sfix33_En20
  wire signed [32:0] sum5_1_re;  // sfix33_En20
  wire signed [32:0] sum5_1_im;  // sfix33_En20
  reg signed [32:0] sum5_1_re_1;  // sfix33_En20
  reg signed [32:0] sum5_1_im_1;  // sfix33_En20
  wire signed [15:0] output_typeconvert_re;  // sfix16_En4
  wire signed [15:0] output_typeconvert_im;  // sfix16_En4
  reg signed [31:0] Delay_Pipeline_t_0_0;  // int32
  reg signed [31:0] Delay_Pipeline_t_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_0_1;  // int32
  reg signed [31:0] Delay_Pipeline_t_1_0;  // int32


  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : Delay_Pipeline_process
      if (rst_n_1_8 == 1'b0) begin
        for(Delay_Pipeline_t_1_0 = 32'sd0; Delay_Pipeline_t_1_0 <= 32'sd21; Delay_Pipeline_t_1_0 = 
          Delay_Pipeline_t_1_0 + 32'sd1) begin
          Delay_Pipeline_reg_re[Delay_Pipeline_t_1_0] <= 16'sb0000000000000000;
          Delay_Pipeline_reg_im[Delay_Pipeline_t_1_0] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb_1_8_0) begin
          for(Delay_Pipeline_t_0_1 = 32'sd0; Delay_Pipeline_t_0_1 <= 32'sd21; Delay_Pipeline_t_0_1 = 
            Delay_Pipeline_t_0_1 + 32'sd1) begin
            Delay_Pipeline_reg_re[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_re[Delay_Pipeline_t_0_1];
            Delay_Pipeline_reg_im[Delay_Pipeline_t_0_1] <= Delay_Pipeline_reg_next_im[Delay_Pipeline_t_0_1];
          end
        end
      end
    end

  always @* begin

    for(Delay_Pipeline_t_0_0 = 32'sd0; Delay_Pipeline_t_0_0 <= 32'sd21; Delay_Pipeline_t_0_0 = 
      Delay_Pipeline_t_0_0 + 32'sd1) begin
      delay_pipeline_re[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_re[Delay_Pipeline_t_0_0];
      delay_pipeline_im[Delay_Pipeline_t_0_0] = Delay_Pipeline_reg_im[Delay_Pipeline_t_0_0];
    end

    Delay_Pipeline_reg_next_re[0] = pp_fir_7_in_re;
    Delay_Pipeline_reg_next_im[0] = pp_fir_7_in_im;

    for(Delay_Pipeline_t_1 = 32'sd0; Delay_Pipeline_t_1 <= 32'sd20; Delay_Pipeline_t_1 = Delay_Pipeline_t_1 + 
      32'sd1) begin
      Delay_Pipeline_reg_next_re[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_re[Delay_Pipeline_t_1];
      Delay_Pipeline_reg_next_im[Delay_Pipeline_t_1 + 32'sd1] = Delay_Pipeline_reg_im[Delay_Pipeline_t_1];
    end

  end



  assign delay_pipeline_21_re = delay_pipeline_re[21];

  assign delay_pipeline_21_im = delay_pipeline_im[21];

  // coeff23
  assign product23_re = 31'sb0000000000000000000000000000000;
  assign product23_im = 31'sb0000000000000000000000000000000;



  assign delay_pipeline_20_re = delay_pipeline_re[20];

  assign delay_pipeline_20_im = delay_pipeline_im[20];

  // coeff22
  assign product22_re = 31'sb0000000000000000000000000000000;
  assign product22_im = 31'sb0000000000000000000000000000000;



  assign adder_add_cast = {{2{product23_re[30]}}, product23_re};
  assign adder_add_cast_1 = {{2{product22_re[30]}}, product22_re};
  assign sum1_1_re = adder_add_cast + adder_add_cast_1;
  assign adder_add_cast_2 = {{2{product23_im[30]}}, product23_im};
  assign adder_add_cast_3 = {{2{product22_im[30]}}, product22_im};
  assign sum1_1_im = adder_add_cast_2 + adder_add_cast_3;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_1_re_1 <= 33'sh000000000;
        sum1_1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_1_re_1 <= sum1_1_re;
          sum1_1_im_1 <= sum1_1_im;
        end
      end
    end



  assign delay_pipeline_19_re = delay_pipeline_re[19];

  assign delay_pipeline_19_im = delay_pipeline_im[19];

  assign coeff21 = 16'sb0000000001000101;



  assign multiplier_mul_temp = delay_pipeline_19_re * coeff21;
  assign product21_re = multiplier_mul_temp[30:0];
  assign multiplier_mul_temp_1 = delay_pipeline_19_im * coeff21;
  assign product21_im = multiplier_mul_temp_1[30:0];



  assign delay_pipeline_18_re = delay_pipeline_re[18];

  assign delay_pipeline_18_im = delay_pipeline_im[18];

  assign coeff20 = 16'sb0000000000001010;



  assign multiplier_mul_temp_2 = delay_pipeline_18_re * coeff20;
  assign product20_re = multiplier_mul_temp_2[30:0];
  assign multiplier_mul_temp_3 = delay_pipeline_18_im * coeff20;
  assign product20_im = multiplier_mul_temp_3[30:0];



  assign adder_add_cast_4 = {{2{product21_re[30]}}, product21_re};
  assign adder_add_cast_5 = {{2{product20_re[30]}}, product20_re};
  assign sum1_2_re = adder_add_cast_4 + adder_add_cast_5;
  assign adder_add_cast_6 = {{2{product21_im[30]}}, product21_im};
  assign adder_add_cast_7 = {{2{product20_im[30]}}, product20_im};
  assign sum1_2_im = adder_add_cast_6 + adder_add_cast_7;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_1_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_2_re_1 <= 33'sh000000000;
        sum1_2_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_2_re_1 <= sum1_2_re;
          sum1_2_im_1 <= sum1_2_im;
        end
      end
    end



  assign sum2_1_re = sum1_1_re_1 + sum1_2_re_1;
  assign sum2_1_im = sum1_1_im_1 + sum1_2_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_2_process
      if (rst_n_1_8 == 1'b0) begin
        sum2_1_re_1 <= 33'sh000000000;
        sum2_1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_1_re_1 <= sum2_1_re;
          sum2_1_im_1 <= sum2_1_im;
        end
      end
    end



  assign delay_pipeline_17_re = delay_pipeline_re[17];

  assign delay_pipeline_17_im = delay_pipeline_im[17];

  assign coeff19 = 16'sb1111111110101110;



  assign multiplier_mul_temp_4 = delay_pipeline_17_re * coeff19;
  assign product19_re = multiplier_mul_temp_4[30:0];
  assign multiplier_mul_temp_5 = delay_pipeline_17_im * coeff19;
  assign product19_im = multiplier_mul_temp_5[30:0];



  assign delay_pipeline_16_re = delay_pipeline_re[16];

  assign delay_pipeline_16_im = delay_pipeline_im[16];

  assign coeff18 = 16'sb0000000011111110;



  assign multiplier_mul_temp_6 = delay_pipeline_16_re * coeff18;
  assign product18_re = multiplier_mul_temp_6[30:0];
  assign multiplier_mul_temp_7 = delay_pipeline_16_im * coeff18;
  assign product18_im = multiplier_mul_temp_7[30:0];



  assign adder_add_cast_8 = {{2{product19_re[30]}}, product19_re};
  assign adder_add_cast_9 = {{2{product18_re[30]}}, product18_re};
  assign sum1_3_re = adder_add_cast_8 + adder_add_cast_9;
  assign adder_add_cast_10 = {{2{product19_im[30]}}, product19_im};
  assign adder_add_cast_11 = {{2{product18_im[30]}}, product18_im};
  assign sum1_3_im = adder_add_cast_10 + adder_add_cast_11;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_3_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_3_re_1 <= 33'sh000000000;
        sum1_3_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_3_re_1 <= sum1_3_re;
          sum1_3_im_1 <= sum1_3_im;
        end
      end
    end



  assign delay_pipeline_15_re = delay_pipeline_re[15];

  assign delay_pipeline_15_im = delay_pipeline_im[15];

  assign coeff17 = 16'sb1111110111001111;



  assign multiplier_mul_temp_8 = delay_pipeline_15_re * coeff17;
  assign product17_re = multiplier_mul_temp_8[30:0];
  assign multiplier_mul_temp_9 = delay_pipeline_15_im * coeff17;
  assign product17_im = multiplier_mul_temp_9[30:0];



  assign delay_pipeline_14_re = delay_pipeline_re[14];

  assign delay_pipeline_14_im = delay_pipeline_im[14];

  assign coeff16 = 16'sb0000010000101111;



  assign multiplier_mul_temp_10 = delay_pipeline_14_re * coeff16;
  assign product16_re = multiplier_mul_temp_10[30:0];
  assign multiplier_mul_temp_11 = delay_pipeline_14_im * coeff16;
  assign product16_im = multiplier_mul_temp_11[30:0];



  assign adder_add_cast_12 = {{2{product17_re[30]}}, product17_re};
  assign adder_add_cast_13 = {{2{product16_re[30]}}, product16_re};
  assign sum1_4_re = adder_add_cast_12 + adder_add_cast_13;
  assign adder_add_cast_14 = {{2{product17_im[30]}}, product17_im};
  assign adder_add_cast_15 = {{2{product16_im[30]}}, product16_im};
  assign sum1_4_im = adder_add_cast_14 + adder_add_cast_15;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_4_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_4_re_1 <= 33'sh000000000;
        sum1_4_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_4_re_1 <= sum1_4_re;
          sum1_4_im_1 <= sum1_4_im;
        end
      end
    end



  assign sum2_2_re = sum1_3_re_1 + sum1_4_re_1;
  assign sum2_2_im = sum1_3_im_1 + sum1_4_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_5_process
      if (rst_n_1_8 == 1'b0) begin
        sum2_2_re_1 <= 33'sh000000000;
        sum2_2_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_2_re_1 <= sum2_2_re;
          sum2_2_im_1 <= sum2_2_im;
        end
      end
    end



  assign sum3_1_re = sum2_1_re_1 + sum2_2_re_1;
  assign sum3_1_im = sum2_1_im_1 + sum2_2_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_6_process
      if (rst_n_1_8 == 1'b0) begin
        sum3_1_re_1 <= 33'sh000000000;
        sum3_1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_1_re_1 <= sum3_1_re;
          sum3_1_im_1 <= sum3_1_im;
        end
      end
    end



  assign delay_pipeline_13_re = delay_pipeline_re[13];

  assign delay_pipeline_13_im = delay_pipeline_im[13];

  assign coeff15 = 16'sb1111100010010100;



  assign multiplier_mul_temp_12 = delay_pipeline_13_re * coeff15;
  assign product15_re = multiplier_mul_temp_12[30:0];
  assign multiplier_mul_temp_13 = delay_pipeline_13_im * coeff15;
  assign product15_im = multiplier_mul_temp_13[30:0];



  assign delay_pipeline_12_re = delay_pipeline_re[12];

  assign delay_pipeline_12_im = delay_pipeline_im[12];

  assign coeff14 = 16'sb0000110100001000;



  assign multiplier_mul_temp_14 = delay_pipeline_12_re * coeff14;
  assign product14_re = multiplier_mul_temp_14[30:0];
  assign multiplier_mul_temp_15 = delay_pipeline_12_im * coeff14;
  assign product14_im = multiplier_mul_temp_15[30:0];



  assign adder_add_cast_16 = {{2{product15_re[30]}}, product15_re};
  assign adder_add_cast_17 = {{2{product14_re[30]}}, product14_re};
  assign sum1_5_re = adder_add_cast_16 + adder_add_cast_17;
  assign adder_add_cast_18 = {{2{product15_im[30]}}, product15_im};
  assign adder_add_cast_19 = {{2{product14_im[30]}}, product14_im};
  assign sum1_5_im = adder_add_cast_18 + adder_add_cast_19;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_7_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_5_re_1 <= 33'sh000000000;
        sum1_5_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_5_re_1 <= sum1_5_re;
          sum1_5_im_1 <= sum1_5_im;
        end
      end
    end



  assign delay_pipeline_11_re = delay_pipeline_re[11];

  assign delay_pipeline_11_im = delay_pipeline_im[11];

  assign coeff13 = 16'sb1110011011101000;



  assign multiplier_mul_temp_16 = delay_pipeline_11_re * coeff13;
  assign product13_re = multiplier_mul_temp_16[30:0];
  assign multiplier_mul_temp_17 = delay_pipeline_11_im * coeff13;
  assign product13_im = multiplier_mul_temp_17[30:0];



  assign delay_pipeline_10_re = delay_pipeline_re[10];

  assign delay_pipeline_10_im = delay_pipeline_im[10];

  assign coeff12 = 16'sb0101000011001000;



  assign multiplier_mul_temp_18 = delay_pipeline_10_re * coeff12;
  assign product12_re = multiplier_mul_temp_18[30:0];
  assign multiplier_mul_temp_19 = delay_pipeline_10_im * coeff12;
  assign product12_im = multiplier_mul_temp_19[30:0];



  assign adder_add_cast_20 = {{2{product13_re[30]}}, product13_re};
  assign adder_add_cast_21 = {{2{product12_re[30]}}, product12_re};
  assign sum1_6_re = adder_add_cast_20 + adder_add_cast_21;
  assign adder_add_cast_22 = {{2{product13_im[30]}}, product13_im};
  assign adder_add_cast_23 = {{2{product12_im[30]}}, product12_im};
  assign sum1_6_im = adder_add_cast_22 + adder_add_cast_23;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_8_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_6_re_1 <= 33'sh000000000;
        sum1_6_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_6_re_1 <= sum1_6_re;
          sum1_6_im_1 <= sum1_6_im;
        end
      end
    end



  assign sum2_3_re = sum1_5_re_1 + sum1_6_re_1;
  assign sum2_3_im = sum1_5_im_1 + sum1_6_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_9_process
      if (rst_n_1_8 == 1'b0) begin
        sum2_3_re_1 <= 33'sh000000000;
        sum2_3_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_3_re_1 <= sum2_3_re;
          sum2_3_im_1 <= sum2_3_im;
        end
      end
    end



  assign delay_pipeline_9_re = delay_pipeline_re[9];

  assign delay_pipeline_9_im = delay_pipeline_im[9];

  assign coeff11 = 16'sb0101000011001000;



  assign multiplier_mul_temp_20 = delay_pipeline_9_re * coeff11;
  assign product11_re = multiplier_mul_temp_20[30:0];
  assign multiplier_mul_temp_21 = delay_pipeline_9_im * coeff11;
  assign product11_im = multiplier_mul_temp_21[30:0];



  assign delay_pipeline_8_re = delay_pipeline_re[8];

  assign delay_pipeline_8_im = delay_pipeline_im[8];

  assign coeff10 = 16'sb1110011011101000;



  assign multiplier_mul_temp_22 = delay_pipeline_8_re * coeff10;
  assign product10_re = multiplier_mul_temp_22[30:0];
  assign multiplier_mul_temp_23 = delay_pipeline_8_im * coeff10;
  assign product10_im = multiplier_mul_temp_23[30:0];



  assign adder_add_cast_24 = {{2{product11_re[30]}}, product11_re};
  assign adder_add_cast_25 = {{2{product10_re[30]}}, product10_re};
  assign sum1_7_re = adder_add_cast_24 + adder_add_cast_25;
  assign adder_add_cast_26 = {{2{product11_im[30]}}, product11_im};
  assign adder_add_cast_27 = {{2{product10_im[30]}}, product10_im};
  assign sum1_7_im = adder_add_cast_26 + adder_add_cast_27;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_10_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_7_re_1 <= 33'sh000000000;
        sum1_7_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_7_re_1 <= sum1_7_re;
          sum1_7_im_1 <= sum1_7_im;
        end
      end
    end



  assign delay_pipeline_7_re = delay_pipeline_re[7];

  assign delay_pipeline_7_im = delay_pipeline_im[7];

  assign coeff9 = 16'sb0000110100001000;



  assign multiplier_mul_temp_24 = delay_pipeline_7_re * coeff9;
  assign product9_re = multiplier_mul_temp_24[30:0];
  assign multiplier_mul_temp_25 = delay_pipeline_7_im * coeff9;
  assign product9_im = multiplier_mul_temp_25[30:0];



  assign delay_pipeline_6_re = delay_pipeline_re[6];

  assign delay_pipeline_6_im = delay_pipeline_im[6];

  assign coeff8 = 16'sb1111100010010100;



  assign multiplier_mul_temp_26 = delay_pipeline_6_re * coeff8;
  assign product8_re = multiplier_mul_temp_26[30:0];
  assign multiplier_mul_temp_27 = delay_pipeline_6_im * coeff8;
  assign product8_im = multiplier_mul_temp_27[30:0];



  assign adder_add_cast_28 = {{2{product9_re[30]}}, product9_re};
  assign adder_add_cast_29 = {{2{product8_re[30]}}, product8_re};
  assign sum1_8_re = adder_add_cast_28 + adder_add_cast_29;
  assign adder_add_cast_30 = {{2{product9_im[30]}}, product9_im};
  assign adder_add_cast_31 = {{2{product8_im[30]}}, product8_im};
  assign sum1_8_im = adder_add_cast_30 + adder_add_cast_31;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_11_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_8_re_1 <= 33'sh000000000;
        sum1_8_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_8_re_1 <= sum1_8_re;
          sum1_8_im_1 <= sum1_8_im;
        end
      end
    end



  assign sum2_4_re = sum1_7_re_1 + sum1_8_re_1;
  assign sum2_4_im = sum1_7_im_1 + sum1_8_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_12_process
      if (rst_n_1_8 == 1'b0) begin
        sum2_4_re_1 <= 33'sh000000000;
        sum2_4_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_4_re_1 <= sum2_4_re;
          sum2_4_im_1 <= sum2_4_im;
        end
      end
    end



  assign sum3_2_re = sum2_3_re_1 + sum2_4_re_1;
  assign sum3_2_im = sum2_3_im_1 + sum2_4_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_13_process
      if (rst_n_1_8 == 1'b0) begin
        sum3_2_re_1 <= 33'sh000000000;
        sum3_2_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_2_re_1 <= sum3_2_re;
          sum3_2_im_1 <= sum3_2_im;
        end
      end
    end



  assign sum4_1_re = sum3_1_re_1 + sum3_2_re_1;
  assign sum4_1_im = sum3_1_im_1 + sum3_2_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_14_process
      if (rst_n_1_8 == 1'b0) begin
        sum4_1_re_1 <= 33'sh000000000;
        sum4_1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum4_1_re_1 <= sum4_1_re;
          sum4_1_im_1 <= sum4_1_im;
        end
      end
    end



  assign delay_pipeline_5_re = delay_pipeline_re[5];

  assign delay_pipeline_5_im = delay_pipeline_im[5];

  assign coeff7 = 16'sb0000010000101111;



  assign multiplier_mul_temp_28 = delay_pipeline_5_re * coeff7;
  assign product7_re = multiplier_mul_temp_28[30:0];
  assign multiplier_mul_temp_29 = delay_pipeline_5_im * coeff7;
  assign product7_im = multiplier_mul_temp_29[30:0];



  assign delay_pipeline_4_re = delay_pipeline_re[4];

  assign delay_pipeline_4_im = delay_pipeline_im[4];

  assign coeff6 = 16'sb1111110111001111;



  assign multiplier_mul_temp_30 = delay_pipeline_4_re * coeff6;
  assign product6_re = multiplier_mul_temp_30[30:0];
  assign multiplier_mul_temp_31 = delay_pipeline_4_im * coeff6;
  assign product6_im = multiplier_mul_temp_31[30:0];



  assign adder_add_cast_32 = {{2{product7_re[30]}}, product7_re};
  assign adder_add_cast_33 = {{2{product6_re[30]}}, product6_re};
  assign sum1_9_re = adder_add_cast_32 + adder_add_cast_33;
  assign adder_add_cast_34 = {{2{product7_im[30]}}, product7_im};
  assign adder_add_cast_35 = {{2{product6_im[30]}}, product6_im};
  assign sum1_9_im = adder_add_cast_34 + adder_add_cast_35;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_15_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_9_re_1 <= 33'sh000000000;
        sum1_9_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_9_re_1 <= sum1_9_re;
          sum1_9_im_1 <= sum1_9_im;
        end
      end
    end



  assign delay_pipeline_3_re = delay_pipeline_re[3];

  assign delay_pipeline_3_im = delay_pipeline_im[3];

  assign coeff5 = 16'sb0000000011111110;



  assign multiplier_mul_temp_32 = delay_pipeline_3_re * coeff5;
  assign product5_re = multiplier_mul_temp_32[30:0];
  assign multiplier_mul_temp_33 = delay_pipeline_3_im * coeff5;
  assign product5_im = multiplier_mul_temp_33[30:0];



  assign delay_pipeline_2_re = delay_pipeline_re[2];

  assign delay_pipeline_2_im = delay_pipeline_im[2];

  assign coeff4 = 16'sb1111111110101110;



  assign multiplier_mul_temp_34 = delay_pipeline_2_re * coeff4;
  assign product4_re = multiplier_mul_temp_34[30:0];
  assign multiplier_mul_temp_35 = delay_pipeline_2_im * coeff4;
  assign product4_im = multiplier_mul_temp_35[30:0];



  assign adder_add_cast_36 = {{2{product5_re[30]}}, product5_re};
  assign adder_add_cast_37 = {{2{product4_re[30]}}, product4_re};
  assign sum1_10_re = adder_add_cast_36 + adder_add_cast_37;
  assign adder_add_cast_38 = {{2{product5_im[30]}}, product5_im};
  assign adder_add_cast_39 = {{2{product4_im[30]}}, product4_im};
  assign sum1_10_im = adder_add_cast_38 + adder_add_cast_39;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_16_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_10_re_1 <= 33'sh000000000;
        sum1_10_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_10_re_1 <= sum1_10_re;
          sum1_10_im_1 <= sum1_10_im;
        end
      end
    end



  assign sum2_5_re = sum1_9_re_1 + sum1_10_re_1;
  assign sum2_5_im = sum1_9_im_1 + sum1_10_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_17_process
      if (rst_n_1_8 == 1'b0) begin
        sum2_5_re_1 <= 33'sh000000000;
        sum2_5_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_5_re_1 <= sum2_5_re;
          sum2_5_im_1 <= sum2_5_im;
        end
      end
    end



  assign delay_pipeline_1_re = delay_pipeline_re[1];

  assign delay_pipeline_1_im = delay_pipeline_im[1];

  assign coeff3 = 16'sb0000000000001010;



  assign multiplier_mul_temp_36 = delay_pipeline_1_re * coeff3;
  assign product3_re = multiplier_mul_temp_36[30:0];
  assign multiplier_mul_temp_37 = delay_pipeline_1_im * coeff3;
  assign product3_im = multiplier_mul_temp_37[30:0];



  assign delay_pipeline_0_re = delay_pipeline_re[0];

  assign delay_pipeline_0_im = delay_pipeline_im[0];

  assign coeff2 = 16'sb0000000001000101;



  assign multiplier_mul_temp_38 = delay_pipeline_0_re * coeff2;
  assign product2_re = multiplier_mul_temp_38[30:0];
  assign multiplier_mul_temp_39 = delay_pipeline_0_im * coeff2;
  assign product2_im = multiplier_mul_temp_39[30:0];



  assign adder_add_cast_40 = {{2{product3_re[30]}}, product3_re};
  assign adder_add_cast_41 = {{2{product2_re[30]}}, product2_re};
  assign sum1_11_re = adder_add_cast_40 + adder_add_cast_41;
  assign adder_add_cast_42 = {{2{product3_im[30]}}, product3_im};
  assign adder_add_cast_43 = {{2{product2_im[30]}}, product2_im};
  assign sum1_11_im = adder_add_cast_42 + adder_add_cast_43;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_18_process
      if (rst_n_1_8 == 1'b0) begin
        sum1_11_re_1 <= 33'sh000000000;
        sum1_11_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum1_11_re_1 <= sum1_11_re;
          sum1_11_im_1 <= sum1_11_im;
        end
      end
    end



  // coeff1
  assign product1_re = 31'sb0000000000000000000000000000000;
  assign product1_im = 31'sb0000000000000000000000000000000;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : gain_out_buff_out_pipe_process
      if (rst_n_1_8 == 1'b0) begin
        product1_re_1 <= 31'sb0000000000000000000000000000000;
        product1_im_1 <= 31'sb0000000000000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          product1_re_1 <= product1_re;
          product1_im_1 <= product1_im;
        end
      end
    end



  assign adder_add_cast_44 = {{2{product1_re_1[30]}}, product1_re_1};
  assign sum2_6_re = sum1_11_re_1 + adder_add_cast_44;
  assign adder_add_cast_45 = {{2{product1_im_1[30]}}, product1_im_1};
  assign sum2_6_im = sum1_11_im_1 + adder_add_cast_45;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_19_process
      if (rst_n_1_8 == 1'b0) begin
        sum2_6_re_1 <= 33'sh000000000;
        sum2_6_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum2_6_re_1 <= sum2_6_re;
          sum2_6_im_1 <= sum2_6_im;
        end
      end
    end



  assign sum3_3_re = sum2_5_re_1 + sum2_6_re_1;
  assign sum3_3_im = sum2_5_im_1 + sum2_6_im_1;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_20_process
      if (rst_n_1_8 == 1'b0) begin
        sum3_3_re_1 <= 33'sh000000000;
        sum3_3_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_3_re_1 <= sum3_3_re;
          sum3_3_im_1 <= sum3_3_im;
        end
      end
    end



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_buff_out_pipe_pro
      if (rst_n_1_8 == 1'b0) begin
        sum3_3_re_2 <= 33'sh000000000;
        sum3_3_im_2 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum3_3_re_2 <= sum3_3_re_1;
          sum3_3_im_2 <= sum3_3_im_1;
        end
      end
    end



  assign sum5_1_re = sum4_1_re_1 + sum3_3_re_2;
  assign sum5_1_im = sum4_1_im_1 + sum3_3_im_2;



  always @(posedge clk_1_8 or negedge rst_n_1_8)
    begin : adder_out_buff_out_pipe_21_process
      if (rst_n_1_8 == 1'b0) begin
        sum5_1_re_1 <= 33'sh000000000;
        sum5_1_im_1 <= 33'sh000000000;
      end
      else begin
        if (enb_1_8_0) begin
          sum5_1_re_1 <= sum5_1_re;
          sum5_1_im_1 <= sum5_1_im;
        end
      end
    end



  assign output_typeconvert_re = sum5_1_re_1[31:16];
  assign output_typeconvert_im = sum5_1_im_1[31:16];



  assign pp_fir_7_out_re = output_typeconvert_re;

  assign pp_fir_7_out_im = output_typeconvert_im;

endmodule  // pp_fir_7

