// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_hybrid\scpa_ppfir_blocked_hybrid\pp_fir_bottom_half.v
// Created: 2026-01-15 14:01:13
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_fir_bottom_half
// Source Path: scpa_ppfir_blocked_hybrid/scpa_dig_ana_ppfir/pp_fir_blocked/pp_fir_bottom_half
// Hierarchy Level: 2
// Model version: 1.71
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_fir_bottom_half
          (clk_1_8,
           rst_n_1_8,
           enb_1_8_0,
           In1_re,
           In1_im,
           mag_re_3,
           sign_re_3,
           mag_im_3,
           sign_im_3,
           mag_re_0,
           sign_re_0,
           mag_im_0,
           sign_im_0,
           mag_re_7,
           sign_re_7,
           mag_im_7,
           sign_im_7,
           mag_re_4,
           sign_re_4,
           mag_im_4,
           sign_im_4);


  input   clk_1_8;
  input   rst_n_1_8;
  input   enb_1_8_0;
  input   signed [15:0] In1_re;  // sfix16_En15
  input   signed [15:0] In1_im;  // sfix16_En15
  output  [7:0] mag_re_3;  // uint8
  output  sign_re_3;  // ufix1
  output  [7:0] mag_im_3;  // uint8
  output  sign_im_3;  // ufix1
  output  [7:0] mag_re_0;  // uint8
  output  sign_re_0;  // ufix1
  output  [7:0] mag_im_0;  // uint8
  output  sign_im_0;  // ufix1
  output  [7:0] mag_re_7;  // uint8
  output  sign_re_7;  // ufix1
  output  [7:0] mag_im_7;  // uint8
  output  sign_im_7;  // ufix1
  output  [7:0] mag_re_4;  // uint8
  output  sign_re_4;  // ufix1
  output  [7:0] mag_im_4;  // uint8
  output  sign_im_4;  // ufix1


  wire [7:0] pp_fir_u_3_out1;  // uint8
  wire pp_fir_u_3_out2;  // ufix1
  wire [7:0] pp_fir_u_3_out3;  // uint8
  wire pp_fir_u_3_out4;  // ufix1
  wire [7:0] pp_fir_u_0_out1;  // uint8
  wire pp_fir_u_0_out2;  // ufix1
  wire [7:0] pp_fir_u_0_out3;  // uint8
  wire pp_fir_u_0_out4;  // ufix1
  wire [7:0] pp_fir_u_7_out1;  // uint8
  wire pp_fir_u_7_out2;  // ufix1
  wire [7:0] pp_fir_u_7_out3;  // uint8
  wire pp_fir_u_7_out4;  // ufix1
  wire [7:0] pp_fir_u_4_out1;  // uint8
  wire pp_fir_u_4_out2;  // ufix1
  wire [7:0] pp_fir_u_4_out3;  // uint8
  wire pp_fir_u_4_out4;  // ufix1


  pp_fir_u_3 pp_fir_u_3_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_3_out1),  // uint8
                             .sign_re(pp_fir_u_3_out2),  // ufix1
                             .mag_im(pp_fir_u_3_out3),  // uint8
                             .sign_im(pp_fir_u_3_out4)  // ufix1
                             );

  assign mag_re_3 = pp_fir_u_3_out1;

  assign sign_re_3 = pp_fir_u_3_out2;

  assign mag_im_3 = pp_fir_u_3_out3;

  assign sign_im_3 = pp_fir_u_3_out4;

  pp_fir_u_0 pp_fir_u_0_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_0_out1),  // uint8
                             .sign_re(pp_fir_u_0_out2),  // ufix1
                             .mag_im(pp_fir_u_0_out3),  // uint8
                             .sign_im(pp_fir_u_0_out4)  // ufix1
                             );

  assign mag_re_0 = pp_fir_u_0_out1;

  assign sign_re_0 = pp_fir_u_0_out2;

  assign mag_im_0 = pp_fir_u_0_out3;

  assign sign_im_0 = pp_fir_u_0_out4;

  pp_fir_u_7 pp_fir_u_7_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_7_out1),  // uint8
                             .sign_re(pp_fir_u_7_out2),  // ufix1
                             .mag_im(pp_fir_u_7_out3),  // uint8
                             .sign_im(pp_fir_u_7_out4)  // ufix1
                             );

  assign mag_re_7 = pp_fir_u_7_out1;

  assign sign_re_7 = pp_fir_u_7_out2;

  assign mag_im_7 = pp_fir_u_7_out3;

  assign sign_im_7 = pp_fir_u_7_out4;

  pp_fir_u_4 pp_fir_u_4_1_1 (.clk_1_8(clk_1_8),
                             .rst_n_1_8(rst_n_1_8),
                             .enb_1_8_0(enb_1_8_0),
                             .In1_re(In1_re),  // sfix16_En15
                             .In1_im(In1_im),  // sfix16_En15
                             .mag_re(pp_fir_u_4_out1),  // uint8
                             .sign_re(pp_fir_u_4_out2),  // ufix1
                             .mag_im(pp_fir_u_4_out3),  // uint8
                             .sign_im(pp_fir_u_4_out4)  // ufix1
                             );

  assign mag_re_4 = pp_fir_u_4_out1;

  assign sign_re_4 = pp_fir_u_4_out2;

  assign mag_im_4 = pp_fir_u_4_out3;

  assign sign_im_4 = pp_fir_u_4_out4;

endmodule  // pp_fir_bottom_half

