// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_hybrid\scpa_ppfir_blocked_hybrid\pp_fir_blocked.v
// Created: 2026-01-15 14:01:13
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_fir_blocked
// Source Path: scpa_ppfir_blocked_hybrid/scpa_dig_ana_ppfir/pp_fir_blocked
// Hierarchy Level: 1
// Model version: 1.71
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_fir_blocked
          (clk_1_8,
           rst_n_1_8,
           enb_1_8_0,
           In1_re,
           In1_im,
           Re_0,
           Re_4,
           Re_s_0,
           Re_s_4,
           Im_0,
           Im_4,
           Im_s_0,
           Im_s_4,
           Re_1,
           Re_5,
           Re_s_1,
           Re_s_5,
           Im_1,
           Im_5,
           Im_s_1,
           Im_s_5,
           Re_2,
           Re_6,
           Re_s_2,
           Re_s_6,
           Im_2,
           Im_6,
           Im_s_2,
           Im_s_6,
           Re_3,
           Re_7,
           Re_s_3,
           Re_s_7,
           Im_3,
           Im_7,
           Im_s_3,
           Im_s_7);


  input   clk_1_8;
  input   rst_n_1_8;
  input   enb_1_8_0;
  input   signed [15:0] In1_re;  // sfix16_En15
  input   signed [15:0] In1_im;  // sfix16_En15
  output  [7:0] Re_0;  // uint8
  output  [7:0] Re_4;  // uint8
  output  Re_s_0;  // ufix1
  output  Re_s_4;  // ufix1
  output  [7:0] Im_0;  // uint8
  output  [7:0] Im_4;  // uint8
  output  Im_s_0;  // ufix1
  output  Im_s_4;  // ufix1
  output  [7:0] Re_1;  // uint8
  output  [7:0] Re_5;  // uint8
  output  Re_s_1;  // ufix1
  output  Re_s_5;  // ufix1
  output  [7:0] Im_1;  // uint8
  output  [7:0] Im_5;  // uint8
  output  Im_s_1;  // ufix1
  output  Im_s_5;  // ufix1
  output  [7:0] Re_2;  // uint8
  output  [7:0] Re_6;  // uint8
  output  Re_s_2;  // ufix1
  output  Re_s_6;  // ufix1
  output  [7:0] Im_2;  // uint8
  output  [7:0] Im_6;  // uint8
  output  Im_s_2;  // ufix1
  output  Im_s_6;  // ufix1
  output  [7:0] Re_3;  // uint8
  output  [7:0] Re_7;  // uint8
  output  Re_s_3;  // ufix1
  output  Re_s_7;  // ufix1
  output  [7:0] Im_3;  // uint8
  output  [7:0] Im_7;  // uint8
  output  Im_s_3;  // ufix1
  output  Im_s_7;  // ufix1


  wire [7:0] pp_fir_bottom_half_out1;  // uint8
  wire pp_fir_bottom_half_out2;  // ufix1
  wire [7:0] pp_fir_bottom_half_out3;  // uint8
  wire pp_fir_bottom_half_out4;  // ufix1
  wire [7:0] pp_fir_bottom_half_out5;  // uint8
  wire pp_fir_bottom_half_out6;  // ufix1
  wire [7:0] pp_fir_bottom_half_out7;  // uint8
  wire pp_fir_bottom_half_out8;  // ufix1
  wire [7:0] pp_fir_bottom_half_out9;  // uint8
  wire pp_fir_bottom_half_out10;  // ufix1
  wire [7:0] pp_fir_bottom_half_out11;  // uint8
  wire pp_fir_bottom_half_out12;  // ufix1
  wire [7:0] pp_fir_bottom_half_out13;  // uint8
  wire pp_fir_bottom_half_out14;  // ufix1
  wire [7:0] pp_fir_bottom_half_out15;  // uint8
  wire pp_fir_bottom_half_out16;  // ufix1
  wire [7:0] pp_fir_top_half_out1;  // uint8
  wire pp_fir_top_half_out2;  // ufix1
  wire [7:0] pp_fir_top_half_out3;  // uint8
  wire pp_fir_top_half_out4;  // ufix1
  wire [7:0] pp_fir_top_half_out5;  // uint8
  wire pp_fir_top_half_out6;  // ufix1
  wire [7:0] pp_fir_top_half_out7;  // uint8
  wire pp_fir_top_half_out8;  // ufix1
  wire [7:0] pp_fir_top_half_out9;  // uint8
  wire pp_fir_top_half_out10;  // ufix1
  wire [7:0] pp_fir_top_half_out11;  // uint8
  wire pp_fir_top_half_out12;  // ufix1
  wire [7:0] pp_fir_top_half_out13;  // uint8
  wire pp_fir_top_half_out14;  // ufix1
  wire [7:0] pp_fir_top_half_out15;  // uint8
  wire pp_fir_top_half_out16;  // ufix1


  pp_fir_bottom_half pp_fir_bottom_half_1_1 (.clk_1_8(clk_1_8),
                                             .rst_n_1_8(rst_n_1_8),
                                             .enb_1_8_0(enb_1_8_0),
                                             .In1_re(In1_re),  // sfix16_En15
                                             .In1_im(In1_im),  // sfix16_En15
                                             .mag_re_3(pp_fir_bottom_half_out1),  // uint8
                                             .sign_re_3(pp_fir_bottom_half_out2),  // ufix1
                                             .mag_im_3(pp_fir_bottom_half_out3),  // uint8
                                             .sign_im_3(pp_fir_bottom_half_out4),  // ufix1
                                             .mag_re_0(pp_fir_bottom_half_out5),  // uint8
                                             .sign_re_0(pp_fir_bottom_half_out6),  // ufix1
                                             .mag_im_0(pp_fir_bottom_half_out7),  // uint8
                                             .sign_im_0(pp_fir_bottom_half_out8),  // ufix1
                                             .mag_re_7(pp_fir_bottom_half_out9),  // uint8
                                             .sign_re_7(pp_fir_bottom_half_out10),  // ufix1
                                             .mag_im_7(pp_fir_bottom_half_out11),  // uint8
                                             .sign_im_7(pp_fir_bottom_half_out12),  // ufix1
                                             .mag_re_4(pp_fir_bottom_half_out13),  // uint8
                                             .sign_re_4(pp_fir_bottom_half_out14),  // ufix1
                                             .mag_im_4(pp_fir_bottom_half_out15),  // uint8
                                             .sign_im_4(pp_fir_bottom_half_out16)  // ufix1
                                             );

  assign Re_0 = pp_fir_bottom_half_out5;

  assign Re_4 = pp_fir_bottom_half_out13;

  assign Re_s_0 = pp_fir_bottom_half_out6;

  assign Re_s_4 = pp_fir_bottom_half_out14;

  assign Im_0 = pp_fir_bottom_half_out7;

  assign Im_4 = pp_fir_bottom_half_out15;

  assign Im_s_0 = pp_fir_bottom_half_out8;

  assign Im_s_4 = pp_fir_bottom_half_out16;

  pp_fir_top_half pp_fir_top_half_1_1 (.clk_1_8(clk_1_8),
                                       .rst_n_1_8(rst_n_1_8),
                                       .enb_1_8_0(enb_1_8_0),
                                       .In1_re(In1_re),  // sfix16_En15
                                       .In1_im(In1_im),  // sfix16_En15
                                       .mag_re_6(pp_fir_top_half_out1),  // uint8
                                       .sign_re_6(pp_fir_top_half_out2),  // ufix1
                                       .mag_im_6(pp_fir_top_half_out3),  // uint8
                                       .sign_im_6(pp_fir_top_half_out4),  // ufix1
                                       .mag_re_1(pp_fir_top_half_out5),  // uint8
                                       .sign_re_1(pp_fir_top_half_out6),  // ufix1
                                       .mag_im_1(pp_fir_top_half_out7),  // uint8
                                       .sign_im_1(pp_fir_top_half_out8),  // ufix1
                                       .mag_re_5(pp_fir_top_half_out9),  // uint8
                                       .sign_re_5(pp_fir_top_half_out10),  // ufix1
                                       .mag_im_5(pp_fir_top_half_out11),  // uint8
                                       .sign_im_5(pp_fir_top_half_out12),  // ufix1
                                       .mag_re_2(pp_fir_top_half_out13),  // uint8
                                       .sign_re_2(pp_fir_top_half_out14),  // ufix1
                                       .mag_im_2(pp_fir_top_half_out15),  // uint8
                                       .sign_im_2(pp_fir_top_half_out16)  // ufix1
                                       );

  assign Re_1 = pp_fir_top_half_out5;

  assign Re_5 = pp_fir_top_half_out9;

  assign Re_s_1 = pp_fir_top_half_out6;

  assign Re_s_5 = pp_fir_top_half_out10;

  assign Im_1 = pp_fir_top_half_out7;

  assign Im_5 = pp_fir_top_half_out11;

  assign Im_s_1 = pp_fir_top_half_out8;

  assign Im_s_5 = pp_fir_top_half_out12;

  assign Re_2 = pp_fir_top_half_out13;

  assign Re_6 = pp_fir_top_half_out1;

  assign Re_s_2 = pp_fir_top_half_out14;

  assign Re_s_6 = pp_fir_top_half_out2;

  assign Im_2 = pp_fir_top_half_out15;

  assign Im_6 = pp_fir_top_half_out3;

  assign Im_s_2 = pp_fir_top_half_out16;

  assign Im_s_6 = pp_fir_top_half_out4;

  assign Re_3 = pp_fir_bottom_half_out1;

  assign Re_7 = pp_fir_bottom_half_out9;

  assign Re_s_3 = pp_fir_bottom_half_out2;

  assign Re_s_7 = pp_fir_bottom_half_out10;

  assign Im_3 = pp_fir_bottom_half_out3;

  assign Im_7 = pp_fir_bottom_half_out11;

  assign Im_s_3 = pp_fir_bottom_half_out4;

  assign Im_s_7 = pp_fir_bottom_half_out12;

endmodule  // pp_fir_blocked

