// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_blocked_total_v2\scpa_ppfir_blocked_total\pp_int_x4_v2.v
// Created: 2025-04-08 12:29:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pp_int_x4_v2
// Source Path: scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2
// Hierarchy Level: 1
// Model version: 1.91
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pp_int_x4_v2
          (clk,
           rst_n,
           enb_1_8_0,
           enb_1_32_0,
           enb_1_32_1,
           enb_1_8_1,
           In1_re,
           In1_im,
           Out1_re,
           Out1_im);


  input   clk;
  input   rst_n;
  input   enb_1_8_0;
  input   enb_1_32_0;
  input   enb_1_32_1;
  input   enb_1_8_1;
  input   signed [12:0] In1_re;  // sfix13_En12
  input   signed [12:0] In1_im;  // sfix13_En12
  output  signed [15:0] Out1_re;  // sfix16_En15
  output  signed [15:0] Out1_im;  // sfix16_En15


  wire Constant_out1;
  wire signed [15:0] FIR_Interpolator_out1_re_0;  // sfix16_En15
  wire signed [15:0] FIR_Interpolator_out1_re_1;  // sfix16_En15
  wire signed [15:0] FIR_Interpolator_out1_re_2;  // sfix16_En15
  wire signed [15:0] FIR_Interpolator_out1_re_3;  // sfix16_En15
  wire signed [15:0] FIR_Interpolator_out1_im_0;  // sfix16_En15
  wire signed [15:0] FIR_Interpolator_out1_im_1;  // sfix16_En15
  wire signed [15:0] FIR_Interpolator_out1_im_2;  // sfix16_En15
  wire signed [15:0] FIR_Interpolator_out1_im_3;  // sfix16_En15
  wire signed [15:0] Upsample0_zero_re;  // sfix16_En15
  wire signed [15:0] Upsample0_zero_im;  // sfix16_En15
  wire signed [15:0] Upsample0_muxout_re;  // sfix16_En15
  wire signed [15:0] Upsample0_muxout_im;  // sfix16_En15
  reg signed [15:0] Upsample0_bypass_reg_re;  // sfix16_En15
  reg signed [15:0] Upsample0_bypass_reg_im;  // sfix16_En15
  wire signed [15:0] Upsample0_bypassout_re;  // sfix16_En15
  wire signed [15:0] Upsample0_bypassout_im;  // sfix16_En15
  wire signed [15:0] Upsample1_zero_re;  // sfix16_En15
  wire signed [15:0] Upsample1_zero_im;  // sfix16_En15
  wire signed [15:0] Upsample1_muxout_re;  // sfix16_En15
  wire signed [15:0] Upsample1_muxout_im;  // sfix16_En15
  reg signed [15:0] Upsample1_bypass_reg_re;  // sfix16_En15
  reg signed [15:0] Upsample1_bypass_reg_im;  // sfix16_En15
  wire signed [15:0] Upsample1_bypassout_re;  // sfix16_En15
  wire signed [15:0] Upsample1_bypassout_im;  // sfix16_En15
  wire signed [15:0] Upsample2_zero_re;  // sfix16_En15
  wire signed [15:0] Upsample2_zero_im;  // sfix16_En15
  wire signed [15:0] Upsample2_muxout_re;  // sfix16_En15
  wire signed [15:0] Upsample2_muxout_im;  // sfix16_En15
  reg signed [15:0] Upsample2_bypass_reg_re;  // sfix16_En15
  reg signed [15:0] Upsample2_bypass_reg_im;  // sfix16_En15
  wire signed [15:0] Upsample2_bypassout_re;  // sfix16_En15
  wire signed [15:0] Upsample2_bypassout_im;  // sfix16_En15
  wire signed [15:0] Upsample3_zero_re;  // sfix16_En15
  wire signed [15:0] Upsample3_zero_im;  // sfix16_En15
  wire signed [15:0] Upsample3_muxout_re;  // sfix16_En15
  wire signed [15:0] Upsample3_muxout_im;  // sfix16_En15
  reg signed [15:0] Upsample3_bypass_reg_re;  // sfix16_En15
  reg signed [15:0] Upsample3_bypass_reg_im;  // sfix16_En15
  wire signed [15:0] Upsample3_bypassout_re;  // sfix16_En15
  wire signed [15:0] Upsample3_bypassout_im;  // sfix16_En15
  reg signed [15:0] Upsample3_out1_re;  // sfix16_En15
  reg signed [15:0] Upsample3_out1_im;  // sfix16_En15
  wire signed [31:0] Add_add_cast;  // sfix32_En15
  wire signed [31:0] Add_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add_add_temp;  // sfix32_En15
  wire signed [31:0] Add_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add_add_temp_1;  // sfix32_En15
  wire signed [15:0] Add_out1_re;  // sfix16_En15
  wire signed [15:0] Add_out1_im;  // sfix16_En15
  reg signed [15:0] Add_out1_re_1;  // sfix16_En15
  reg signed [15:0] Add_out1_im_1;  // sfix16_En15
  wire signed [31:0] Add1_add_cast;  // sfix32_En15
  wire signed [31:0] Add1_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add1_add_temp;  // sfix32_En15
  wire signed [31:0] Add1_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add1_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add1_add_temp_1;  // sfix32_En15
  wire signed [15:0] Add1_out1_re;  // sfix16_En15
  wire signed [15:0] Add1_out1_im;  // sfix16_En15
  reg signed [15:0] Add1_out1_re_1;  // sfix16_En15
  reg signed [15:0] Add1_out1_im_1;  // sfix16_En15
  wire signed [31:0] Add2_add_cast;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_1;  // sfix32_En15
  wire signed [31:0] Add2_add_temp;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_2;  // sfix32_En15
  wire signed [31:0] Add2_add_cast_3;  // sfix32_En15
  wire signed [31:0] Add2_add_temp_1;  // sfix32_En15
  wire signed [15:0] Add2_out1_re;  // sfix16_En15
  wire signed [15:0] Add2_out1_im;  // sfix16_En15


  assign Constant_out1 = 1'b1;



  FIR_Interpolator FIR_Interpolator_1_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dataIn_re(In1_re),  // sfix13_En12
                                         .dataIn_im(In1_im),  // sfix13_En12
                                         .validIn(Constant_out1),
                                         .dataOut_re_0(FIR_Interpolator_out1_re_0),  // sfix16_En15
                                         .dataOut_re_1(FIR_Interpolator_out1_re_1),  // sfix16_En15
                                         .dataOut_re_2(FIR_Interpolator_out1_re_2),  // sfix16_En15
                                         .dataOut_re_3(FIR_Interpolator_out1_re_3),  // sfix16_En15
                                         .dataOut_im_0(FIR_Interpolator_out1_im_0),  // sfix16_En15
                                         .dataOut_im_1(FIR_Interpolator_out1_im_1),  // sfix16_En15
                                         .dataOut_im_2(FIR_Interpolator_out1_im_2),  // sfix16_En15
                                         .dataOut_im_3(FIR_Interpolator_out1_im_3)  // sfix16_En15
                                         );

  assign Upsample0_zero_re = 16'sb0000000000000000;
  assign Upsample0_zero_im = 16'sb0000000000000000;



  // Upsample0: Upsample by 4, Sample offset 0 
  assign Upsample0_muxout_re = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_re_0 :
              Upsample0_zero_re);
  assign Upsample0_muxout_im = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_im_0 :
              Upsample0_zero_im);



  // Upsample bypass register
  always @(posedge clk or negedge rst_n)
    begin : Upsample0_bypass_process
      if (rst_n == 1'b0) begin
        Upsample0_bypass_reg_re <= 16'sb0000000000000000;
        Upsample0_bypass_reg_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Upsample0_bypass_reg_im <= Upsample0_muxout_im;
          Upsample0_bypass_reg_re <= Upsample0_muxout_re;
        end
      end
    end

  assign Upsample0_bypassout_re = (enb_1_8_1 == 1'b1 ? Upsample0_muxout_re :
              Upsample0_bypass_reg_re);
  assign Upsample0_bypassout_im = (enb_1_8_1 == 1'b1 ? Upsample0_muxout_im :
              Upsample0_bypass_reg_im);



  assign Upsample1_zero_re = 16'sb0000000000000000;
  assign Upsample1_zero_im = 16'sb0000000000000000;



  // Upsample1: Upsample by 4, Sample offset 0 
  assign Upsample1_muxout_re = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_re_1 :
              Upsample1_zero_re);
  assign Upsample1_muxout_im = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_im_1 :
              Upsample1_zero_im);



  // Upsample bypass register
  always @(posedge clk or negedge rst_n)
    begin : Upsample1_bypass_process
      if (rst_n == 1'b0) begin
        Upsample1_bypass_reg_re <= 16'sb0000000000000000;
        Upsample1_bypass_reg_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Upsample1_bypass_reg_im <= Upsample1_muxout_im;
          Upsample1_bypass_reg_re <= Upsample1_muxout_re;
        end
      end
    end

  assign Upsample1_bypassout_re = (enb_1_8_1 == 1'b1 ? Upsample1_muxout_re :
              Upsample1_bypass_reg_re);
  assign Upsample1_bypassout_im = (enb_1_8_1 == 1'b1 ? Upsample1_muxout_im :
              Upsample1_bypass_reg_im);



  assign Upsample2_zero_re = 16'sb0000000000000000;
  assign Upsample2_zero_im = 16'sb0000000000000000;



  // Upsample2: Upsample by 4, Sample offset 0 
  assign Upsample2_muxout_re = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_re_2 :
              Upsample2_zero_re);
  assign Upsample2_muxout_im = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_im_2 :
              Upsample2_zero_im);



  // Upsample bypass register
  always @(posedge clk or negedge rst_n)
    begin : Upsample2_bypass_process
      if (rst_n == 1'b0) begin
        Upsample2_bypass_reg_re <= 16'sb0000000000000000;
        Upsample2_bypass_reg_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Upsample2_bypass_reg_im <= Upsample2_muxout_im;
          Upsample2_bypass_reg_re <= Upsample2_muxout_re;
        end
      end
    end

  assign Upsample2_bypassout_re = (enb_1_8_1 == 1'b1 ? Upsample2_muxout_re :
              Upsample2_bypass_reg_re);
  assign Upsample2_bypassout_im = (enb_1_8_1 == 1'b1 ? Upsample2_muxout_im :
              Upsample2_bypass_reg_im);



  assign Upsample3_zero_re = 16'sb0000000000000000;
  assign Upsample3_zero_im = 16'sb0000000000000000;



  // Upsample3: Upsample by 4, Sample offset 0 
  assign Upsample3_muxout_re = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_re_3 :
              Upsample3_zero_re);
  assign Upsample3_muxout_im = (enb_1_32_1 == 1'b1 ? FIR_Interpolator_out1_im_3 :
              Upsample3_zero_im);



  // Upsample bypass register
  always @(posedge clk or negedge rst_n)
    begin : Upsample3_bypass_process
      if (rst_n == 1'b0) begin
        Upsample3_bypass_reg_re <= 16'sb0000000000000000;
        Upsample3_bypass_reg_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_8_1) begin
          Upsample3_bypass_reg_im <= Upsample3_muxout_im;
          Upsample3_bypass_reg_re <= Upsample3_muxout_re;
        end
      end
    end

  assign Upsample3_bypassout_re = (enb_1_8_1 == 1'b1 ? Upsample3_muxout_re :
              Upsample3_bypass_reg_re);
  assign Upsample3_bypassout_im = (enb_1_8_1 == 1'b1 ? Upsample3_muxout_im :
              Upsample3_bypass_reg_im);



  always @(posedge clk or negedge rst_n)
    begin : rd_0_process
      if (rst_n == 1'b0) begin
        Upsample3_out1_re <= 16'sb0000000000000000;
        Upsample3_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          Upsample3_out1_re <= Upsample3_bypassout_re;
          Upsample3_out1_im <= Upsample3_bypassout_im;
        end
      end
    end



  assign Add_add_cast = {{16{Upsample2_bypassout_re[15]}}, Upsample2_bypassout_re};
  assign Add_add_cast_1 = {{16{Upsample3_out1_re[15]}}, Upsample3_out1_re};
  assign Add_add_temp = Add_add_cast + Add_add_cast_1;
  assign Add_out1_re = Add_add_temp[15:0];
  assign Add_add_cast_2 = {{16{Upsample2_bypassout_im[15]}}, Upsample2_bypassout_im};
  assign Add_add_cast_3 = {{16{Upsample3_out1_im[15]}}, Upsample3_out1_im};
  assign Add_add_temp_1 = Add_add_cast_2 + Add_add_cast_3;
  assign Add_out1_im = Add_add_temp_1[15:0];



  always @(posedge clk or negedge rst_n)
    begin : rd_1_process
      if (rst_n == 1'b0) begin
        Add_out1_re_1 <= 16'sb0000000000000000;
        Add_out1_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          Add_out1_re_1 <= Add_out1_re;
          Add_out1_im_1 <= Add_out1_im;
        end
      end
    end



  assign Add1_add_cast = {{16{Upsample1_bypassout_re[15]}}, Upsample1_bypassout_re};
  assign Add1_add_cast_1 = {{16{Add_out1_re_1[15]}}, Add_out1_re_1};
  assign Add1_add_temp = Add1_add_cast + Add1_add_cast_1;
  assign Add1_out1_re = Add1_add_temp[15:0];
  assign Add1_add_cast_2 = {{16{Upsample1_bypassout_im[15]}}, Upsample1_bypassout_im};
  assign Add1_add_cast_3 = {{16{Add_out1_im_1[15]}}, Add_out1_im_1};
  assign Add1_add_temp_1 = Add1_add_cast_2 + Add1_add_cast_3;
  assign Add1_out1_im = Add1_add_temp_1[15:0];



  always @(posedge clk or negedge rst_n)
    begin : rd_2_process
      if (rst_n == 1'b0) begin
        Add1_out1_re_1 <= 16'sb0000000000000000;
        Add1_out1_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          Add1_out1_re_1 <= Add1_out1_re;
          Add1_out1_im_1 <= Add1_out1_im;
        end
      end
    end



  assign Add2_add_cast = {{16{Upsample0_bypassout_re[15]}}, Upsample0_bypassout_re};
  assign Add2_add_cast_1 = {{16{Add1_out1_re_1[15]}}, Add1_out1_re_1};
  assign Add2_add_temp = Add2_add_cast + Add2_add_cast_1;
  assign Add2_out1_re = Add2_add_temp[15:0];
  assign Add2_add_cast_2 = {{16{Upsample0_bypassout_im[15]}}, Upsample0_bypassout_im};
  assign Add2_add_cast_3 = {{16{Add1_out1_im_1[15]}}, Add1_out1_im_1};
  assign Add2_add_temp_1 = Add2_add_cast_2 + Add2_add_cast_3;
  assign Add2_out1_im = Add2_add_temp_1[15:0];



  assign Out1_re = Add2_out1_re;

  assign Out1_im = Add2_out1_im;

endmodule  // pp_int_x4_v2

