// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_hybrid\scpa_ppfir_blocked_hybrid\scpa_dig_ana_ppfir.v
// Created: 2026-01-13 06:37:39
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 7.8125e-11
// Target subsystem base rate: 3.125e-10
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        3.125e-10
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// Re_0                      ce_out        3.125e-10
// Re_s_0                    ce_out        3.125e-10
// Im_0                      ce_out        3.125e-10
// im_s_dig_0                    ce_out        3.125e-10
// Re_1                      ce_out        3.125e-10
// Re_s_1                    ce_out        3.125e-10
// Im_1                      ce_out        3.125e-10
// im_s_dig_1                    ce_out        3.125e-10
// Re_2                      ce_out        3.125e-10
// Re_s_2                    ce_out        3.125e-10
// Im_2                      ce_out        3.125e-10
// im_s_dig_2                    ce_out        3.125e-10
// Re_3                      ce_out        3.125e-10
// Re_s_3                    ce_out        3.125e-10
// Im_3                      ce_out        3.125e-10
// im_s_dig_3                    ce_out        3.125e-10
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: scpa_dig_ana_ppfir
// Source Path: scpa_ppfir_blocked_hybrid/scpa_dig_ana_ppfir
// Hierarchy Level: 0
// Model version: 1.67
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module scpa_dig_ana_ppfir
          (clk,
           rst_n,
           en,
           In1_re,
           In1_im,
           Re_0,
           Re_s_0,
           Im_0,
           Im_s_0,
           Re_1,
           Re_s_1,
           Im_1,
           Im_s_1,
           Re_2,
           Re_s_2,
           Im_2,
           Im_s_2,
           Re_3,
           Re_s_3,
           Im_3,
           Im_s_3);


  input   clk;
  input   rst_n;
  input   en;
  input   signed [11:0] In1_re;  // sfix13_En12
  input   signed [11:0] In1_im;  // sfix13_En12
  output  [255:0] Re_0;  // uint8
  output  Re_s_0;  // ufix1
  output  [255:0] Im_0;  // uint8
  output  Im_s_0;  // ufix1
  output  [255:0] Re_1;  // uint8
  output  Re_s_1;  // ufix1
  output  [255:0] Im_1;  // uint8
  output  Im_s_1;  // ufix1
  output  [255:0] Re_2;  // uint8
  output  Re_s_2;  // ufix1
  output  [255:0] Im_2;  // uint8
  output  Im_s_2;  // ufix1
  output  [255:0] Re_3;  // uint8
  output  Re_s_3;  // ufix1
  output  [255:0] Im_3;  // uint8
  output  Im_s_3;  // ufix1


  wire enb_1_8_0;
  wire enb_r8_1_32_1;
  wire enb_r8_1_8_1;
  wire signed [15:0] pp_int_x4_out1_re;  // sfix16_En15
  wire signed [15:0] pp_int_x4_out1_im;  // sfix16_En15
  wire [7:0] pp_fir_blocked_out1;  // uint8
  wire [7:0] pp_fir_blocked_out2;  // uint8
  wire pp_fir_blocked_out3;  // ufix1
  wire pp_fir_blocked_out4;  // ufix1
  wire [7:0] pp_fir_blocked_out5;  // uint8
  wire [7:0] pp_fir_blocked_out6;  // uint8
  wire pp_fir_blocked_out7;  // ufix1
  wire pp_fir_blocked_out8;  // ufix1
  wire [7:0] pp_fir_blocked_out9;  // uint8
  wire [7:0] pp_fir_blocked_out10;  // uint8
  wire pp_fir_blocked_out11;  // ufix1
  wire pp_fir_blocked_out12;  // ufix1
  wire [7:0] pp_fir_blocked_out13;  // uint8
  wire [7:0] pp_fir_blocked_out14;  // uint8
  wire pp_fir_blocked_out15;  // ufix1
  wire pp_fir_blocked_out16;  // ufix1
  wire [7:0] pp_fir_blocked_out17;  // uint8
  wire [7:0] pp_fir_blocked_out18;  // uint8
  wire pp_fir_blocked_out19;  // ufix1
  wire pp_fir_blocked_out20;  // ufix1
  wire [7:0] pp_fir_blocked_out21;  // uint8
  wire [7:0] pp_fir_blocked_out22;  // uint8
  wire pp_fir_blocked_out23;  // ufix1
  wire pp_fir_blocked_out24;  // ufix1
  wire [7:0] pp_fir_blocked_out25;  // uint8
  wire [7:0] pp_fir_blocked_out26;  // uint8
  wire pp_fir_blocked_out27;  // ufix1
  wire pp_fir_blocked_out28;  // ufix1
  wire [7:0] pp_fir_blocked_out29;  // uint8
  wire [7:0] pp_fir_blocked_out30;  // uint8
  wire pp_fir_blocked_out31;  // ufix1
  wire pp_fir_blocked_out32;  // ufix1
  wire [7:0] digPhaseCombiner_out1;  // uint8
  wire digPhaseCombiner1_out1;  // ufix1
  wire [7:0] digPhaseCombiner2_out1;  // uint8
  wire digPhaseCombiner3_out1;  // ufix1
  wire [7:0] digPhaseCombiner4_out1;  // uint8
  wire digPhaseCombiner5_out1;  // ufix1
  wire [7:0] digPhaseCombiner6_out1;  // uint8
  wire digPhaseCombiner7_out1;  // ufix1
  wire [7:0] digPhaseCombiner8_out1;  // uint8
  wire digPhaseCombiner9_out1;  // ufix1
  wire [7:0] digPhaseCombiner10_out1;  // uint8
  wire digPhaseCombiner11_out1;  // ufix1
  wire [7:0] digPhaseCombiner12_out1;  // uint8
  wire digPhaseCombiner13_out1;  // ufix1
  wire [7:0] digPhaseCombiner14_out1;  // uint8
  wire digPhaseCombiner15_out1;  // ufix1

  // Pipeline registers to break long path into b2u converters
  reg [7:0] re_pipe_0;
  reg [7:0] im_pipe_0;
  reg [7:0] re_pipe_1;
  reg [7:0] im_pipe_1;
  reg [7:0] re_pipe_2;
  reg [7:0] im_pipe_2;
  reg [7:0] re_pipe_3;
  reg [7:0] im_pipe_3;
  reg       re_s_pipe_0;
  reg       im_s_pipe_0;
  reg       re_s_pipe_1;
  reg       im_s_pipe_1;
  reg       re_s_pipe_2;
  reg       im_s_pipe_2;
  reg       re_s_pipe_3;
  reg       im_s_pipe_3;
  
  clkDiv #(.DIV(2)) clkDiv_1_2 (.clk_in(clk),
                                 .rst(rst_n),
                                 .clk_out(clk_2)
                                 );

  clkDiv #(.DIV(8)) clkDiv_1_8 (.clk_in(clk),
                                 .rst(rst_n),
                                 .clk_out(clk_8)
                                 ); 

  scpa_dig_ana_ppfir_tc scpa_dig_ana_ppfir_tc (.clk_1_8(clk_2),
                                               .rst_n_1_8(rst_n),
                                               .en_2(en),
                                               .enb_1_8_0(enb_1_8_0),
                                               .enb_r8_1_8_1(enb_r8_1_8_1),
                                               .enb_r8_1_32_1(enb_r8_1_32_1)
                                               );

  pp_int_x4 pp_int_x4_1_1 (.clk_1_8(clk_2),
                           .clk_1_32(clk_8),
                           .rst_n_1_8(rst_n),
                           .rst_n_1_32(rst_n),
                           .enb_1_8_0(enb_1_8_0),
                           .enb_1_32_0(en),
                           .enb_r8_1_32_1(enb_r8_1_32_1),
                           .enb_r8_1_8_1(enb_r8_1_8_1),
                           .In1_re(In1_re),  // sfix13_En12
                           .In1_im(In1_im),  // sfix13_En12
                           .Out1_re(pp_int_x4_out1_re),  // sfix16_En15
                           .Out1_im(pp_int_x4_out1_im)  // sfix16_En15
                           );

  pp_fir_blocked pp_fir_blocked_1_1 (.clk_1_8(clk_2),
                                     .rst_n_1_8(rst_n),
                                     .enb_1_8_0(enb_1_8_0),
                                     .In1_re(pp_int_x4_out1_re),  // sfix16_En15
                                     .In1_im(pp_int_x4_out1_im),  // sfix16_En15
                                     .Re_0(pp_fir_blocked_out1),  // uint8
                                     .Re_4(pp_fir_blocked_out2),  // uint8
                                     .Re_s_0(pp_fir_blocked_out3),  // ufix1
                                     .Re_s_4(pp_fir_blocked_out4),  // ufix1
                                     .Im_0(pp_fir_blocked_out5),  // uint8
                                     .Im_4(pp_fir_blocked_out6),  // uint8
                                     .Im_s_0(pp_fir_blocked_out7),  // ufix1
                                     .Im_s_4(pp_fir_blocked_out8),  // ufix1
                                     .Re_1(pp_fir_blocked_out9),  // uint8
                                     .Re_5(pp_fir_blocked_out10),  // uint8
                                     .Re_s_1(pp_fir_blocked_out11),  // ufix1
                                     .Re_s_5(pp_fir_blocked_out12),  // ufix1
                                     .Im_1(pp_fir_blocked_out13),  // uint8
                                     .Im_5(pp_fir_blocked_out14),  // uint8
                                     .Im_s_1(pp_fir_blocked_out15),  // ufix1
                                     .Im_s_5(pp_fir_blocked_out16),  // ufix1
                                     .Re_2(pp_fir_blocked_out17),  // uint8
                                     .Re_6(pp_fir_blocked_out18),  // uint8
                                     .Re_s_2(pp_fir_blocked_out19),  // ufix1
                                     .Re_s_6(pp_fir_blocked_out20),  // ufix1
                                     .Im_2(pp_fir_blocked_out21),  // uint8
                                     .Im_6(pp_fir_blocked_out22),  // uint8
                                     .Im_s_2(pp_fir_blocked_out23),  // ufix1
                                     .Im_s_6(pp_fir_blocked_out24),  // ufix1
                                     .Re_3(pp_fir_blocked_out25),  // uint8
                                     .Re_7(pp_fir_blocked_out26),  // uint8
                                     .Re_s_3(pp_fir_blocked_out27),  // ufix1
                                     .Re_s_7(pp_fir_blocked_out28),  // ufix1
                                     .Im_3(pp_fir_blocked_out29),  // uint8
                                     .Im_7(pp_fir_blocked_out30),  // uint8
                                     .Im_s_3(pp_fir_blocked_out31),  // ufix1
                                     .Im_s_7(pp_fir_blocked_out32)  // ufix1
                                     );

  digPhaseCombiner dpc_re_0 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out1),  // uint8
                             .In2(pp_fir_blocked_out2),  // uint8
                             .re_dig_0(digPhaseCombiner_out1)  // uint8
                            );

  digSignCombiner dsc_re_0 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out3),  // ufix1
                            .In2(pp_fir_blocked_out4),  // ufix1
                            .re_s_dig_0(digPhaseCombiner1_out1)  // uint8
                            );

  digPhaseCombiner dpc_im_0 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out5),  // uint8
                             .In2(pp_fir_blocked_out6),  // uint8
                             .re_dig_0(digPhaseCombiner2_out1)  // uint8
                            );

  digSignCombiner dsc_im_0 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out7),  // ufix1
                            .In2(pp_fir_blocked_out8),  // ufix1
                            .re_s_dig_0(digPhaseCombiner3_out1)  // uint8
                            );

  b2u_8to255_quad b2u_8to255_quad_1 (.clk(clk),
                                     .rst(rst_n),
                                     .enable(enb_1_8_0),
                                     .iIn(re_pipe_0),
                                     .qIn(im_pipe_0),
                                     .iMsb(1'b0),
                                     .qMsb(1'b0),
                                     .iOut(Re_0),
                                     .qOut(Im_0)
                                       );

  digPhaseCombiner dpc_re_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out9),  // uint8
                             .In2(pp_fir_blocked_out10),  // uint8
                             .re_dig_0(digPhaseCombiner4_out1)  // uint8
                            );

  digSignCombiner dsc_re_1 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out11),  // ufix1
                            .In2(pp_fir_blocked_out12),  // ufix1
                            .re_s_dig_0(digPhaseCombiner5_out1)  // uint8
                            );

  digPhaseCombiner dpc_im_1 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out13),  // uint8
                             .In2(pp_fir_blocked_out14),  // uint8
                             .re_dig_0(digPhaseCombiner6_out1)  // uint8
                             );

  digSignCombiner dsc_im_1 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out15),  // ufix1
                            .In2(pp_fir_blocked_out16),  // ufix1
                            .re_s_dig_0(digPhaseCombiner7_out1)  // uint8
                            );

  b2u_8to255_quad b2u_8to255_quad_2 (.clk(clk),
                                     .rst(rst_n),
                                     .enable(enb_1_8_0),
                                     .iIn(re_pipe_1),
                                     .qIn(im_pipe_1),
                                     .iMsb(1'b0),
                                     .qMsb(1'b0),
                                     .iOut(Re_1),
                                     .qOut(Im_1)
                                       );

  digPhaseCombiner dpc_re_2 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out17),  // uint8
                             .In2(pp_fir_blocked_out18),  // uint8
                             .re_dig_0(digPhaseCombiner8_out1)  // uint8
                            );

  digSignCombiner dsc_re_2 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out19),  // ufix1
                            .In2(pp_fir_blocked_out20),  // ufix1
                            .re_s_dig_0(digPhaseCombiner9_out1)  // uint8
                            );

  digPhaseCombiner dpc_im_2 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out21),  // uint8
                             .In2(pp_fir_blocked_out22),  // uint8
                             .re_dig_0(digPhaseCombiner10_out1)  // uint8
                            );

  digSignCombiner dsc_im_2 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out23),  // ufix1
                            .In2(pp_fir_blocked_out24),  // ufix1
                            .re_s_dig_0(digPhaseCombiner11_out1)  // uint8
                            );

  b2u_8to255_quad b2u_8to255_quad_3 (.clk(clk),
                                     .rst(rst_n),
                                     .enable(enb_1_8_0),
                                     .iIn(re_pipe_2),
                                     .qIn(im_pipe_2),
                                     .iMsb(1'b0),
                                     .qMsb(1'b0),
                                     .iOut(Re_2),
                                     .qOut(Im_2)
                                       );

  digPhaseCombiner dpc_re_3 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out25),  // uint8
                             .In2(pp_fir_blocked_out26),  // uint8
                             .re_dig_0(digPhaseCombiner12_out1)  // uint8
                             );

  digSignCombiner dsc_re_3 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out27),  // ufix1
                            .In2(pp_fir_blocked_out28),  // ufix1
                            .re_s_dig_0(digPhaseCombiner13_out1)  // uint8
                            );

  digPhaseCombiner dpc_im_3 (.clk(clk),
                             .rst_n(rst_n),
                             .enb_1_4_0(en),
                             .In1(pp_fir_blocked_out29),  // uint8
                             .In2(pp_fir_blocked_out30),  // uint8
                             .re_dig_0(digPhaseCombiner14_out1)  // uint8
                             );

  digSignCombiner dsc_im_3 (.clk(clk),
                            .rst_n(rst_n),
                            .enb_1_4_0(en),
                            .In1(pp_fir_blocked_out31),  // ufix1
                            .In2(pp_fir_blocked_out32),  // ufix1
                            .re_s_dig_0(digPhaseCombiner15_out1)  // uint8
                            );

  b2u_8to255_quad b2u_8to255_quad_4 (.clk(clk),
                                     .rst(rst_n),
                                     .enable(enb_1_8_0),
                                     .iIn(re_pipe_3),
                                     .qIn(im_pipe_3),
                                     .iMsb(1'b0),
                                     .qMsb(1'b0),
                                     .iOut(Re_3),
                                     .qOut(Im_3)
                                       );

  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      re_pipe_0   <= 8'd0;
      im_pipe_0   <= 8'd0;
      re_pipe_1   <= 8'd0;
      im_pipe_1   <= 8'd0;
      re_pipe_2   <= 8'd0;
      im_pipe_2   <= 8'd0;
      re_pipe_3   <= 8'd0;
      im_pipe_3   <= 8'd0;
      re_s_pipe_0 <= 1'b0;
      im_s_pipe_0 <= 1'b0;
      re_s_pipe_1 <= 1'b0;
      im_s_pipe_1 <= 1'b0;
      re_s_pipe_2 <= 1'b0;
      im_s_pipe_2 <= 1'b0;
      re_s_pipe_3 <= 1'b0;
      im_s_pipe_3 <= 1'b0;
    end else if (enb_1_8_0) begin
      re_pipe_0   <= digPhaseCombiner_out1;
      im_pipe_0   <= digPhaseCombiner2_out1;
      re_pipe_1   <= digPhaseCombiner4_out1;
      im_pipe_1   <= digPhaseCombiner6_out1;
      re_pipe_2   <= digPhaseCombiner8_out1;
      im_pipe_2   <= digPhaseCombiner10_out1;
      re_pipe_3   <= digPhaseCombiner12_out1;
      im_pipe_3   <= digPhaseCombiner14_out1;
      re_s_pipe_0 <= digPhaseCombiner1_out1;
      im_s_pipe_0 <= digPhaseCombiner3_out1;
      re_s_pipe_1 <= digPhaseCombiner5_out1;
      im_s_pipe_1 <= digPhaseCombiner7_out1;
      re_s_pipe_2 <= digPhaseCombiner9_out1;
      im_s_pipe_2 <= digPhaseCombiner11_out1;
      re_s_pipe_3 <= digPhaseCombiner13_out1;
      im_s_pipe_3 <= digPhaseCombiner15_out1;
    end
  end

  assign Re_s_0 = re_s_pipe_0;
  assign Im_s_0 = im_s_pipe_0;
  assign Re_s_1 = re_s_pipe_1;
  assign Im_s_1 = im_s_pipe_1;
  assign Re_s_2 = re_s_pipe_2;
  assign Im_s_2 = im_s_pipe_2;
  assign Re_s_3 = re_s_pipe_3;
  assign Im_s_3 = im_s_pipe_3;

endmodule  // scpa_dig_ana_ppfir

