// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_hybrid\scpa_ppfir_blocked_hybrid\signed_mag.v
// Created: 2026-01-12 13:19:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: signed_mag

// Source Path: scpa_ppfir_blocked_hybrid/scpa_dig_ana_ppfir/pp_fir_blocked/pp_fir_bottom_half/pp_fir_u_0/signed_mag
// Hierarchy Level: 4
// Model version: 1.67
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module signed_mag
          (In1_re,
           In1_im,
           mag_re,
           sign_re,
           mag_im,
           sign_im);


  input   signed [8:0] In1_re;  // sfix9
  input   signed [8:0] In1_im;  // sfix9
  output  [7:0] mag_re;  // uint8
  output  sign_re;  // ufix1
  output  [7:0] mag_im;  // uint8
  output  sign_im;  // ufix1


  wire signed [9:0] Abs1_y;  // sfix10
  wire signed [9:0] Abs1_1;  // sfix10
  wire [7:0] Abs1_out1;  // uint8
  wire Bit_Slice_out1;  // ufix1
  wire signed [9:0] Abs_rsvd_y;  // sfix10
  wire signed [9:0] Abs_rsvd_1;  // sfix10
  wire [7:0] Abs_out1;  // uint8
  wire Bit_Slice1_out1;  // ufix1


  assign Abs1_1 = {In1_re[8], In1_re};
  assign Abs1_y = (In1_re < 9'sb000000000 ?  - (Abs1_1) :
              {In1_re[8], In1_re});
  assign Abs1_out1 = Abs1_y[7:0];



  assign mag_re = Abs1_out1;

  assign Bit_Slice_out1 = In1_re[8];



  assign sign_re = Bit_Slice_out1;

  assign Abs_rsvd_1 = {In1_im[8], In1_im};
  assign Abs_rsvd_y = (In1_im < 9'sb000000000 ?  - (Abs_rsvd_1) :
              {In1_im[8], In1_im});
  assign Abs_out1 = Abs_rsvd_y[7:0];



  assign mag_im = Abs_out1;

  assign Bit_Slice1_out1 = In1_im[8];



  assign sign_im = Bit_Slice1_out1;

endmodule  // signed_mag

