// -------------------------------------------------------------
// 

// File Name: C:\Users\Owner\OneDrive - Virginia Tech\Research\Non-uniform Sampling RF-DAC\hdlsrc_pp_filter_blocked_total_v2\scpa_ppfir_blocked_total\subFilter_block.v
// Created: 2025-04-08 12:29:27
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter_block

// Source Path: scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR Interpolator/scpa_ppfir_blocked_total/pp_fir_blocked_total/pp_int_x4_v2/FIR 
// Interpolator/FIRFilter2/Filter/subFilte
// Hierarchy Level: 5
// Model version: 1.91
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter_block
          (clk,
           rst_n,
           enb_1_32_0,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           coefIn_11,
           coefIn_12,
           coefIn_13,
           coefIn_14,
           coefIn_15,
           coefIn_16,
           coefIn_17,
           coefIn_18,
           coefIn_19,
           coefIn_20,
           coefIn_21,
           coefIn_22,
           coefIn_23,
           coefIn_24,
           dinRegVld,
           syncReset,
           dout_1_re,
           doutVld);


  input   clk;
  input   rst_n;
  input   enb_1_32_0;
  input   signed [12:0] dinReg2_0_re;  // sfix13_En12
  input   signed [15:0] coefIn_0;  // sfix16_En15
  input   signed [15:0] coefIn_1;  // sfix16_En15
  input   signed [15:0] coefIn_2;  // sfix16_En15
  input   signed [15:0] coefIn_3;  // sfix16_En15
  input   signed [15:0] coefIn_4;  // sfix16_En15
  input   signed [15:0] coefIn_5;  // sfix16_En15
  input   signed [15:0] coefIn_6;  // sfix16_En15
  input   signed [15:0] coefIn_7;  // sfix16_En15
  input   signed [15:0] coefIn_8;  // sfix16_En15
  input   signed [15:0] coefIn_9;  // sfix16_En15
  input   signed [15:0] coefIn_10;  // sfix16_En15
  input   signed [15:0] coefIn_11;  // sfix16_En15
  input   signed [15:0] coefIn_12;  // sfix16_En15
  input   signed [15:0] coefIn_13;  // sfix16_En15
  input   signed [15:0] coefIn_14;  // sfix16_En15
  input   signed [15:0] coefIn_15;  // sfix16_En15
  input   signed [15:0] coefIn_16;  // sfix16_En15
  input   signed [15:0] coefIn_17;  // sfix16_En15
  input   signed [15:0] coefIn_18;  // sfix16_En15
  input   signed [15:0] coefIn_19;  // sfix16_En15
  input   signed [15:0] coefIn_20;  // sfix16_En15
  input   signed [15:0] coefIn_21;  // sfix16_En15
  input   signed [15:0] coefIn_22;  // sfix16_En15
  input   signed [15:0] coefIn_23;  // sfix16_En15
  input   signed [15:0] coefIn_24;  // sfix16_En15
  input   dinRegVld;
  input   syncReset;
  output  signed [15:0] dout_1_re;  // sfix16_En15
  output  doutVld;


  reg  [27:0] intdelay_reg;  // ufix1 [28]
  wire vldShift;
  wire vldOutTmp;
  wire signed [15:0] ZERO_OUT;  // sfix16_En15
  wire signed [28:0] addin;  // sfix29_En27
  wire signed [12:0] dinDly2;  // sfix13_En12
  wire signed [28:0] tapout;  // sfix29_En27
  wire signed [12:0] dinDly2_1;  // sfix13_En12
  wire signed [28:0] tapout_1;  // sfix29_En27
  wire signed [12:0] dinDly2_2;  // sfix13_En12
  wire signed [28:0] tapout_2;  // sfix29_En27
  wire signed [12:0] dinDly2_3;  // sfix13_En12
  wire signed [28:0] tapout_3;  // sfix29_En27
  wire signed [12:0] dinDly2_4;  // sfix13_En12
  wire signed [28:0] tapout_4;  // sfix29_En27
  wire signed [12:0] dinDly2_5;  // sfix13_En12
  wire signed [28:0] tapout_5;  // sfix29_En27
  wire signed [12:0] dinDly2_6;  // sfix13_En12
  wire signed [28:0] tapout_6;  // sfix29_En27
  wire signed [12:0] dinDly2_7;  // sfix13_En12
  wire signed [28:0] tapout_7;  // sfix29_En27
  wire signed [12:0] dinDly2_8;  // sfix13_En12
  wire signed [28:0] tapout_8;  // sfix29_En27
  wire signed [12:0] dinDly2_9;  // sfix13_En12
  wire signed [28:0] tapout_9;  // sfix29_En27
  wire signed [12:0] dinDly2_10;  // sfix13_En12
  wire signed [28:0] tapout_10;  // sfix29_En27
  wire signed [12:0] dinDly2_11;  // sfix13_En12
  wire signed [28:0] tapout_11;  // sfix29_En27
  wire signed [12:0] dinDly2_12;  // sfix13_En12
  wire signed [28:0] tapout_12;  // sfix29_En27
  wire signed [12:0] dinDly2_13;  // sfix13_En12
  wire signed [28:0] tapout_13;  // sfix29_En27
  wire signed [12:0] dinDly2_14;  // sfix13_En12
  wire signed [28:0] tapout_14;  // sfix29_En27
  wire signed [12:0] dinDly2_15;  // sfix13_En12
  wire signed [28:0] tapout_15;  // sfix29_En27
  wire signed [12:0] dinDly2_16;  // sfix13_En12
  wire signed [28:0] tapout_16;  // sfix29_En27
  wire signed [12:0] dinDly2_17;  // sfix13_En12
  wire signed [28:0] tapout_17;  // sfix29_En27
  wire signed [12:0] dinDly2_18;  // sfix13_En12
  wire signed [28:0] tapout_18;  // sfix29_En27
  wire signed [12:0] dinDly2_19;  // sfix13_En12
  wire signed [28:0] tapout_19;  // sfix29_En27
  wire signed [12:0] dinDly2_20;  // sfix13_En12
  wire signed [28:0] tapout_20;  // sfix29_En27
  wire signed [12:0] dinDly2_21;  // sfix13_En12
  wire signed [28:0] tapout_21;  // sfix29_En27
  wire signed [12:0] dinDly2_22;  // sfix13_En12
  wire signed [28:0] tapout_22;  // sfix29_En27
  wire signed [12:0] dinDly2_23;  // sfix13_En12
  wire signed [28:0] tapout_23;  // sfix29_En27
  wire signed [28:0] tapout_24;  // sfix29_En27
  wire signed [15:0] dout_cast;  // sfix16_En15
  wire signed [15:0] muxOut;  // sfix16_En15
  reg signed [15:0] dout_1_re_1;  // sfix16_En15
  reg  doutVld_1;


  always @(posedge clk or negedge rst_n)
    begin : intdelay_process
      if (rst_n == 1'b0) begin
        intdelay_reg <= {28{1'b0}};
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {28{1'b0}};
          end
          else begin
            if (dinRegVld) begin
              intdelay_reg[0] <= dinRegVld;
              intdelay_reg[32'sd27:32'sd1] <= intdelay_reg[32'sd26:32'sd0];
            end
          end
        end
      end
    end

  assign vldShift = intdelay_reg[27];



  assign vldOutTmp = dinRegVld & vldShift;



  assign ZERO_OUT = 16'sb0000000000000000;



  assign addin = 29'sb00000000000000000000000000000;



  FilterTapSystolicWvldin FilterTap_1_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinReg2_0_re),  // sfix13_En12
                                         .coefIn_0(coefIn_0),  // sfix16_En15
                                         .addin(addin),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2),  // sfix13_En12
                                         .tapout(tapout)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_2_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2),  // sfix13_En12
                                         .coefIn_0(coefIn_1),  // sfix16_En15
                                         .addin(tapout),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_1),  // sfix13_En12
                                         .tapout(tapout_1)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_3_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2_1),  // sfix13_En12
                                         .coefIn_0(coefIn_2),  // sfix16_En15
                                         .addin(tapout_1),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_2),  // sfix13_En12
                                         .tapout(tapout_2)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_4_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2_2),  // sfix13_En12
                                         .coefIn_0(coefIn_3),  // sfix16_En15
                                         .addin(tapout_2),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_3),  // sfix13_En12
                                         .tapout(tapout_3)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_5_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2_3),  // sfix13_En12
                                         .coefIn_0(coefIn_4),  // sfix16_En15
                                         .addin(tapout_3),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_4),  // sfix13_En12
                                         .tapout(tapout_4)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_6_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2_4),  // sfix13_En12
                                         .coefIn_0(coefIn_5),  // sfix16_En15
                                         .addin(tapout_4),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_5),  // sfix13_En12
                                         .tapout(tapout_5)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_7_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2_5),  // sfix13_En12
                                         .coefIn_0(coefIn_6),  // sfix16_En15
                                         .addin(tapout_5),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_6),  // sfix13_En12
                                         .tapout(tapout_6)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_8_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2_6),  // sfix13_En12
                                         .coefIn_0(coefIn_7),  // sfix16_En15
                                         .addin(tapout_6),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_7),  // sfix13_En12
                                         .tapout(tapout_7)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_9_1 (.clk(clk),
                                         .rst_n(rst_n),
                                         .enb_1_32_0(enb_1_32_0),
                                         .dinReg2_0_re(dinDly2_7),  // sfix13_En12
                                         .coefIn_0(coefIn_8),  // sfix16_En15
                                         .addin(tapout_7),  // sfix29_En27
                                         .dinRegVld(dinRegVld),
                                         .syncReset(syncReset),
                                         .dinDly2(dinDly2_8),  // sfix13_En12
                                         .tapout(tapout_8)  // sfix29_En27
                                         );

  FilterTapSystolicWvldin FilterTap_10_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_8),  // sfix13_En12
                                          .coefIn_0(coefIn_9),  // sfix16_En15
                                          .addin(tapout_8),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_9),  // sfix13_En12
                                          .tapout(tapout_9)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_11_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_9),  // sfix13_En12
                                          .coefIn_0(coefIn_10),  // sfix16_En15
                                          .addin(tapout_9),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_10),  // sfix13_En12
                                          .tapout(tapout_10)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_12_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_10),  // sfix13_En12
                                          .coefIn_0(coefIn_11),  // sfix16_En15
                                          .addin(tapout_10),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_11),  // sfix13_En12
                                          .tapout(tapout_11)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_13_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_11),  // sfix13_En12
                                          .coefIn_0(coefIn_12),  // sfix16_En15
                                          .addin(tapout_11),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_12),  // sfix13_En12
                                          .tapout(tapout_12)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_14_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_12),  // sfix13_En12
                                          .coefIn_0(coefIn_13),  // sfix16_En15
                                          .addin(tapout_12),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_13),  // sfix13_En12
                                          .tapout(tapout_13)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_15_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_13),  // sfix13_En12
                                          .coefIn_0(coefIn_14),  // sfix16_En15
                                          .addin(tapout_13),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_14),  // sfix13_En12
                                          .tapout(tapout_14)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_16_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_14),  // sfix13_En12
                                          .coefIn_0(coefIn_15),  // sfix16_En15
                                          .addin(tapout_14),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_15),  // sfix13_En12
                                          .tapout(tapout_15)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_17_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_15),  // sfix13_En12
                                          .coefIn_0(coefIn_16),  // sfix16_En15
                                          .addin(tapout_15),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_16),  // sfix13_En12
                                          .tapout(tapout_16)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_18_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_16),  // sfix13_En12
                                          .coefIn_0(coefIn_17),  // sfix16_En15
                                          .addin(tapout_16),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_17),  // sfix13_En12
                                          .tapout(tapout_17)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_19_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_17),  // sfix13_En12
                                          .coefIn_0(coefIn_18),  // sfix16_En15
                                          .addin(tapout_17),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_18),  // sfix13_En12
                                          .tapout(tapout_18)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_20_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_18),  // sfix13_En12
                                          .coefIn_0(coefIn_19),  // sfix16_En15
                                          .addin(tapout_18),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_19),  // sfix13_En12
                                          .tapout(tapout_19)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_21_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_19),  // sfix13_En12
                                          .coefIn_0(coefIn_20),  // sfix16_En15
                                          .addin(tapout_19),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_20),  // sfix13_En12
                                          .tapout(tapout_20)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_22_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_20),  // sfix13_En12
                                          .coefIn_0(coefIn_21),  // sfix16_En15
                                          .addin(tapout_20),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_21),  // sfix13_En12
                                          .tapout(tapout_21)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_23_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_21),  // sfix13_En12
                                          .coefIn_0(coefIn_22),  // sfix16_En15
                                          .addin(tapout_21),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_22),  // sfix13_En12
                                          .tapout(tapout_22)  // sfix29_En27
                                          );

  FilterTapSystolicWvldin FilterTap_24_1 (.clk(clk),
                                          .rst_n(rst_n),
                                          .enb_1_32_0(enb_1_32_0),
                                          .dinReg2_0_re(dinDly2_22),  // sfix13_En12
                                          .coefIn_0(coefIn_23),  // sfix16_En15
                                          .addin(tapout_22),  // sfix29_En27
                                          .dinRegVld(dinRegVld),
                                          .syncReset(syncReset),
                                          .dinDly2(dinDly2_23),  // sfix13_En12
                                          .tapout(tapout_23)  // sfix29_En27
                                          );

  FilterTapSystolicWvldInC0_block FilterTap_25_1 (.clk(clk),
                                                  .rst_n(rst_n),
                                                  .enb_1_32_0(enb_1_32_0),
                                                  .dinReg2_0_re(dinDly2_23),  // sfix13_En12
                                                  .addin(tapout_23),  // sfix29_En27
                                                  .dinRegVld(dinRegVld),
                                                  .syncReset(syncReset),
                                                  .tapout(tapout_24)  // sfix29_En27
                                                  );

  assign dout_cast = tapout_24[27:12];



  assign muxOut = (vldOutTmp == 1'b0 ? ZERO_OUT :
              dout_cast);



  always @(posedge clk or negedge rst_n)
    begin : intdelay_1_process
      if (rst_n == 1'b0) begin
        dout_1_re_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 16'sb0000000000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end



  always @(posedge clk or negedge rst_n)
    begin : intdelay_2_process
      if (rst_n == 1'b0) begin
        doutVld_1 <= 1'b0;
      end
      else begin
        if (enb_1_32_0) begin
          if (syncReset == 1'b1) begin
            doutVld_1 <= 1'b0;
          end
          else begin
            doutVld_1 <= vldOutTmp;
          end
        end
      end
    end



  assign dout_1_re = dout_1_re_1;

  assign doutVld = doutVld_1;

endmodule  // subFilter_block

