
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Jan 25 2026 21:08:09 EST (Jan 26 2026 02:08:09 UTC)

// Verification Directory fv/b2u_3b_static 

module b2u_3b_static(IN, BGREN);
  input [2:0] IN;
  output [6:0] BGREN;
  wire [2:0] IN;
  wire [6:0] BGREN;
  wire n_1;
  assign BGREN[3] = IN[2];
  AND2_X0P7M_A9PP140ZTS_C30 g141__2398(.A (BGREN[5]), .B (IN[0]), .Y
       (BGREN[6]));
  NAND2XB_X2M_A9PP140ZTS_C30 g142__5107(.A (n_1), .BN (IN[2]), .Y
       (BGREN[0]));
  NOR2XB_X2M_A9PP140ZTS_C30 g143__6260(.A (n_1), .BN (IN[2]), .Y
       (BGREN[4]));
  AO21_X1M_A9PP140ZTS_C30 g144__4319(.A0 (IN[1]), .A1 (IN[0]), .B0
       (IN[2]), .Y (BGREN[2]));
  OR2_X0P7B_A9PP140ZTS_C30 g145__8428(.A (IN[1]), .B (IN[2]), .Y
       (BGREN[1]));
  NOR2_X0P7B_A9PP140ZTS_C30 g146__5526(.A (IN[1]), .B (IN[0]), .Y
       (n_1));
  AND2_X0P7M_A9PP140ZTS_C30 g147__6783(.A (IN[1]), .B (IN[2]), .Y
       (BGREN[5]));
endmodule

