# This is an internal file generated by Innovus v22.10-p001_1 on Sun Feb  2 13:11:15 2025

qxDPInvokeSignOffExtractionCCEJob -jobid 7 -numjobs 16 \
		47454 47454 1 1 \
		"extLogDir/IQuantus_02-Feb-2025_13:10:50_47454_pT8pcA/.extr.pp_int_x4.0.parallel_proc.47454_7.res" "xyz"
