# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# in combination with the "applet" infrastructure
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

set location(::applet::ff_edi) [list source [file join $dir ff_edi/ff_edi.tcl]]
set location(::applet::foundationflow) [list source [file join $dir foundationflow/foundationflow.tcl]]
set location(::applet::generate_report) [list source [file join $dir generate_report/generate_report.tcl]]
set location(::applet::measure) [list source [file join $dir measure/measure.tcl]]
set location(::applet::phys_qos_edi_stats) [list source [file join $dir phys_qos_edi_stats/phys_qos_edi_stats.tcl]]
set location(::applet::set_cost_groups) [list source [file join $dir set_cost_groups/set_cost_groups.tcl]]
set location(::applet::time_info) [list source [file join $dir time_info/time_info.tcl]]
set location(::applet::time_info_api) [list source [file join $dir time_info_api/time_info_api.tcl]]

foreach pkgName [array names location] {
    if {![file exists [lindex $location(${pkgName}) end]]} { regsub "\\.tcl" $location(${pkgName}) ".etf" location(${pkgName}) } 
}

package ifneeded ::applet::ff_edi 1.9 $location(::applet::ff_edi)
package ifneeded ::applet::foundationflow 1.162 $location(::applet::foundationflow)
package ifneeded ::applet::generate_report 1.64 $location(::applet::generate_report)
package ifneeded ::applet::measure 1.69 $location(::applet::measure)
package ifneeded ::applet::phys_qos_edi_stats 1.1 $location(::applet::phys_qos_edi_stats)
package ifneeded ::applet::set_cost_groups 1.10 $location(::applet::set_cost_groups)
package ifneeded ::applet::time_info 1.40 $location(::applet::time_info)
package ifneeded ::applet::time_info_api 1.5 $location(::applet::time_info_api)
