// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\mash_111\mash111_tb.v
// Created: 2024-03-25 18:29:07
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 5e-08
// Target subsystem base rate: 5e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: mash111_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module mash111_tb;



  reg  clk;
  reg  rst;
  wire clk_enable;
  wire Out1_done;  // ufix1
  wire rdEnb;
  wire Out1_done_enb;  // ufix1
  reg [20:0] Out1_addr;  // ufix21
  wire Out1_active;  // ufix1
  reg [20:0] conv_out1_addr;  // ufix21
  wire conv_out1_active;  // ufix1
  reg  tb_enb_delay;
  wire conv_out1_enb;  // ufix1
  wire [20:0] conv_out1_addr_delay_1;  // ufix21
  reg signed [31:0] fp_In1;  // sfix32
  reg signed [42:0] rawData_In1;  // sfix43_En42
  reg signed [31:0] status_In1;  // sfix32
  reg signed [42:0] holdData_In1;  // sfix43_En42
  reg signed [42:0] In1_offset;  // sfix43_En42
  wire signed [42:0] In1;  // sfix43_En42
  reg  check1_done;  // ufix1
  wire snkDonen;
  wire tb_enb;
  wire ce_out;
  wire signed [4:0] Out1;  // sfix5_En1
  wire Out1_enb;  // ufix1
  wire Out1_lastAddr;  // ufix1
  wire [20:0] Out1_addr_delay_1;  // ufix21
  reg signed [31:0] fp_Out1_expected;  // sfix32
  reg signed [4:0] Out1_expected;  // sfix5_En1
  reg signed [31:0] status_Out1_expected;  // sfix32
  wire signed [4:0] Out1_ref;  // sfix5_En1
  reg  Out1_testFailure;  // ufix1
  wire testFailure;  // ufix1


  assign Out1_done_enb = Out1_done & rdEnb;



  assign Out1_active = Out1_addr != 21'b100000000000001100100;



  assign conv_out1_active = conv_out1_addr != 21'b100000000000001100100;



  assign conv_out1_enb = conv_out1_active & (rdEnb & tb_enb_delay);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1048676
  always @(posedge clk or negedge rst)
    begin : conv_process
      if (rst == 1'b0) begin
        conv_out1_addr <= 21'b000000000000000000000;
      end
      else begin
        if (conv_out1_enb) begin
          if (conv_out1_addr >= 21'b100000000000001100100) begin
            conv_out1_addr <= 21'b000000000000000000000;
          end
          else begin
            conv_out1_addr <= conv_out1_addr + 21'b000000000000000000001;
          end
        end
      end
    end



  assign #1 conv_out1_addr_delay_1 = conv_out1_addr;

  // Data source for In1
  initial
    begin : In1_fileread
      fp_In1 = $fopen("In1.dat", "r");
      status_In1 = $rewind(fp_In1);
    end

  always @(conv_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_In1 <= 43'bx;
      end
      else if (rdEnb == 1) begin
        status_In1 = $fscanf(fp_In1, "%h", rawData_In1);
      end
    end

  // holdData reg for conv_out1
  always @(posedge clk or negedge rst)
    begin : stimuli_conv_out1
      if (!rst) begin
        holdData_In1 <= 43'bx;
      end
      else begin
        holdData_In1 <= rawData_In1;
      end
    end

  always @(rawData_In1 or rdEnb)
    begin : stimuli_conv_out1_1
      if (rdEnb == 1'b0) begin
        In1_offset <= holdData_In1;
      end
      else begin
        In1_offset <= rawData_In1;
      end
    end

  assign #2 In1 = In1_offset;

  assign snkDonen =  ~ check1_done;



  assign tb_enb = rst & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk or negedge rst)
    begin : u_enable_delay
      if (!rst) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (check1_done == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : rst_gen
      rst <= 1'b0;
      # (20);
      @ (posedge clk)
      # (2);
      rst <= 1'b1;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  mash111 u_mash111 (.clk(clk),
                     .rst(rst),
                     .clk_enable(clk_enable),
                     .In1(In1),  // sfix43_En42
                     .ce_out(ce_out),
                     .Out1(Out1)  // sfix5_En1
                     );

  assign Out1_enb = ce_out & Out1_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 1048676
  always @(posedge clk or negedge rst)
    begin : c_2_process
      if (rst == 1'b0) begin
        Out1_addr <= 21'b000000000000000000000;
      end
      else begin
        if (Out1_enb) begin
          if (Out1_addr >= 21'b100000000000001100100) begin
            Out1_addr <= 21'b000000000000000000000;
          end
          else begin
            Out1_addr <= Out1_addr + 21'b000000000000000000001;
          end
        end
      end
    end



  assign Out1_lastAddr = Out1_addr >= 21'b100000000000001100100;



  assign Out1_done = Out1_lastAddr & rst;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or negedge rst)
    begin : checkDone_1
      if (!rst) begin
        check1_done <= 0;
      end
      else begin
        if (Out1_done_enb) begin
          check1_done <= Out1_done;
        end
      end
    end

  assign #1 Out1_addr_delay_1 = Out1_addr;

  // Data source for Out1_expected
  initial
    begin : Out1_expected_fileread
      fp_Out1_expected = $fopen("Out1_expected.dat", "r");
      status_Out1_expected = $rewind(fp_Out1_expected);
    end

  always @(Out1_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        Out1_expected <= 5'bx;
      end
      else if (ce_out == 1) begin
        status_Out1_expected = $fscanf(fp_Out1_expected, "%h", Out1_expected);
      end
    end

  assign Out1_ref = Out1_expected;

  always @(posedge clk or negedge rst)
    begin : Out1_checker
      if (rst == 1'b0) begin
        Out1_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && Out1 !== Out1_ref) begin
          Out1_testFailure <= 1'b1;
          $display("ERROR in Out1 at time %t : Expected '%h' Actual '%h'", $time, Out1_ref, Out1);
        end
      end
    end

  assign testFailure = Out1_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // mash111_tb

