# This is an internal file generated by Innovus v22.10-p001_1 on Sat Jan 25 08:03:18 2025

qxDPInvokeSignOffExtractionCCEJob -jobid 9 -numjobs 16 \
		30989 30989 1 1 \
		"extLogDir/IQuantus_24-Jan-2025_21:51:01_30989_GqWLlq/.extr.pp_int_x4.1.parallel_proc.30989_9.res" "xyz"
